### ISSUE TITLE
UI - Rate Management - Browse Rate Schedules

### ISSUE THREAD

**Issue by ZahidRavian** [asifjans/Inovedia#10]
1) On Rate Schedule Item popup, "Rate Plan" drop down will have 1st entry <None>.

2) On Rate Schedule Item popup, "Mobile Profile" drop down will have 1st entry *

**Comment by nawabanjum** [comment]
done

**Comment by ZahidRavian** [comment]
Validation on Rate Plan is " You must select Rate plan."
It will be " You must select rate plan."
First alphabet of first word will be Caps only. else will be in small case.

**Comment by ZahidRavian** [comment]
In Rate Schedule Item - Rate Schedule Calendar 
On Add/Edit/Copy Popup, when the check box "Specify Active Days" will be unchecked, all days will be checked and disabled. and when it is checked all days will be enabled.

**Comment by nawabanjum** [comment]
done take a look
