### ISSUE TITLE
Client Admin Portal feedback(3-3-2018)

### ISSUE THREAD

**Issue by shayanr262** [asifjans/Inovedia#105]

**Comment by shayanr262** [comment]
General:
1) All the reports that are exported have issues in their headings. Either they have repetitive words or incomplete or confusing description. Please rectify them as much as possible.
2) In the bottom of all results, I should have option of jumping to last and first page along with Previous and Next buttons.
3)

**Comment by shayanr262** [comment]
Dashboard:

3) It should have these columns/graphs as well: Total Monthly Sales, Total Active Ads and (if possible) Monthly total number of tickets sold for each denomination i.e. 200 tickets for 25 AED, 300 for AED 45 etc.

**Comment by shayanr262** [comment]
Account Management:

4) When I click suspend button, the message has “are you sure….”. Please make the “a” of “are” capital.
5) Asif and Wela account status was appearing suspended but button was showing normal status. So I suspended it and then again restored it and then the status became normal.
6) Mr. Wela Ted email is not showing. User who signup using facebook there emails is not showing.
7) There is no provision for deleting the customer account permanently.
8) I keep getting logged out again and again. Session expiry time should be one hour.
9) The date format in all sections should be DD/MM/YYYY.
10) I don’t see customer ID section anywhere. It is supposed to be printed on the ticket

**Comment by shayanr262** [comment]
Ad management:
11) When I click View Details, the car images are not being shown.
12) The admin should be able to change the feature of sold to unsold. Once I clicked on Sold button, I’m not able to revert it back to unsold. 
13) In export files, Featured column should have Yes and No instead of True.
14) In export files, Ticket Quantity is 750 whereas it should be 600.
15) In export files, Car Make, Model and Year should also be there.
16) When I click restore button, the message has “are you sure….”. Please make the “a” of “are” capital.
17) No option for permanently deleting the ad.

**Comment by shayanr262** [comment]
Ticket Management:

18) The search field should have Purchase Date From and Purchase Date To fields.
19) Raffle Draw Icon on Ticket Management and Ad Management are different. Make them similar to avoid confusion.
20) When I move cursor to any field like minimize, cancel, expand etc, all have small alphabets at the start. Please make those words begin with capital letter.
21) In export files, Car Make, Model and Year should also be there.
22) When transferring the ticket, in “Transferred To” section, along with the Ad Reference Number search option, there should be some sort of option to select from all active ads in that particular price denomination. For example, I’m trying to transfer ticket of AED 25, then along with search option, there should be some functionality which will show or list down all the cars in AED 25.

**Comment by shayanr262** [comment]
Reward Points:

23) Admin should have option to delete anybody’s reward points or give them bonus reward points into account.
24) Admin should be able to credit anybody’s account with any number of reward points.
25) It should be able to generate the report of purchases made against report with user details, car details for which ticket is purchased, additional cash paid for ticket etc.

**Comment by shayanr262** [comment]
Ticket Sales Report:

26) The report should have four more columns; nationality, gender, age and full price of the car.
27) It should display number of tickets sold in each denomination and amount. The report currently being generated is fine. You can generate another report which should have only the above mentioned things with the following format. If I search by inputting a single date in Search/Filter section of the admin page, then it should generate the report for that particular date. And if enter a To and From date e.g. for a week, then it should generate the following report for the whole week.
![sales_rprt](https://user-images.githubusercontent.com/35724117/36975525-2ee784c8-209c-11e8-9189-cab58c7e6f53.PNG)

**Comment by shayanr262** [comment]
Ticket Transfer Report:

28) When I export the report, instead of showing “From Ad” and “To Ad”, it shows “Ad Ref” and “Ad1 Ref” as headings which is confusing. It should clearly state From Ad and To Ad.

**Comment by shayanr262** [comment]
Ticket Refund Report:

29) Generate the separate report similar to the format that I mentioned in Ticket Sale Report section?

**Comment by ZarshaB** [comment]
30>> Once the ad is deactivated it cannot be featured. Please remove option of Featured for deactivated accounts.

**Comment by ZarshaB** [comment]
**Not Fixed**
6>> Can't check as Fb button is not working.
8>> Not Fixed.
13>> Not Fixed
19>> 
![image](https://user-images.githubusercontent.com/35685146/37199352-2e7763a0-23a3-11e8-8efd-d23c7ac7689e.png)

**New**
31>> Please put full stop at the end of message.
![image](https://user-images.githubusercontent.com/35685146/37199321-1c13255a-23a3-11e8-81ae-ffb50b34e095.png)

**Comment by ZarshaB** [comment]
"Re-opened" 
1>> On clicking on "Export" of "Ticket Sale Report", it is redirecting to error page.
![image](https://user-images.githubusercontent.com/35685146/37272165-a9694bea-25f7-11e8-8d44-0f0caa661470.png)

**Comment by ZarshaB** [comment]
30>> Re-opened.
![image](https://user-images.githubusercontent.com/35685146/37276087-a67c8de2-2602-11e8-9e5c-6941ea96885f.png)

**Comment by ZahidRavian** [comment]
These issues are fixed and ready for testing. 
1, 6, 26, 30, 31

**Comment by ZarshaB** [comment]
Fixed >> 1,26,30,31

Pending:
6>> Will be checked once Fb button functionality would be available.

**Comment by ZarshaB** [comment]
**Re-opened:**
23>> Currently Admin is having option for deleting record related to Reward points. My account had zero reward points as I won the lucky draw. I removed record from Admin and it took my reward points into negative. 
![image](https://user-images.githubusercontent.com/35685146/37509712-43a4b12a-291a-11e8-9fde-332d52f8ae62.png)

![image](https://user-images.githubusercontent.com/35685146/37509663-0fd5cee2-291a-11e8-8163-3eb8a939c4b7.png)

**Comment by ZarshaB** [comment]
27, 29 >> It seems okay. I need to discuss few points with sir about it and then I'll remove these two from here.

**Comment by ZarshaB** [comment]
25>> Dashboard issue:
https://github.com/asifjans/Inovedia/issues/106

**Comment by ZarshaB** [comment]
26>> Not Fixed:
Account Management: The date format in all sections should be DD/MM/YYYY

**Comment by ZarshaB** [comment]
27>> For transferring ticket,  current ad's reference number should not be available.
![image](https://user-images.githubusercontent.com/35685146/37554726-a0d24292-29fe-11e8-8255-9af964a688f6.png)

**Comment by ZarshaB** [comment]
23>> When I add reward points then it is visible in the history only.
![image](https://user-images.githubusercontent.com/35685146/37554867-b5fa2f0c-2a00-11e8-81c7-2dfeeffda3c6.png)
![image](https://user-images.githubusercontent.com/35685146/37554870-c0145af8-2a00-11e8-89f7-ad0d045e78b8.png)

**Comment by ZarshaB** [comment]
24>> Please also change it to "Ad..".
![image](https://user-images.githubusercontent.com/35685146/37587395-0a45cd60-2b81-11e8-9475-21cab5cc2315.png)

**Comment by ZarshaB** [comment]
25>> Please make the file name same as it is for other files.
![image](https://user-images.githubusercontent.com/35685146/37587444-2d1be130-2b81-11e8-8d09-4f8073bcb845.png)

![image](https://user-images.githubusercontent.com/35685146/37587468-3d28296c-2b81-11e8-9ff7-7f96e44abb5d.png)

**Comment by ZarshaB** [comment]
**Not Fixed**
23>> Currently Admin is having option for deleting record related to Reward points. My account had zero reward points as I won the lucky draw. I removed record from Admin and it took my reward points into negative.
![image](https://user-images.githubusercontent.com/35685146/37509712-43a4b12a-291a-11e8-9fde-332d52f8ae62.png)

![image](https://user-images.githubusercontent.com/35685146/37509663-0fd5cee2-291a-11e8-8163-3eb8a939c4b7.png)

**Comment by ZarshaB** [comment]
26>> I have total 35 points remaining in my account and I have no option to remove these 35 points.
![image](https://user-images.githubusercontent.com/35685146/37644591-1d270dca-2c46-11e8-9fdb-e936d192a54b.png)

**Comment by ZarshaB** [comment]
**Re-opened**
23>> I have total 35 points remaining in my account and I have no option to remove these 35 points. **(Fixed)**
![image](https://user-images.githubusercontent.com/35685146/37644591-1d270dca-2c46-11e8-9fdb-e936d192a54b.png)

**Comment by ZarshaB** [comment]
Issue 23 is due to  Issue 110 of https://github.com/asifjans/Inovedia/issues/87

**Comment by ZarshaB** [comment]
23>> It is now deleting reward points but in history it is showing reward points in negative.
![image](https://user-images.githubusercontent.com/35685146/37698399-9e39c448-2d04-11e8-823d-bfb6bcbf48b9.png)

**Comment by ZarshaB** [comment]
24>> It is accepting minus icons etc.
![image](https://user-images.githubusercontent.com/35685146/37720850-fc6488d8-2d49-11e8-808c-0048280151f0.png)

**Comment by ZarshaB** [comment]
2>> Still remaining.
