### ISSUE TITLE
Admin Portal- UI

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#107]

**Comment by ZarshaB** [comment]
1>> Please also change it to "Social Media" as we have changed it for site.
![image](https://user-images.githubusercontent.com/35685146/37023903-37ffbe9c-2149-11e8-9c98-3ef2d6956e28.png)

**Comment by ZarshaB** [comment]
2>> Please put full stop or exclamation mark at the end of all informative messages.
![image](https://user-images.githubusercontent.com/35685146/37024363-6dd5aed6-214a-11e8-9480-9e1909509b18.png)

**Comment by ZarshaB** [comment]
3>> Message is not correct. Please make it "Are you sure that you want to make this as Featured Ad?" 
![image](https://user-images.githubusercontent.com/35685146/37024447-b3ef6d08-214a-11e8-87f4-8f2c779fc564.png)

**Comment by ZarshaB** [comment]
4>> Please make it "Ad.." instead of "Add..".
![image](https://user-images.githubusercontent.com/35685146/37024968-3ef8937e-214c-11e8-98f0-9bc2a478a889.png)

**Comment by ZarshaB** [comment]
5>> Please make first letter capital and put full stop at the end.
![image](https://user-images.githubusercontent.com/35685146/37025283-18117c7a-214d-11e8-94ea-0baa47389767.png)

**Comment by ZarshaB** [comment]
6>> Please make it's first letter capital.
![image](https://user-images.githubusercontent.com/35685146/37025339-48f8b1be-214d-11e8-9b47-907e1695cdbc.png)

**Comment by ZarshaB** [comment]
7>> Put full stop at the end.
![image](https://user-images.githubusercontent.com/35685146/37025445-987403ec-214d-11e8-9802-8fd48e382681.png)

**Comment by ZarshaB** [comment]
8>> Please make it "Tickets Result".
![image](https://user-images.githubusercontent.com/35685146/37025505-bab29130-214d-11e8-9d99-937d1c481935.png)

**Comment by ZarshaB** [comment]
9>> Please put question mark at the end of questions.
![image](https://user-images.githubusercontent.com/35685146/37025544-d7b3b37c-214d-11e8-9b8b-8b2f4255d943.png)

**Comment by ZarshaB** [comment]
10>> Don't leave things open ended. Please do close messages and also make letters capital.
![image](https://user-images.githubusercontent.com/35685146/37025821-8596b3a4-214e-11e8-9e7e-44303f621601.png)

**Comment by ZarshaB** [comment]
11>> It is "WelaDela" instead of "WELADELA".
![image](https://user-images.githubusercontent.com/35685146/37026348-f00dcd84-214f-11e8-8ee9-c1da2ed3cc16.png)

**Comment by ZarshaB** [comment]
12>> Please make it "Deleted".
![image](https://user-images.githubusercontent.com/35685146/37083937-e6b9fbcc-2212-11e8-9f52-766523715ea0.png)

**Comment by ZarshaB** [comment]
13>> Please correct it. It would be "Sold".
![image](https://user-images.githubusercontent.com/35685146/37146654-31452cf6-22e6-11e8-8191-e50a22a47005.png)

**Comment by ZarshaB** [comment]
14>> Please remove decimal from price.
![image](https://user-images.githubusercontent.com/35685146/37275279-8ac3df9e-2600-11e8-8a38-4108882922d9.png)

**Comment by ZarshaB** [comment]
15>> When after clicking on Search I open calendar then it appears like this.
![image](https://user-images.githubusercontent.com/35685146/37648328-7c68ea42-2c50-11e8-9aa7-4f8e17b12c25.png)
![image](https://user-images.githubusercontent.com/35685146/37648342-8480eb26-2c50-11e8-836f-4670d68ceb7f.png)

**Comment by ZarshaB** [comment]
16>> It is accepting minus icons etc.
![image](https://user-images.githubusercontent.com/35685146/37720850-fc6488d8-2d49-11e8-808c-0048280151f0.png)

**Comment by ZarshaB** [comment]
17>> No favicon icon.
![image](https://user-images.githubusercontent.com/35685146/38258661-7e6812aa-377c-11e8-90c2-b4866c551a5a.png)

**Comment by ZahidRavian** [comment]
These issues are fixed and ready for testing.

1>> Please also change it to "Social Media" as we have changed it for site. (Fixed)
2>> Please put full stop or exclamation mark at the end of all informative messages. (Fixed)
3>> Message is not correct. Please make it "Are you sure you want to make this ad featured?" (Fixed)
5>> Please make first letter capital and put full stop at the end. (Fixed)
6>> Please make first letter of all messages capital and put full stop at the end. (Fixed)
7>> Put full stop at the end. (Fixed)
8>> Please make it "Tickets Result". (Fixed)
9>> Please put question mark at the end of questions. (Fixed)
10>> Don't leave things open ended. Please do close messages and also make letters capital. (Fixed)
11>> It is "WelaDela" instead of "WELADELA". (Fixed)
12>> Please make it "Deleted". (Fixed)
13>> Please correct it. It would be "Sold". (Fixed)
14>> Please remove decimal from price. (Fixed)

**Comment by ZarshaB** [comment]
Reopened
1>> Fixed for Ticket Management but not for Hear About Us Report page.
![image](https://user-images.githubusercontent.com/35685146/38548789-0fcbefec-3ccc-11e8-846f-3b516fcace21.png)

**Comment by ZarshaB** [comment]
6>> Not able to find this message. Will update it after I have found this message.
