### ISSUE TITLE
UI Website

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#109]

**Comment by ZarshaB** [comment]
1>> Label and placeholders are not at one line.
![image](https://user-images.githubusercontent.com/35685146/37139485-d580639c-22cf-11e8-84b8-99a5c8d2367f.png)

**Comment by ZarshaB** [comment]
2>> Main images cross sign and other image cross sign's placement is different.
![image](https://user-images.githubusercontent.com/35685146/37139568-321e4092-22d0-11e8-9559-bf0c071f6585.png)

**Comment by ZarshaB** [comment]
3>> Slider is overlapping.
![image](https://user-images.githubusercontent.com/35685146/37139690-9a130692-22d0-11e8-8e74-6b48406eb4ba.png)

**Comment by ZarshaB** [comment]
4>> Fb button flickers.

**Comment by ZarshaB** [comment]
5>> Please make it "Search Filters" instead of "Search Filter".
![image](https://user-images.githubusercontent.com/35685146/37215899-1fa07528-23db-11e8-98ff-b4b00af67e93.png)

**Comment by ZarshaB** [comment]
6>> Facebook button flickers.

**Comment by ZarshaB** [comment]
2>> It is still there.

**Comment by sammiullah** [comment]
2>> Main images cross sign and other image cross sign's placement is different. **(FIXED)**
![image](https://user-images.githubusercontent.com/35685146/37139568-321e4092-22d0-11e8-9559-bf0c071f6585.png)

**Comment by Anum444** [comment]
2>> Main images cross sign and other image cross sign's placement is different. **(FIXED)**
