### ISSUE TITLE
Multiple copies of Ads.

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#110]

**Comment by ZarshaB** [comment]
1>> If I click on Save button multiple times then Multiple copies of Ads are created.

**Comment by ZarshaB** [comment]
![image](https://user-images.githubusercontent.com/35685146/37140396-6bc1dbbc-22d3-11e8-8626-907ebf3b864c.png)

**Comment by asifjans** [comment]
Fixed.
