### ISSUE TITLE
Feedback Status App issues

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#111]

**Comment by asifjans** [comment]
@ ANUM

**Comment by asifjans** [comment]
@ Sami

**Comment by asifjans** [comment]
@ Haider

**Comment by asifjans** [comment]
@ Zahid

**Comment by asifjans** [comment]
**Client Feedback Pending issues:**
1: Feedback - Back button #130
2: Feedback - Templates #127
3: Feedback- Mobile Version #126
4: Feedback - Transfer Transfer #124
5: Feedback - Login #123
7: Feedback- Ticket #117
**Client Feedback Fixed issues:**
1: Feedback- Mobile #118
2: Feedback - Mobile - How it Works #119
3: Feedback - Change Password #120
4: Feedback- My Account #121
5: Feedback - My Account - Menu #122
6: Feedback - Purchase History #125
7: Feedback - Register #128
8: Feedback - Home #129

**Comment by asifjans** [comment]
Feedback - Car name #146 (Sami
Feedback- Billing Address #145 (Sami
Feedback - Reward Points #136
Feedback - Mobile #141 (Anum)

**Comment by Anum444** [comment]
2>> I'm seeing the slider overlapping.  (Sami_Fixed))
4>> Size is decreased but images are appearing compressed. (Anum_Fixed)
18>> Menu is not scrolling down. (Haider)
6>> Please also increase the size of Text and buttons. (Anum_FIXED)

**Comment by Anum444** [comment]
Feedback - Message change #155 (Sami)
Feedback - Purchase History #154 (Anum)
Image size of View Cars and Car Detail page #149 (Haider)

**Comment by sammiullah** [comment]
Feedback - Message change #155 (Sami) **FIXED**

**Comment by Anum444** [comment]
Feedback App Web Issues - 03/04/18 #148
8>> My Favorites: When I click on the Ad title, it is opening the ad in browser. It should be opened in the app. (Sami)
11>> Purchase History:  When I click on the Ad title, it is opening the ad in browser. It should be opened in the app. (Sami)
12>> Purchase History:  When I click on e-Ticket, it is opening in browser. It should open in app. (Sami)
5>> All headings like Terms & Conditions, FAQs etc shoould be moved a littler lower. They r touching the top banner (Anum)
14>> Please refer to attached picture. What is this grey line doing in reasons for deleting the ad? (Anum)
