### ISSUE TITLE
Client's Feedback 8th March 2018 - WEB UI

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#112]

**Comment by ZarshaB** [comment]
1>> As discussed, please remove the logo completely.

**Comment by ZarshaB** [comment]
2>> Please use Facebook instead of FB. The text in button should be neat with proper spacing from facebook logo.

**Comment by ZarshaB** [comment]
3>>Please give this line proper space from heading " Your Personal Details". It does not look neat this way.
![image](https://user-images.githubusercontent.com/35685146/37144553-3950bf56-22e0-11e8-8ea4-945fe3bdb0c9.png)

**Comment by ZarshaB** [comment]
4>> When the DOB is entered, it is shown as MM/DD/YYYY. It should be DD/MM/YYYY

**Comment by ZarshaB** [comment]
5>> This Z (like BMW Z3 and Z4)Looks highly unprofessional.

**Comment by ZarshaB** [comment]
6>> Please move the captcah a little lower. It is almost touching with the text above. Reduce the size of captcha by at least 20% and increase the size of Register button and also the size of text in it.

**Comment by ZarshaB** [comment]
7>> The button at the bottom should be read "View Full Screen".
![image](https://user-images.githubusercontent.com/35685146/37144651-7f465ce6-22e0-11e8-9008-b81388354a45.png)

**Comment by ZarshaB** [comment]
8>>  Please remove the two commas.
![image](https://user-images.githubusercontent.com/35685146/37144701-aa166768-22e0-11e8-9b1a-561297ddb4ee.png)

**Comment by ZarshaB** [comment]
9>> Please move all three buttons of "My Profile" page a little lower. Almost touching the Hear About US section. Also they should have some more space from Dowloand Our App footer.

**Comment by ZarshaB** [comment]
10>> Whenever I open the page in my browser, it goes to How it Works for a split second and then comes to banner. Please resolve.

**Comment by ZarshaB** [comment]
11>> When I place ad and goes to the admin for review, it appears as pending in my dashboard. But when I click on the ad from there, it opens the ad but the status in that ad is Sold Out. Please rectify.

**Comment by ZarshaB** [comment]
12>> I have been observing back button malfunctioning. I'll explain one scenario. I viewed the car and scrolled down to read description and then I clicked back arrow in the bar. Instead of taking me back to the previous page, it took me to the top of that particlau car ad page and when i clicked back again, it only then took me to previous page. Also, I removed a car from my favorites and then started browsing cars. Whenever I opened up an ad, and clicked back, it routed me to previous screen and always displayed the messgae of "listing removed from favorites" everytime even though I had browsed to 6-7 cars after removing the car. Please rectify.

**Comment by ZarshaB** [comment]
13>> Even though my account was deleted, but my ad was still there. How will we track the customer who has posted the ad but deleted the account? And what if he has deleted the account but his car has been sold? So in such cases where customer has a live ad or has bought the ticket and he presses the delete button, then his account should not be deleted. Instead he should be prompted the following message: 

                                       Not that Easily!!!

You have one active ad (or active ticket in case customer has bought a ticket) so we can't let you go. For more details, shoot us an email on info@weladela.com.

**Comment by ZarshaB** [comment]
14>> Some of the emails that I'm viewing on my mobile (both gmail and hotmail accounts) are improporaly formated. One screenshot is attached with the email for your reference.

**Comment by asifjans** [comment]
15) Anum please test email tempalate in mobile UI, those you developed.

**Comment by ZarshaB** [comment]
The font which is being used in actual template would be used.

**Comment by ZarshaB** [comment]
**Not Fixed**
2>> Spacing between logo and text should be a little more and also icon is appearing blur.
![image](https://user-images.githubusercontent.com/35685146/37198306-b14a78de-239f-11e8-8309-c9bb8a8b7dde.png)

4>> Not Fixed.
![image](https://user-images.githubusercontent.com/35685146/37198398-03c6e7dc-23a0-11e8-8f64-cc2cda77ba53.png)

5>> Should be confirmed from Client.

6>> Also increase the size of text in Register button.
![image](https://user-images.githubusercontent.com/35685146/37198464-2d16ad66-23a0-11e8-812b-acef0a7379b0.png)

9>> Please bring these buttons in middle.
![image](https://user-images.githubusercontent.com/35685146/37198497-50a63936-23a0-11e8-8c8c-39229bfe601a.png)

11>> If ad is not hyperlinked then it's color of title should be black.
![image](https://user-images.githubusercontent.com/35685146/37198524-722c0478-23a0-11e8-9e97-e791e7c7180f.png)

13>> Spacing of message is not correct. It should be similar to other messages. Also it should be "You have 5 active ad**s** **and** 16 **tickets** so ...." 
![image](https://user-images.githubusercontent.com/35685146/37198636-ca60aba8-23a0-11e8-80da-be654461ca72.png)

**Comment by asifjans** [comment]
6>> Also increase the size of text in Register button. **(Fixed)**
previous size of font was 12px and button was 148px. now the size of font is 16px and button size is 164px

**Comment by ZarshaB** [comment]
**Not Fixed**
11>> The ad's color is now black. But when I takes cursor on it, it's color changes and also cursor changes to clickable shape. It should not change it's color on hover and also not clickable.

**New:**
16>> Please also make this email linked as it is in "Points Redeem Policy".
![image](https://user-images.githubusercontent.com/35685146/37204626-5ed8f3be-23b3-11e8-89f7-09be56d0c3ac.png)

**Comment by ZarshaB** [comment]
Please also change this text as it is for Register page.
![image](https://user-images.githubusercontent.com/35685146/37215987-6684d696-23db-11e8-9133-661dc8f0d4e7.png)

**Comment by ZarshaB** [comment]
17>> As discussed, please see to what extent the video of "How it Works" can be enlarged without effecting the resolution and format.

**Comment by ZarshaB** [comment]
19>> Facebook login  button doesn't look neat at all. Please refer to  dubizzle. They have a separater line in between logo and the text. Please use that but keep word Login instead of Sign In

**Comment by ZarshaB** [comment]
23>> When I click on the link of forgot password email, the page displayed has shown some errors which were not there earlier. Under the heading Reset Your Password, text should read: "Please enter new password having minimum 6 characters."

When the customer enters the less than 6 characters, then the error message should read : "Minimum 6 characters required."

Same error message should be displayed when I change the password from My Account section.
![image](https://user-images.githubusercontent.com/35685146/37274139-9b1e5228-25fd-11e8-9294-d19e46527a15.png)

**Comment by ZarshaB** [comment]
24>> When I opted to change password in my profile, I successfully changed the password and it displayed the success message. But it stayed on the same page prompting for password change fields. This is a new issue and wasn't there before. Once the customer has changed the password, he should be routed to his profile page with successfully displaying the message

**Comment by Anum444** [comment]
**These issues are fixed and ready for testing:**

16,17,19,21,23,24,25

**Comment by ZarshaB** [comment]
**Re-opened**
21>> Please align it from bottom.
![image](https://user-images.githubusercontent.com/35685146/37329291-081dc48c-26bf-11e8-83b9-67ae3c070594.png)

22>> Please also make this message same as it is for change password from "My profile". Please change the highlighted text to "Good Job".
![image](https://user-images.githubusercontent.com/35685146/37329335-3e7fa400-26bf-11e8-9cd8-c1e6a06b9c90.png)

**Comment by ZarshaB** [comment]
**For Font:**
•For font, I have come across a tool which can tell the font used on website. Please find attached the font details used on dubizzle which is proxima-nova. It looks really good and neat especially so let's use it on our website. 

 - Proxima-nova having weight 700 looks the most attractive, neat and  readable. So please use same specs throughout the website. 
  - I have noticed that they haven't used bold anywhere on the website  (please you also double check on their website). They have just played with the font size. So we'll also do the same. All the heading will be  larger in size than the text body but not bold.
 - Please use uniform size and font style throughout the website and correspondence mediums (emails, error and information messages etc.)

**Comment by ZarshaB** [comment]
26>> Please adjust the empty space accordingly.
![image](https://user-images.githubusercontent.com/35685146/37388865-ea468b40-2783-11e8-936a-b9e859e3e892.png)

18>> It is appearing like this.
![image](https://user-images.githubusercontent.com/35685146/37388891-054bbd52-2784-11e8-97d5-d93aee60aab7.png)

**Comment by ZarshaB** [comment]
19>> Images font.
