### ISSUE TITLE
Feedback- Ticket

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#117]

**Comment by ZarshaB** [comment]
1>> When I made the purchase, I did not get the ticket copy in email.

**Comment by ZarshaB** [comment]
On purchase of any ad, user will get the two emails. 
One is of order summary. And the other is of ticket ( e-ticket).

**Comment by asifjans** [comment]
Fixed, Please take a look and give your feedback

**Comment by ZarshaB** [comment]
The order Id is different in ticket and order summary.
![image](https://user-images.githubusercontent.com/35685146/37700978-331d4d82-2d0f-11e8-8614-9d3c64a53290.png)
![image](https://user-images.githubusercontent.com/35685146/37701022-537ada22-2d0f-11e8-821c-188f1ebaca1e.png)

**Comment by ZarshaB** [comment]
Every time when I buy a new ticket for same ad it displays one more ticket than previous in email. For example when I bought ticket for the first time then it showed me one ticket. When I bought second time then it showed me 2 tickets. When I bought third time then  it showed me three tickets.
![image](https://user-images.githubusercontent.com/35685146/37898668-de8a9688-3102-11e8-9630-0408ba85234c.png)

**Comment by Anum444** [comment]
**These issues are fixed and ready for testing**

Every time when I buy a new ticket for same ad it displays one more ticket than previous in email. For example when I bought ticket for the first time then it showed me one ticket. When I bought second time then it showed me 2 tickets. When I bought third time then it showed me three tickets.

Can you please look into it? As The order Id is different in ticket and order summary.
