### ISSUE TITLE
Feedback - Change Password

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#120]
Please look at the attached file "Password Change Alignment." The error messages are appearing on field which is below the actual erroneous field and looks like that those messages are for field below. Please make them appear for the relevant field. Please give them proper space from the "Update" button at the bottom. It is overlapping. 
![image](https://user-images.githubusercontent.com/35685146/37585670-b6825d6a-2b7b-11e8-820d-79425a4e2648.png)

**Comment by sammiullah** [comment]
**this is fixed and ready for review!**

**Comment by Anum444** [comment]
Fixed
