### ISSUE TITLE
Feedback- My Account

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#121]
All headings of tables in sub sections of my account (e.g. My Favorites, My Ads etc) are clickable but have no functionality. Can you please check on that?

![image](https://user-images.githubusercontent.com/35685146/37585795-178eddf4-2b7c-11e8-868b-9e101d45f35d.png)

**Comment by sammiullah** [comment]
**this is fixed and ready for review**

**Comment by Anum444** [comment]
Fixed
