### ISSUE TITLE
Feedback - Login

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#123]
In ceratin instances, when I'm already login in one window and open a link that I have received in email in another window, then Im prompted for login. It shouldn't be hapeening. If Im logged in then I should remain logged in.

**Comment by ZarshaB** [comment]
In transfer and Refund templates it requires login.

**Comment by ZarshaB** [comment]
Still same issue as links are redirecting to live site.

**Comment by asifjans** [comment]
Please test now.

**Comment by asifjans** [comment]
we have mode some changes, try now please.

**Comment by ZarshaB** [comment]
Need to test for other templates. Waiting for Register issue to get resolved.
