### ISSUE TITLE
Feedback - Transfer Transfer

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#124]
When I transferred the ticket, it is sending me the link to download ticket. As informed earlier, the ticket should be attached in the email as PDF.

**Comment by asifjans** [comment]
Fixed,

**Comment by ZarshaB** [comment]
The ticket is appearing in two pages. 
![image](https://user-images.githubusercontent.com/35685146/37757452-eaa721ca-2dce-11e8-9c54-8e6dde21d238.png)

**Comment by ZarshaB** [comment]
Also Ticket No is not having same weight or boldness as others have.
![image](https://user-images.githubusercontent.com/35685146/37757744-d24653de-2dcf-11e8-96f2-a492a82e9d88.png)
