### ISSUE TITLE
Feedback - Purchase History

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#125]
Please refer to attached image "Purchase History". (1) e-Ticket link should be read as "e-Ticket". Please remove the word link. (2) Refer to 2nd hilighted portion. The word "transferred" should be in second row. It doesn’t look good in one line.

![image](https://user-images.githubusercontent.com/35685146/37585977-bc78eb5c-2b7c-11e8-8bfe-77a7d23fa772.png)

**Comment by sammiullah** [comment]
**this is fixed and ready for review!**

**Comment by Anum444** [comment]
Fixed
