### ISSUE TITLE
Feedback- Mobile Version

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#126]
I haven't gone through the mobile version in detail but from what I have observed, I can see that it hasn't been optimized properly. For example, the text of the headings in My account is nor readible. My Purchases and My ads is not optimized and have unorganized viewing and the list goes on. Please have a look at it and optimize the mobile version as per the requirements.

**Comment by ZarshaB** [comment]
Images are appearing blur and are not readable.
![image](https://user-images.githubusercontent.com/35685146/37704141-e39cb6de-2d19-11e8-90a2-f9ce78b11e67.png)

**Comment by ZarshaB** [comment]
2>> Image is not clickable. 
![image](https://user-images.githubusercontent.com/35685146/37704228-1ca5547c-2d1a-11e8-96d1-97b98cc5740e.png)

**Comment by ZarshaB** [comment]
4>> It is not optimize and not functional.
![image](https://user-images.githubusercontent.com/35685146/37704552-f487efa8-2d1a-11e8-8c90-84e6981826c1.png)

**Comment by ZarshaB** [comment]
5>> Text of button "View More" and "Learn More" is not centre aligned. 
![image](https://user-images.githubusercontent.com/35685146/37719738-804a3f10-2d47-11e8-941c-b1d8cfcf5d49.png)

**Comment by ZarshaB** [comment]
6>> Timer size should be reduced.
![image](https://user-images.githubusercontent.com/35685146/37719820-bdef3dc0-2d47-11e8-8db8-b8e0642c0757.png)

**Comment by ZarshaB** [comment]
7>>  Please also make loader at the centre of page.

**Comment by ZarshaB** [comment]
8>>  It is now taking me here after login.
![image](https://user-images.githubusercontent.com/35685146/37142080-d176f654-22d8-11e8-9d2d-a4c808af4d9a.png)

**Comment by ZarshaB** [comment]
9>> Buy Car button does not fill on click.

**Comment by ZarshaB** [comment]
10>> Spacing of  headings of all pages from above is not same.

**Comment by ZarshaB** [comment]
11>>  It is fixed for Register, Login pages. But Not For place your Ad general portion,Order summary page there is still issue that when I type then field disappears.

**Comment by ZarshaB** [comment]
12>> Timer in this view is covering the whole image.
![image](https://user-images.githubusercontent.com/35685146/37281128-ccbc11bc-2611-11e8-942a-a4f48226b11d.png)

**Comment by ZarshaB** [comment]
13>> Without Images this portion is appearing like this
![image](https://user-images.githubusercontent.com/35685146/36474985-2150d380-171b-11e8-8804-ceaa86cce53d.png)

**Comment by ZarshaB** [comment]
15>>  Space is not same.
![image](https://user-images.githubusercontent.com/35685146/37602527-57036ce8-2bae-11e8-9699-3b72c7c42e22.png)

**Comment by ZarshaB** [comment]
17>> Facebook button flickers. It disappears at first and then appears. Same is the case is with "Terms and Conditions option of "About Us" option.

**Comment by ZarshaB** [comment]
iPhone = https://github.com/asifjans/Inovedia/issues/113
iPad = https://github.com/asifjans/Inovedia/issues/51

**Comment by Anum444** [comment]
**These issues are fixed and ready for testing;**

1>> Images are appearing blur and are not readable. (FIXED)
3>> Alignment of headings on all pages is not same. (FIXED)
4>> It is not optimize and not functional. (FIXED)
5>> Text of button "View More" and "Learn More", Buyer and Seller is not centre aligned.
(FIXED)
6>> Timer size should be reduced. (FIXED)
7>> Please also make loader at the centre of page. (FIXED)
8>> It is now taking me here after login.
(FIXED)
9>> Buy Car button does not fill on click
 (FIXED)
10>> Spacing of headings of all pages from above is not same. (FIXED)
12>> Timer in this view is covering the whole image.  (FIXED)
11>> It is fixed for Register, Login pages. But Not For place your Ad general portion,Order summary page there is still issue that when I type then field disappears. (FIXED)
13>> Without Images this portion is appearing like this (FIXED)
15>> Space is not same. (FIXED)
16>> Extra spacing. (FIXED)
18>>It disappears at first and then appears. Same is the case is with "Terms and Conditions option of "About Us" option. (FIXED)

**Comment by ZarshaB** [comment]
Zohaib's iPhone Issues:

19>> Slider is appearing like this.
![image](https://user-images.githubusercontent.com/35685146/37823507-85eaa4cc-2eab-11e8-9f33-7ebf9f69cdb7.png)

20>> Sorting fileds are appearing like this.
![image](https://user-images.githubusercontent.com/35685146/37823539-989d5416-2eab-11e8-943e-83ec3ed2d240.png)

21>> Price is cutting.
![image](https://user-images.githubusercontent.com/35685146/37823572-af270902-2eab-11e8-8c78-d2b6ce738179.png)

22>> Menu does not hover on click.
![image](https://user-images.githubusercontent.com/35685146/37823599-c074e9fe-2eab-11e8-991d-04a1089aa9c9.png)

23>> Place your Ad button does not fill.
![image](https://user-images.githubusercontent.com/35685146/37823620-d0988020-2eab-11e8-8705-1adc2399bdf1.png)

24>> Tables are having extra space from below. 
![image](https://user-images.githubusercontent.com/35685146/37823632-deb77698-2eab-11e8-874c-5ec96161301a.png)

**Comment by ZarshaB** [comment]
25>> It is "Favorites" instead of "Favourites".

**Comment by ZarshaB** [comment]
26>> Hover is not appearing correct.
![image](https://user-images.githubusercontent.com/35685146/37823985-05bf47d8-2ead-11e8-97e9-d6af979f50d0.png)

**Comment by ZarshaB** [comment]
27>> Slider is going out of layout.
![image](https://user-images.githubusercontent.com/35685146/37824013-2145c8e2-2ead-11e8-8187-53682888ec4d.png)

**Comment by ZarshaB** [comment]
28>> Alignment issue of options and radio buttons.
![image](https://user-images.githubusercontent.com/35685146/37824043-389e77fa-2ead-11e8-9593-dbacbba97393.png)

**Comment by ZarshaB** [comment]
29>> Pages are scrolling.
![image](https://user-images.githubusercontent.com/35685146/37824095-5f04ba62-2ead-11e8-979a-f25644ee51be.png)

**Comment by ZarshaB** [comment]
30>> Alignment of images is not same.
![image](https://user-images.githubusercontent.com/35685146/37825482-cb84b12a-2eb1-11e8-9ed1-231ccbce757f.png)

**Comment by ZarshaB** [comment]
Not Fixed:
4
6>> Please reduce more space.

**Comment by ZarshaB** [comment]
31>> Cross icon for first image is appearing like this.
![image](https://user-images.githubusercontent.com/35685146/37826199-51664248-2eb4-11e8-83a4-e137e403956b.png)

**Comment by ZarshaB** [comment]
32>> This cross button is not working.
![image](https://user-images.githubusercontent.com/35685146/37826355-ea6e265e-2eb4-11e8-990a-d2b8b252197b.png)

33>> Buttons alignment is not correct.
![image](https://user-images.githubusercontent.com/35685146/37826371-01899a8a-2eb5-11e8-96fd-598875b644e2.png)

**Comment by Anum444** [comment]
**These issues are fixed and ready for testing**

4>> It is functional now but please also reduce it's size. 
29>> Pages are scrolling. (Fixed)
30>> Alignment of images is not same. 
31>> Cross icon for first image is appearing like this. 
32>> This cross button is not working. 
33>> Buttons alignment is not correct.

**Comment by ZarshaB** [comment]
1>> It is not redirecting to "Our Featured Cars" after login.

**Comment by ZarshaB** [comment]
2>> It is appearing like this when I click on transfer icon.
![image](https://user-images.githubusercontent.com/35685146/37901108-b6098ed8-3109-11e8-97df-3f389dc7490c.png)

**Comment by Anum444** [comment]
2>> It is appearing like this when I click on transfer icon. **(Fixed)**
1>> It is not redirecting to "Our Featured Cars" after login. **(Fixed)**

**Comment by ZarshaB** [comment]
It's cross icon is remaining.

**Comment by Anum444** [comment]
It's cross icon is remaining.  **(FIXED)**

**Comment by ZarshaB** [comment]
View Full screen button of How it works is not working in mobile.

**Comment by ZarshaB** [comment]
2>> Please reduce it's space a little more.
![image](https://user-images.githubusercontent.com/35685146/38016757-70f6dc48-3289-11e8-91c9-c863c0ba69a0.png)

**Comment by ZarshaB** [comment]
3>> There should be some space between pagination box and line.
![image](https://user-images.githubusercontent.com/35685146/38017598-ec46a78c-328b-11e8-919c-8b8350d4d093.png)

**Comment by asifjans** [comment]
(2) Fixed
(3) Fixed
