### ISSUE TITLE
Feedback - Templates

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#127]
Still there. All email like register, welcome, order summary email, password change etc have different layout and fonts. 

All emails have different spacing and formating. Some texts have single line spacing from heading and some have 3-4 line spacing.

When these emails are viewed on phone, then they have cutting issues for both gmail and hotmail. Screenshots attached. Please consider all scenarios where customer will get emails from us. Use both hotmail and gmail accounts and check the issues in viewing on cellphones(android and iOS both) and desktop.

**Comment by ZarshaB** [comment]
![image](https://user-images.githubusercontent.com/35685146/37586707-03da88c8-2b7f-11e8-9725-3fa5c3794781.png)

**Comment by ZarshaB** [comment]
**Hotmail Desktop 2**
![image](https://user-images.githubusercontent.com/35685146/37586723-11ab979e-2b7f-11e8-8876-9f85841246fa.png)

**Comment by ZarshaB** [comment]
**Hotmail Desktop 1**
![image](https://user-images.githubusercontent.com/35685146/37586779-37354744-2b7f-11e8-81dd-23b113bc66b8.png)

**Comment by ZarshaB** [comment]
**Hotmail Desktop 3**
![image](https://user-images.githubusercontent.com/35685146/37586707-03da88c8-2b7f-11e8-9725-3fa5c3794781.png)

**Comment by ZarshaB** [comment]
**iPhone 1**
![image](https://user-images.githubusercontent.com/35685146/37586833-5c99ae9e-2b7f-11e8-8df0-3137a682678e.png)

**Comment by ZarshaB** [comment]
**iPhone 2**

![image](https://user-images.githubusercontent.com/35685146/37586857-6d116758-2b7f-11e8-88a4-67e6566e88d4.png)

**Comment by ZarshaB** [comment]
**iPhone 3**

![image](https://user-images.githubusercontent.com/35685146/37586880-7e55dd96-2b7f-11e8-863c-5b2c575876be.png)

**Comment by ZarshaB** [comment]
**iPhone 4**

![image](https://user-images.githubusercontent.com/35685146/37586900-8cb59ea8-2b7f-11e8-80e5-260b10ec1dd3.png)

**Comment by asifjans** [comment]
![sign-in](https://user-images.githubusercontent.com/10880558/37704472-b56c2ae6-2d1a-11e8-91c4-3b1a3cafdfd7.png)

**Comment by ZarshaB** [comment]
**Refund**
Highlighted portion would be semi bold. Also one image is appearing correct and other is appearing broken. Alignment of button is also not correct.
![image](https://user-images.githubusercontent.com/35685146/37903808-bc3aab3a-3112-11e8-893b-53d48cdcdd70.png)

**Comment by ZarshaB** [comment]
**Buy Car**
Extra spacing. 
In Mobile alignment of Cheers is not correct.
![image](https://user-images.githubusercontent.com/35685146/37903852-eedc2de8-3112-11e8-8187-a661a0a3c7f7.png)

**Comment by ZarshaB** [comment]
**Order Summary**
Values will be semi bold.
![image](https://user-images.githubusercontent.com/35685146/37903916-305f8f9e-3113-11e8-86b9-f8c53a513db8.png)

**Comment by ZarshaB** [comment]
**Welcome**
Buttons alignment is not correct. Images are stretched.
![image](https://user-images.githubusercontent.com/35685146/37903942-4c66fefc-3113-11e8-9346-5f1b1caa6f38.png)

**Comment by ZarshaB** [comment]
**Transfer**
Broken Image.
![image](https://user-images.githubusercontent.com/35685146/37903963-61623d94-3113-11e8-99ba-608d46559248.png)

**Comment by ZarshaB** [comment]
In Transfer I'm getting number of attachments.

**Comment by ZarshaB** [comment]
Images of Welcome and Transfer are not appearing.

**Comment by ZarshaB** [comment]
**Transfer** 
![image](https://user-images.githubusercontent.com/35685146/38015104-39d28244-3284-11e8-8cce-7a21f6721703.png)

**Comment by ZarshaB** [comment]
**Welcome**
![image](https://user-images.githubusercontent.com/35685146/38015359-f607956c-3284-11e8-989f-b550d55a5a1e.png)

**Comment by ZarshaB** [comment]
Templates should also be fixed for gmail browser of Mobile.

**Comment by ZarshaB** [comment]
**Welcome**
![image](https://user-images.githubusercontent.com/35685146/38039082-e98c1ac4-32c5-11e8-91a4-3f18a8993613.png)
