### ISSUE TITLE
Feedback - Back button

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#130]
I have been observing back button malfunctioning. I'll explain one scenario. I viewed the car and scrolled down to read description and then I clicked back arrow in the bar. Instead of taking me back to the previous page, it took me to the top of that particlau car ad page and when i clicked back again, it only then took me to previous page. Also, I removed a car from my favorites and then started browsing cars. Whenever I opened up an ad, and clicked back, it routed me to previous screen and always displayed the messgae of "listing removed from favorites" everytime even though I had browsed to 6-7 cars after removing the car. Please rectify.

**Comment by asifjans** [comment]
Fixed, Please take a look and give your feedback.
