### ISSUE TITLE
Client Admin Feedback 25/03/18

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#132]

**Comment by ZarshaB** [comment]
**Account Management**
1>> Account Id is not available in export files.

**Comment by ZarshaB** [comment]
2>> In Refund Ticket please change the Car Id to reference number.

**Comment by ZarshaB** [comment]
Previous Client's Feedback
https://github.com/asifjans/Inovedia/issues/105

**Comment by ZarshaB** [comment]
Admin Dashboard = https://github.com/asifjans/Inovedia/issues/106

**Comment by ZarshaB** [comment]
**Reopened**
3>> If user has uploaded both "Front And Back" images and also "Documents" then at Admin side it should display everything. 
For now if I upload docs in Front and Back portion then from Admin side it displays error message.

**Comment by ZarshaB** [comment]
4>> There should be search option for selecting Winner.

**Comment by ZarshaB** [comment]
Reports = https://github.com/asifjans/Inovedia/issues/134

**Comment by shayanr262** [comment]
**Reopened**
3>> If user has uploaded both "Front And Back" images and also "Documents" then at Admin side it should display everything. **(Fixed)**
For now if I upload docs in Front and Back portion then from Admin side it displays error message.

**Comment by ZarshaB** [comment]
3>> When I upload document from "Front" and "Back" of user's account then on Admin's account, it displays me error message.
