### ISSUE TITLE
Pending Tasks

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#135]

**Comment by ZarshaB** [comment]
**UI - Functional Tasks**
94 >> Ticket's status should changed to "Pending" for "Deactivate" and "Sold" ads also in Purchase History.(Not Fixed)
106>> (Will test when I'll able to login with fb from demo.)
110>> It is displaying me reward points earned as 105. Whereas I have paid AED 94 and I have earned 94 reward points. (Not Fixed)

https://github.com/asifjans/Inovedia/issues/87

**Comment by ZarshaB** [comment]
**UI - Tasks**
26>> On clicking on "watch" icon, image flicks and then go to original size. (haider)
Video Link = https://www.screencast.com/t/ex4UxGJQ

https://github.com/asifjans/Inovedia/issues/91

**Comment by ZarshaB** [comment]
**Browser Compatibility
IE**
2>> On Contact Us this is appearing on scrolling down. (Not Fixed)
3>> Complete figure is not appearing. (Not Fixed)
7>> This is appearing on here and Order Summary page also for Billing address and also for Place your Ad. 

**Safari**
1,2,3,4,5,6,7,8

https://github.com/asifjans/Inovedia/issues/96

**Comment by ZarshaB** [comment]
**Validation Messages**
1,3,6
https://github.com/asifjans/Inovedia/issues/101

**Comment by ZarshaB** [comment]
**UI-Website**
2,5,6

https://github.com/asifjans/Inovedia/issues/109

**Comment by ZarshaB** [comment]
**Responsive Issues Android**
90,26
https://github.com/asifjans/Inovedia/issues/61

**Comment by ZarshaB** [comment]
**Blur Issues**
1
https://github.com/asifjans/Inovedia/issues/114

**Comment by Anum444** [comment]
Image size of View Cars and Car Detail page 
1
#149

**Comment by Anum444** [comment]
Responsive Issues 
2
#45

**Comment by Anum444** [comment]
Feedback App Web Issues - 03/04/18 
8
#148

**Comment by ZarshaB** [comment]
**Feedback- App Web Issues:**

https://github.com/asifjans/Inovedia/issues/148

**Comment by ZarshaB** [comment]
**Admin Portal- UI**
https://github.com/asifjans/Inovedia/issues/107

**Comment by ZarshaB** [comment]
**Admin Portal - Functional**
https://github.com/asifjans/Inovedia/issues/93

**Comment by ZarshaB** [comment]
**Client Admin Feedback**
2>> There should be option of upload picture for winner.
https://github.com/asifjans/Inovedia/issues/95

**Comment by ZarshaB** [comment]
Spacing Issue
https://github.com/asifjans/Inovedia/issues/144

**Comment by Anum444** [comment]
1. UI - Functional Tasks
2. UI - Tasks
3. Browser Compatibility
4. UI-Website (Sami)
5. Blur Issues
6. Image size of View Cars and Car Detail page
7. Responsive Issues
8. Feedback App Web Issues - 03/04/18
9. Admin Portal- UI
10. Admin Portal - Functional
11. Client Admin Feedback
12. Spacing Issue

**Comment by Anum444** [comment]
Web Site Issues:

Spacing Issue  **(Close)**
Responsive Issues    **(Close)**
Image size of View Cars and Car Detail page
Blur Issues
UI-Website **(Close)**
Browser Compatibility
UI - Tasks
UI - Functional Tasks

**Comment by ZarshaB** [comment]
**UI - Tasks**
26>> **(haider)** On clicking on "watch" icon, image flicks and then go to original size. 
Video Link = https://www.screencast.com/t/ex4UxGJQ

https://github.com/asifjans/Inovedia/issues/91

**Comment by ZarshaB** [comment]
**Side Arrows**

https://github.com/asifjans/Inovedia/issues/161

**Comment by ZarshaB** [comment]
**Android Application Issues**
1>> There should be fb button.
https://github.com/asifjans/Inovedia/issues/115

**Comment by ZarshaB** [comment]
**(Zahid)**
**Client Admin Feedback**
2>> There should be option of upload picture for winner.
https://github.com/asifjans/Inovedia/issues/95

**Comment by ZarshaB** [comment]
**(Zahid)**
**Admin Portal - Functional**
18,20,29.32.33,34,36,38,40,41
https://github.com/asifjans/Inovedia/issues/93

**Comment by ZarshaB** [comment]
**Zahid**
**Admin Portal- UI**
1,2,3,6,15,16,17,
https://github.com/asifjans/Inovedia/issues/107

**Comment by ZarshaB** [comment]
**Feedback App Web Issues - 03/04/18** 
1,2,3,7,13,16,18
#148

**Comment by ZarshaB** [comment]
**Haider**
**Image size of View Cars and Car Detail page** 
1,2,3,4
#149

**Comment by ZarshaB** [comment]
**Blur Issues**
1
https://github.com/asifjans/Inovedia/issues/114

**Comment by ZarshaB** [comment]
**Browser Compatibility
IE**
2>> **(Anum)** On Contact Us this is appearing on scrolling down. 
7>> This is appearing on here and Order Summary page also for Billing address and also for Place your Ad.  
13>> option is going on next line.  
![image](https://user-images.githubusercontent.com/35685146/38500576-45c52b0c-3c24-11e8-92c6-94e8fbeae2cc.png)

**(Anum)**
**Safari**
1>> Reopened
2,6,8,10,

https://github.com/asifjans/Inovedia/issues/96

**Comment by Anum444** [comment]
**Pending issues**

Browser Compatibility
Blur Issues
Image size of View Cars and Car Detail page
UI - Tasks

**New issues**
Checkbox Alignment
Side Arrows

**Comment by ZarshaB** [comment]
**Buy ticket button from Car Detail redirecting to Home page**

https://github.com/asifjans/Inovedia/issues/164

**Comment by ZarshaB** [comment]
**Feedback App Functional Issues - 03/04/18**
https://github.com/asifjans/Inovedia/issues/163

**Comment by ZarshaB** [comment]
**Feedback - Reward Points**
https://github.com/asifjans/Inovedia/issues/165

**Comment by ZarshaB** [comment]
**Feedback - Account Management**

https://github.com/asifjans/Inovedia/issues/166

**Comment by ZarshaB** [comment]
**On deleting account it redirects to error page**
https://github.com/asifjans/Inovedia/issues/167

**Comment by ZarshaB** [comment]
**Search bar flickers when I select any value.**
https://github.com/asifjans/Inovedia/issues/168

**Comment by ZarshaB** [comment]
**Search bar flickers when I select any value.**
https://github.com/asifjans/Inovedia/issues/168

**Comment by ZarshaB** [comment]
**Speed of website is very slow.**
https://github.com/asifjans/Inovedia/issues/169

**Comment by ZarshaB** [comment]
**Feedback App Web Issues - 03/04/18**
1,2
https://github.com/asifjans/Inovedia/issues/148

**Comment by ZarshaB** [comment]
**Friends and Family Testing Feedback of Client - 13/04/18**
1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20

https://github.com/asifjans/Inovedia/issues/170

**Comment by ZarshaB** [comment]
**No Result Found placement and button on Desktop**
https://github.com/asifjans/Inovedia/issues/172

**Comment by ZarshaB** [comment]
**Validation message** 
https://github.com/asifjans/Inovedia/issues/173

**Comment by ZarshaB** [comment]
**Alignment of Ticket**
https://github.com/asifjans/Inovedia/issues/174

**Comment by ZarshaB** [comment]
**Scroll bars are different.**
https://github.com/asifjans/Inovedia/issues/176

**Comment by ZarshaB** [comment]
**Back button.**
https://github.com/asifjans/Inovedia/issues/175

**Comment by ZarshaB** [comment]
**Mobile Version - Overlapping due to scroll bar addition.**
https://github.com/asifjans/Inovedia/issues/177

**Comment by ZarshaB** [comment]
**Mobile - Login - Alignment of Text**
https://github.com/asifjans/Inovedia/issues/178

**Comment by ZarshaB** [comment]
**Change card Icons of Footer** 
https://github.com/asifjans/Inovedia/issues/179

**Comment by ZarshaB** [comment]
**Invalid Emirates Id**
https://github.com/asifjans/Inovedia/issues/180

**Comment by ZarshaB** [comment]
**Haider**
**Image size of View Cars and Car Detail page** 
2,6
#149

**Comment by ZarshaB** [comment]
**Browser Compatibility
IE**  

7>> This is appearing on here and Order Summary page also for Billing address and also for Place your Ad.   **Not FIXED**

https://github.com/asifjans/Inovedia/issues/96

**Comment by ZarshaB** [comment]
**On deleting account it redirects to error page**
https://github.com/asifjans/Inovedia/issues/167

**Comment by ZarshaB** [comment]
**Search bar flickers when I select any value.**
https://github.com/asifjans/Inovedia/issues/168

**Comment by ZarshaB** [comment]
**Feedback App Web Issues - 03/04/18**
2
https://github.com/asifjans/Inovedia/issues/148

**Comment by ZarshaB** [comment]
**After login it should redirect me to correct pages.**
https://github.com/asifjans/Inovedia/issues/171

**Comment by ZarshaB** [comment]
**Validation message** 
2
https://github.com/asifjans/Inovedia/issues/173
