### ISSUE TITLE
Feedback - Templates

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#139]

**Comment by ZarshaB** [comment]
Winner email, order confirmation and Ticket Transfer email had all text in bold. Only headings (e.g. Hi "name" and You've won and headings of cloumns etc)  should be in bold whereas all other text should be in normal font. Please rectify.


I have observed other issues in emails which are still there but for the time being lets close it We'll resolve them in later stage. For the time being only rectify the winner, order confirmation and ticket transfer email only.

**Comment by sammiullah** [comment]
**changes are done** 
test them!
