### ISSUE TITLE
Feedback App Issues - 03/04/18

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#147]

**Comment by ZarshaB** [comment]
1>> The arrows in App icon doesn't look aligned and seem to be towards the top. They should be in middle

**Comment by ZarshaB** [comment]
2>> Need suggestion. How would it look when Top  arrow in the icon is made green??

**Comment by ZarshaB** [comment]
3>> How it Works page
Shouldn't the video be playing automatically when customer clicks the HIW button. Plus there is no thumbnail.

**Comment by ZarshaB** [comment]
4>> Login Message:
Please refer to attach picture. The error message is not properly aligned. It should be read as follows and should be center aligned.
Ooooooops!!!
Please Login/Register to continue.

![image](https://user-images.githubusercontent.com/35685146/38237089-96d84e64-373f-11e8-8ab9-528c4291b553.png)

**Comment by ZarshaB** [comment]
5>> Refer to image. When I clicked search button, there was no option to cancel it. Add a corss mark to cancel it.

**Fixed**

**Comment by ZarshaB** [comment]
6>> Tips on Buying Tickets
Since we have removed it from main website, so please remove it from here as well.

**Comment by ZarshaB** [comment]
7>> Introduce Back button wherever possible. There are lots of places where I can not find back button and have to choose another option to navigate.

**Comment by ZarshaB** [comment]
8>> **Register**
No Middle Name option has provided. It is there in the website

**Comment by ZarshaB** [comment]
9>> **Register** 
Mobile Number is taking all alphabets and are unlimited.

**Comment by ZarshaB** [comment]
10>> **Register**
No Reenter Password option

**Comment by ZarshaB** [comment]
11>> **Register**
After entering all fields, there is no provision for "Send me amazing deals" and "By clicking on Register, I agree"

**Comment by ZarshaB** [comment]
12>> In certain instances e.g. While posting the ad, when I have entered the text, I don’t find any option to remove the keyboard. It is just there. Please rectify it and once I have entered the text, I should have option of cancelling the keyboard.

**Comment by ZarshaB** [comment]
13>> Where is My Profile Section?

**Comment by ZarshaB** [comment]
14>> Where is Privacy Policy?

**Comment by ZarshaB** [comment]
15>> Whenever I go back with back arrow, it should give the refreshed status or information. It is happening everywhere that old info being displayed. For example, I deleted ad. After confirmation message, when I clicked back arrow, It went back to My Ads page with car status as active.

**Comment by ZarshaB** [comment]
16>> Logout/ Forgot Password / Register
Please refer to attached picture. Realign the dialogue box. The Heading should be below the cross arrow. The remaining text should be centre aligned. Everything should be properly spaced from each other. Same issue with forgot password Enter email and confirmation message and Thank You message for registering

![image](https://user-images.githubusercontent.com/35685146/38237863-c4089f90-3741-11e8-9d25-6ae922076393.png)
![image](https://user-images.githubusercontent.com/35685146/38237878-cc62a4a6-3741-11e8-8495-16094c1bc127.png)
![image](https://user-images.githubusercontent.com/35685146/38237926-da1006c0-3741-11e8-8705-ceb035ea8541.png)

**Comment by ZarshaB** [comment]
17>> All the dialogue boxes and information messages are improperly formatted. Should be centre aligned and proper format should be done as mentioned in point 16.

**Comment by ZarshaB** [comment]
18>> Please add the message for Register "Now we're Talking…." in register section

**Comment by ZarshaB** [comment]
19>> All email links like confirmation of email, change password link, links in marketing email or Car Ads that we send in welcome and other emails should open in app.

**Comment by ZarshaB** [comment]
20>> I did not see any Ad sharing functionality over whats app, Facebook, email etc

**Comment by zohaibqadir** [comment]
All Issues have been fixed 
Please test the latest APK

**Comment by ZarshaB** [comment]
Re-opened
9>> There should be limit for mobile number field.
3>> There should be thumb nail of video.

Register page two lines have small font. I need to test that for other mobiles. 
Back button functionality>> Sir said that he'll look into it.

**Comment by ZarshaB** [comment]
Re-opened:
3>> It is okay. But for How it works from inside it should also be same as it is for other How it works screen i.e. cover the whole screen.
![image](https://user-images.githubusercontent.com/35685146/38415015-9aba590c-39a9-11e8-89ad-8a6e7df20a65.png)


>> Please also increase the font size for those two lines of Register page/

**Comment by ZarshaB** [comment]
20>> Please also increase the font size for those two lines of Register page.

**Comment by ZarshaB** [comment]
21>> Arrow is not working.
![image](https://user-images.githubusercontent.com/35685146/38415260-691780b8-39aa-11e8-9bad-145f451b7697.png)

**Comment by zohaibqadir** [comment]
All issues have been fixed, please test

**Comment by ZarshaB** [comment]
Please make it round.
![image](https://user-images.githubusercontent.com/35685146/38424485-a4159e82-39ca-11e8-82fa-fb70a75b7004.png)

**Comment by ZarshaB** [comment]
Back button functionality will be tested by sir.
