### ISSUE TITLE
Image size of View Cars and Car Detail page 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#149]

**Comment by ZarshaB** [comment]
It's frame will be of same size and in centre but image size will vary according to size. 
![image](https://user-images.githubusercontent.com/35685146/38244135-165a553e-3753-11e8-9387-18c816273bad.png)

**Comment by ZarshaB** [comment]
It is okay for large image, but when image gets small then it does not look good. So please make a border across it.

**Comment by ZarshaB** [comment]
In View Cars, three cars in a row were fine. Now it's look very small in size. Also their size was okay in View Cars. 
![image](https://user-images.githubusercontent.com/35685146/38373736-55f908f2-390b-11e8-915d-5831d7a75e16.png)

**Comment by ZarshaB** [comment]
In Car Detail page, when I upload large size image then it make the size of small image equal to that and making that small image blur. And if I upload large image with small image then it makes large image size small. It should not change the size of image to that much small. 
![image](https://user-images.githubusercontent.com/35685146/38373895-c29aa966-390b-11e8-9b8d-3e1070c8bac8.png)
![image](https://user-images.githubusercontent.com/35685146/38373904-c91af700-390b-11e8-93b8-f2b8abda4ba3.png)
![image](https://user-images.githubusercontent.com/35685146/38373926-da980658-390b-11e8-9935-810d1d50a433.png)
![image](https://user-images.githubusercontent.com/35685146/38373945-e665306e-390b-11e8-8b37-39f7e251ade1.png)

**Comment by ZarshaB** [comment]
2>> There is so much extra space. Can you please align quantity and heart in between Time left and Ticket Sold. And also move Time left and Ticket sold a little above.
![image](https://user-images.githubusercontent.com/35685146/38422689-208b8f18-39c5-11e8-88b6-6b11e7abe080.png)

**Comment by ZarshaB** [comment]
3>> Images are appearing under the frame in pop up.
![image](https://user-images.githubusercontent.com/35685146/38425835-666a745a-39ce-11e8-95cc-6692c9fbd5e5.png)

**Comment by ZarshaB** [comment]
4>> List view option is not working.
![image](https://user-images.githubusercontent.com/35685146/38500221-39a4c3c4-3c23-11e8-8ab7-2162f0243d05.png)

**Comment by ZarshaB** [comment]
5>> On clicking on "watch" icon, image flicks and then go to original size.  
Video Link = https://www.screencast.com/t/ex4UxGJQ

**Comment by asifjans** [comment]
**(RFR)** In Car Detail page, when I upload large size image then it makes the size of small image equal to that and making that small image blur. And if I upload large image with small image then it makes large image size small. It should not change the size of image to that much small.

3>> **(RFR)**  Images are appearing under the frame in pop up.

5>> **(RFR)**   On clicking on "watch" icon, image flicks and then go to original size.

**Comment by ZarshaB** [comment]
6>> **Mobile Version**
At first on clicking on watch icon it appears like this and after 2-3 times clicks it appears correct. And also it's cross icon changes it's size.
![image](https://user-images.githubusercontent.com/35685146/38726777-98f2ebe0-3f24-11e8-9faa-9f261a37f836.png)

**Comment by ZarshaB** [comment]
2>> **(sami)** There is so much extra space. Can you please  move Time left and Ticket sold above in order to remove extra space.
![image](https://user-images.githubusercontent.com/35685146/38422689-208b8f18-39c5-11e8-88b6-6b11e7abe080.png)

**Comment by ZarshaB** [comment]
6>> **Mobile Version and also in desktop**
At first on clicking on watch icon it appears like this and after 2-3 times clicks it appears correct. And also it's cross icon changes it's size.
![image](https://user-images.githubusercontent.com/35685146/38726777-98f2ebe0-3f24-11e8-9faa-9f261a37f836.png)

**Comment by asifjans** [comment]
2>> **(RFR)** There is so much extra space. Can you please  move Time left and Ticket sold above in order to remove extra space.

**Comment by asifjans** [comment]
6>> **(RFR)**  **Mobile Version and also in desktop**
At first on clicking on watch icon it appears like this and after 2-3 times clicks it appears correct. And also it's cross icon changes it's size.

**Comment by asifjans** [comment]
2) Fixed
6) Fixed

**Comment by ZarshaB** [comment]
**Not Fixed**
6>> **(Haider)**  **Mobile Version and also in desktop**
At first on clicking on watch icon it appears like this and after 2-3 times clicks it appears correct. And also it's cross icon changes it's size.
![image](https://user-images.githubusercontent.com/35685146/38871004-f43ac27e-4268-11e8-8769-c852cac08e23.png)

**Comment by ZarshaB** [comment]
6>> This issue is resolved. But icon still changes it's shape from smaller to bigger icon.
