### ISSUE TITLE
Centre align 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#156]

**Comment by ZarshaB** [comment]
Please make the text centre align.
![image](https://user-images.githubusercontent.com/35685146/38360450-a84a8004-38e3-11e8-8655-e16fce3ce230.png)

**Comment by sammiullah** [comment]
Please make the text centre align.
![image](https://user-images.githubusercontent.com/35685146/38360450-a84a8004-38e3-11e8-8655-e16fce3ce230.png)

**Comment by ZarshaB** [comment]
It is not fixed in latest release.
