### ISSUE TITLE
Buy ticket button from Car Detail redirecting to Home page

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#164]

**Comment by ZarshaB** [comment]
When I click on Buy Ticket button of Car Detail page it redirects me to Our Featured Cars section of Home page.

**Comment by Anum444** [comment]
![image](https://user-images.githubusercontent.com/35521943/38566053-3bd708c6-3cfc-11e8-8989-039b47e6d194.png)

Working Fine in Demo.

**Comment by ZarshaB** [comment]
Please test it for Buy Ticket button not for Buy Car button on demo.

**Comment by Anum444** [comment]
When I click on Buy Ticket button of Car Detail page it redirects me to Our Featured Cars section of Home page.   **(FIXED)**
