### ISSUE TITLE
On deleting account it redirects to error page

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#167]

**Comment by ZarshaB** [comment]
When I'm deleting any account from user's side then it redirects to error page and also account got deleted. 
![image](https://user-images.githubusercontent.com/35685146/38671054-d25268f0-3e63-11e8-8dc1-42b524b919ad.png)

**Comment by ZarshaB** [comment]
Also the account that is already created, when I try to delete them it shows message of active tickets. When I click on title of those tickets from "Purchase History" page then it shows me that Ad with "Sold Out" status. Also when I search that ad from Admin Panel then that Ad does not exist. So Not able to delete previously created account.

**Comment by ZarshaB** [comment]
Not able to test it because of not able to register account.

**Comment by asifjans** [comment]
Fixed
