### ISSUE TITLE
Search bar flickers when I select any value. 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#168]

**Comment by ZarshaB** [comment]
Search bar flickers when I select any value. 
![image](https://user-images.githubusercontent.com/35685146/38686084-f02d4e20-3e8c-11e8-8a16-991b5bf8c0c9.png)

**Comment by Anum444** [comment]
Search bar flickers when I select any value.  **RFR**

**Comment by ZarshaB** [comment]
**Not Fixed**
![image](https://user-images.githubusercontent.com/35685146/38816991-cc3c1cc2-41b0-11e8-802e-cddca8b08e42.png)

**Comment by ZarshaB** [comment]
2>> It does not allow me to select last values from drop down.
![image](https://user-images.githubusercontent.com/35685146/38861376-dd3278dc-424b-11e8-896f-0069dba727c1.png)

**Comment by Anum444** [comment]
2>> It does not allow me to select last values from drop down.   **RFR**

**Comment by Anum444** [comment]
2>> It does not allow me to select last values from drop down.   **RFR**
1>> **RFR**

**Comment by ZarshaB** [comment]
1,2 >> Not Fixed
