### ISSUE TITLE
Friends and Family Testing Feedback of Client - 13/04/18

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#170]

**Comment by ZarshaB** [comment]
1>> When customer registers, there is repetition of the message "Thank you for registering with us". Please keep it only in the heading and remove it from the text below. 

Thank you for registering with us!!!
Your email has been verified. Let's continue to login.

**Comment by ZarshaB** [comment]
2>> When customer clicks on check out, there is a pop-up box saying "Are you sure you want to check out?" and the button is OK. Replace the OK button with Yes.

**Comment by ZarshaB** [comment]
3>> **Mobile Registration**
Passport number should be alphanumeric

**Comment by ZarshaB** [comment]
4>> Based on customer feedback, the field "City" in Place Your Ad seems wrongly placed, it is coming in between vehicle specs / details. Please move it to the start in all site versions and apps.

**Comment by ZarshaB** [comment]
5>> Based on customer feedback, making the passport and emirates ID mandatory is hassle and everybody is facing problems while registring as nobody is having passport with them at that time. So please make it optional field in all site versions and apps. Instead in Emirates ID coulmn where "Emirates Id" is written in grey, please replace that with following text:-

Recommended For UAE Residents

In Passport coulmn where "Passport" is written in grey, please replace that with following text:-

Recommended For Non-Residents

**Comment by ZarshaB** [comment]
6>> **Mobile Version Home Page**
The featured car lists for the cars lets you scroll the background and not functioning properly when scrolling.

**Comment by ZarshaB** [comment]
7>> **Desktop Version Home page**
When customer scroll down from banner to featured cars, 2-3 cars in the start automatically move towards left and list begins with next few cars. Please add timer where customer could get enough time to have a look at the cars list from the start and should also have option to manually move right or left in featured cars list.

**Comment by ZarshaB** [comment]
8>> When customer purchases more than 1 ticket then he has to refresh to update the totall bill amount at bottom. Please make it automatic that whenever customer enters any number of ticket, the bill amount at the bottom should be refreshed automatically.

**Comment by ZarshaB** [comment]
9>>**Registration  / Admin Dashboard**
 By mistake, one customer entered wrong email for registration. But in admin portal, it was being reflected as active customer. Please rectify it. Customer who applied for registartion should appear in the list but not as an active customer until he verifies the link recieved in email.

**Comment by ZarshaB** [comment]
10>> I purchased multiple tickets for four different cars at the same time in one checkout. Although it took time but the checkout was successful and all details are available in My Purchase section. However, I did not get a single email regarding order summary and ticket purchases. It is a BIG issue

**Comment by ZarshaB** [comment]
11>> Some featured cars have bigger images while others are small. Due to which there is no uniformity on homepage in Featured car list. Please make all images of same size.

**Comment by ZarshaB** [comment]
12>> **Login**
Please add Remember Me button.

**Comment by ZarshaB** [comment]
13>> F**AQs**
The questions are not in line. For example in general, second question and its answer are not related to each other. Please go through already provided document and make them accordingly. Please note that there were few changes in originally provided document, so you have to upload those update answers. This section is already reviewed and shouldn't be happening to already reviewed sections.

**Comment by ZarshaB** [comment]
14>> **Place your Ad**
In Fuel type, there is one option Gasoline. Please make it Gasoline/Petrol all across the versions

**Comment by ZarshaB** [comment]
15>> **Place your Ad**
When customer posts ad and he gets message that  "Hi Usama, 
Thanks for submitting the ad. Our car gurus will now be doing free evaluation of your ride and will get back to you within 12 hours. And since you have already decided to sell your car, then why not try your luck here for your next ride. Happy Shopping!!!". This message should be in pop-up form. None of the customer was able to locate the message and they were clueless that what will happen next.

**Comment by ZarshaB** [comment]
16>> One account a_almadhloum@hotmail.com was created without any details of Passport, emirates id, contact number etc. How is it possible?

**Comment by ZarshaB** [comment]
17>> There are some major issues in reward point system. 
(1) I entered 2000 reward points to redeem, It showed a total of 60 AED discount whreas it should be 40 AED. Then I changed and entered 1500 rewards points for redemption. Instead of showing new discount, it added into previous amount of AED 60 and the reward points deducted were 3500. This kept on happening till I made the final transaction. This should not be happening. Once I enter a number of reward points and then i reenter them, it should be updated immediatily.

2) Secondly when customer enters rewards points which exceed the price of the ticket, then instead of showing a negative balance in total and then going towards the checkout, customer should get following message immediately once when enters rewards points that exceed the price of ticket. 

Oooopss!!!

We thought so too but due to some mumbo-jumbo, the value of Rewards Points redeemed cannot exceed the price of ticket.

**Comment by ZarshaB** [comment]
18>> In My Ads, there is no scroll bar on the right.

**Comment by ZarshaB** [comment]
19>> In Buyer FAQs, the answer to second last question "Can I still enter the draw….." should be replaced as follows:-

Yes, you can. You have to provide a valid UAE Mobile Number while registering and have to be physically present in UAE to claim the prize in case you win the draw.

**Comment by ZarshaB** [comment]
20>> **Place your Ad**
In Ad title, where "Ad title" is written in grey in input field, please replace it with following text:-

e.g. Audi A7 For Sale

**Comment by asifjans** [comment]
18>> **(RFR)** In My Ads, there is no scroll bar on the right.
Comment: There should be scroll bar on this side on all other pages too. And also Sir said there should be pagination too.

**Comment by ZarshaB** [comment]
**Reopened** 
5>> Please also update it's place holders on My Profile page.
![image](https://user-images.githubusercontent.com/35685146/38741536-8eb3c2f6-3f53-11e8-8bd8-c00406933fca.png)

**Comment by ZarshaB** [comment]
**Not Fixed**
9>> **Zahid** **Registration  / Admin Dashboard**
 By mistake, one customer entered wrong email for registration. But in admin portal, it was being reflected as active customer. Please rectify it. Customer who applied for registartion should appear in the list but not as an active customer until he verifies the link recieved in email.


if  "IsEmailVerificaiton" false then show status"Pending"

**Comment by ZarshaB** [comment]
**Not Fixed**
12>> **anum** **Login**
Please add Remember Me button.

(Functionality is not being added.)

**Comment by ZarshaB** [comment]
**Not Fixed**
12>> **anum** **Login**
Please add Remember Me button.

(It is saving email and checkbox is checked but not saving password. )

**Comment by ZarshaB** [comment]
okay
