### ISSUE TITLE
Validation message and Issues

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#173]

**Comment by ZarshaB** [comment]
Without clicking on anything when I come to this page, DOB field displays this error message.
![image](https://user-images.githubusercontent.com/35685146/38741291-10771ae6-3f53-11e8-99a4-56c96b66b421.png)

**Comment by ZarshaB** [comment]
2>> Please move these messages above close to the fields.
![image](https://user-images.githubusercontent.com/35685146/38742574-673f52d2-3f56-11e8-82a5-5d203cf07276.png)

**Comment by ZarshaB** [comment]
3>> When I enter this value it redirected me to error page.
![image](https://user-images.githubusercontent.com/35685146/38742785-e17d48ba-3f56-11e8-911e-05b097a4ae3c.png)
![image](https://user-images.githubusercontent.com/35685146/38742837-01117b6a-3f57-11e8-9847-08c77a5eec47.png)

**Comment by Anum444** [comment]
2>> **RFR** Please move these messages above close to the fields.
3>> **RFR**  When I enter this value it redirected me to error page.

**Comment by ZarshaB** [comment]
2>> Fixed for other pages but not for this page.
![image](https://user-images.githubusercontent.com/35685146/38816652-0148b1a6-41b0-11e8-892f-717f69886c07.png)

**Comment by Anum444** [comment]
2>> Fixed for other pages but not for this page.  **RFR**
