### ISSUE TITLE
Scroll bars are different. (Chrome) 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#176]

**Comment by ZarshaB** [comment]
My Favorites page is scrollable but there is not scrol bar.
![image](https://user-images.githubusercontent.com/35685146/38800133-ecb6ad04-417f-11e8-9c6b-45db4dcace0a.png)

**Comment by ZarshaB** [comment]
My Favorites page is scroll able but no scroll bar is there. 
![image](https://user-images.githubusercontent.com/35685146/38811273-9158cba4-41a2-11e8-8a2a-090c77ecbadf.png)

**Comment by Anum444** [comment]
Purchase History page has different scroll bar than other pages. (Chrome)  **Fixed**
