### ISSUE TITLE
Mobile Version - Overlapping due to scroll bar addition.

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#177]

**Comment by ZarshaB** [comment]
![image](https://user-images.githubusercontent.com/35685146/38804980-b09696f0-418d-11e8-8ee1-09fda52d0224.png)
![image](https://user-images.githubusercontent.com/35685146/38804997-bb4c815e-418d-11e8-89de-0c9dd15c0d58.png)
![image](https://user-images.githubusercontent.com/35685146/38805006-c55657d8-418d-11e8-81be-2ee358b8f9b8.png)
![image](https://user-images.githubusercontent.com/35685146/38805018-ce005a1e-418d-11e8-9848-4d1512a8f339.png)

**Comment by asifjans** [comment]
**(RFR)** Account pages are overlapping.
