### ISSUE TITLE
Mobile - Alignment of Text and extra space

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#178]

**Comment by ZarshaB** [comment]
Text Alignment is not same. And also please check if the font size is equal for both.
![image](https://user-images.githubusercontent.com/35685146/38805134-330162d2-418e-11e8-9344-ce238b2281af.png)

**Comment by ZarshaB** [comment]
2>> There is extra space below the footer.
![image](https://user-images.githubusercontent.com/35685146/38805391-13ac52d8-418f-11e8-931e-81300d868ca1.png)

**Comment by Anum444** [comment]
**Fixed**
1>> Text Alignment is not same. And also please check if the font size is equal for both.
