### ISSUE TITLE
Change card Icons of Footer

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#179]

**Comment by ZarshaB** [comment]
Please change card icons to this. 
![image](https://user-images.githubusercontent.com/35685146/38815068-8005c820-41ac-11e8-84fa-f482fb68e061.png)

**Comment by asifjans** [comment]
@ZarshaB  in Mobile Website or in Both?

**Comment by ZarshaB** [comment]
In both s Footer will be same.

**Comment by Anum444** [comment]
Please change card icons to this.   **RFR**

**Comment by ZarshaB** [comment]
Cards are changed but text is not visible.
![image](https://user-images.githubusercontent.com/35685146/38856496-1045d522-4240-11e8-93cb-f32d56aefad2.png)

**Comment by Anum444** [comment]
Cards are changed but text is not visible.  **RFR**
