### ISSUE TITLE
Invalid Emirates Id

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#180]

**Comment by ZarshaB** [comment]
Shouldn't it display error if invalid emirates id is entered?
![image](https://user-images.githubusercontent.com/35685146/38815421-5602b636-41ad-11e8-82b3-5a98d5ee6833.png)

**Comment by Anum444** [comment]
Shouldn't it display error if invalid emirates id is entered?  **RFR**

**Comment by sammiullah** [comment]
**FIXED**  Shouldn't it display error if invalid emirates id is entered?
![image](https://user-images.githubusercontent.com/35685146/38815421-5602b636-41ad-11e8-82b3-5a98d5ee6833.png)
![image](https://user-images.githubusercontent.com/35685146/38815474-73acb592-41ad-11e8-9b90-43d78eb00291.png)
****

**Comment by ZarshaB** [comment]
If I enter invalid emirates id then on clicking on Save button of My Profile page, it displays error message but also saves the information and displays this in ticket.

**Comment by sammiullah** [comment]
**FIXED**  Shouldn't it display error if invalid emirates id is entered?
![image](https://user-images.githubusercontent.com/35685146/38815421-5602b636-41ad-11e8-82b3-5a98d5ee6833.png)
![image](https://user-images.githubusercontent.com/35685146/38815474-73acb592-41ad-11e8-9b90-43d78eb00291.png)
****

**Comment by ZarshaB** [comment]
I'll test after I'll able to register.

**Comment by ZarshaB** [comment]
It is fixed for Register page but not for My Profile page. If I remove the filed and then click on Save button then it still displays me error message. 
![image](https://user-images.githubusercontent.com/35685146/38881199-f7104b28-4280-11e8-82f2-77a48377bbd2.png)
