### ISSUE TITLE
Reward Points message.

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#195]

**Comment by ZarshaB** [comment]
If Reward Points redeemed are greater than existing Reward Points than message should be:
Oooopss!!!
We thought so too but due to some mumbo-jumbo, the value of Reward Points redeemed is greater than existing Reward Points in your Account. 

Instead of this:
![image](https://user-images.githubusercontent.com/35685146/38928014-f3ee5ad4-4320-11e8-8f5c-f27b5bf2acd4.png)
![image](https://user-images.githubusercontent.com/35685146/38928015-f416c870-4320-11e8-9138-167ee99271ec.png)

**Comment by asifjans** [comment]
**(RFR)** If Reward Points redeemed are greater than existing Reward Points than message should be:
Oooopss!!!
We thought so too but due to some mumbo-jumbo, the value of Reward Points redeemed is greater than existing Reward Points in your Account.
