### ISSUE TITLE
Mobile 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#200]

**Comment by ZarshaB** [comment]
1>> Please reduce a little space from Car detail page.

**Comment by ZarshaB** [comment]
2>> Please update Facebook, insta and youtube icons in footer.

**Comment by Anum444** [comment]
2>> Please update Facebook, insta and youtube icons in footer.  **RFR**
![image](https://user-images.githubusercontent.com/35685146/38982965-aa4f7702-43dc-11e8-8970-9446f2040df4.png)
