### ISSUE TITLE
Results page of App

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#201]

**Comment by ZarshaB** [comment]
![image](https://user-images.githubusercontent.com/35685146/38982521-7d572980-43db-11e8-99bd-d08a7acea8b4.png)

**Comment by asifjans** [comment]
**Ref material:** 
https://www.jqueryscript.net/demo/Horizontal-Vertical-Timeline-Plugin-jQuery/
http://www.bestjquery.com/2017/03/albe-timeline-jquery-timelines-plugin-json-data/

**Comment by ZarshaB** [comment]
![imgpsh_fullsize](https://user-images.githubusercontent.com/35685146/39355436-aa430db4-4a26-11e8-8074-5a254b546ca0.png)

**Comment by ZarshaB** [comment]
1>> Font is not correct for Heading.
![image](https://user-images.githubusercontent.com/35685146/39807768-98762eee-5396-11e8-9052-bbece0f7d23f.png)

**Comment by ZarshaB** [comment]
2>> Overlapping of image.
![image](https://user-images.githubusercontent.com/35685146/39807814-be8b82f0-5396-11e8-928d-ea0a5584b930.png)

**Comment by ZarshaB** [comment]
3>> Font size should be increased and also Apr 2018 should be in one line.
![image](https://user-images.githubusercontent.com/35685146/39807883-e890bef8-5396-11e8-9632-bf7cd56a32ab.png)

**Comment by ZarshaB** [comment]
4>> Shouldn't it be clickable like it is in template?
![image](https://user-images.githubusercontent.com/35685146/39808269-e73b7bc8-5397-11e8-88a8-0cc8e0336161.png)
![image](https://user-images.githubusercontent.com/35685146/39808290-f1c36240-5397-11e8-8b34-b872003d022a.png)

**Comment by ZarshaB** [comment]
5>> Mobile 
This portion is missing.
![image](https://user-images.githubusercontent.com/35685146/39808545-a3ceb34a-5398-11e8-8fb1-af808cb7a8f2.png)

**Comment by ZarshaB** [comment]
6>> Button moves on scrolling.
![image](https://user-images.githubusercontent.com/35685146/39808594-ca161a84-5398-11e8-9f91-3deac6f3dd90.png)

**Comment by ZarshaB** [comment]
2>> There will come both Model and Make name.
![image](https://user-images.githubusercontent.com/35685146/39875621-8a645e80-548a-11e8-8428-09b884b48998.png)

**Comment by Anum444** [comment]
**Fixed**

1>> No images are appearing on live and also there is overlapping of images.
2>> There will come both Model and Make name.

**Comment by ZarshaB** [comment]
3>> This is half cut.
![image](https://user-images.githubusercontent.com/35685146/39876723-5e68b206-548d-11e8-98a0-d67e74d673b8.png)

**Comment by Anum444** [comment]
**Fixed**
3>> This is half cut.

**Comment by ZahidRavian** [comment]
1>> Images are still not appearing on App. **(Fixed)**
