### ISSUE TITLE
Mobile | Buttons are not working in watch pop up. 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#202]

**Comment by ZarshaB** [comment]
Both buttons are not working in watch pop up of mobile.

**Comment by ZarshaB** [comment]
![image](https://user-images.githubusercontent.com/35685146/38982484-685da202-43db-11e8-9391-36e2d4ff3c76.png)

**Comment by Anum444** [comment]
**RFR**
Both buttons are not working in watch pop up of mobile.

**Comment by ZarshaB** [comment]
Buttons are now working but when I click on Buy Car button then it's shape changes.
![image](https://user-images.githubusercontent.com/35685146/38995277-fed23f56-4401-11e8-9e74-91893016f2e3.png)

**Comment by Anum444** [comment]
Buttons are now working but when I click on Buy Car button then it's shape changes.  **Fixed**
