### ISSUE TITLE
Alignment of pages

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#204]

**Comment by ZarshaB** [comment]
1>> My Ads 
Can you please make them center aligned?
![image](https://user-images.githubusercontent.com/35685146/38984813-2861d050-43e1-11e8-9668-3ef44083a436.png)
![image](https://user-images.githubusercontent.com/35685146/38984855-48c1574e-43e1-11e8-8514-e65d9927797d.png)

**Comment by ZarshaB** [comment]
2>> Reward Points page
When I scroll this page to left then it's alignment changes.
![image](https://user-images.githubusercontent.com/35685146/38984909-70667950-43e1-11e8-9bcc-b7cd18792229.png)

**Comment by Anum444** [comment]
**RFR**

1>> My Ads , My Favorites
Can you please make them center aligned?

2>> Reward Points page
When I scroll this page to left then it's alignment changes.

**Comment by ZarshaB** [comment]
Reward Points Alignment for both tables.
![image](https://user-images.githubusercontent.com/35685146/38996416-97019ec8-4404-11e8-85e5-ad705f737291.png)

**Comment by ZarshaB** [comment]
In website it is okay. But in mobile it is appearing toota phota. :(
![image](https://user-images.githubusercontent.com/35685146/38998045-3624ccca-4408-11e8-8962-c4f7e12cdb99.png)
![image](https://user-images.githubusercontent.com/35685146/38998079-3fee2ed6-4408-11e8-8498-3f1c5e818d69.png)
