### ISSUE TITLE
Mobile | Filter after search

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#206]

**Comment by ZarshaB** [comment]
When I search by using Home page search bar then on Filters page it shows me selected value filter. 

![image](https://user-images.githubusercontent.com/35685146/38998171-713b0310-4408-11e8-9521-ab9a357747ab.png)

**Comment by asifjans** [comment]
**(RFR)** When I search by using Home page search bar then on Filters page it shows me selected value filter.
