### ISSUE TITLE
Issues Remaining other than Zohaib's Issues

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#224]

**Comment by ZarshaB** [comment]
1>> Purchase History 
I have to click on cross button for so many times and then it clicks.
![image](https://user-images.githubusercontent.com/35685146/39352896-8e27b334-4a1f-11e8-810d-e0699271701d.png)

**Comment by ZarshaB** [comment]
2>> Mobile
Paging for My Ads and My Favorites pages.

**Comment by ZarshaB** [comment]
3>> My profile
Saving incomplete Emirates Id.

**Comment by ZarshaB** [comment]
4>> In Nexus back button is not appearing for Car Detail and Filters pages.

**Comment by ZarshaB** [comment]
5>> Radio buttons in Shayan's mobile are not appearing correct.

**Comment by ZarshaB** [comment]
7>> Issue that was fixed for multiple clicks multiple pop ups appears. Now it is appearing in watch pop when I click on favorites icon.
![image](https://user-images.githubusercontent.com/35685146/39364920-13cce206-4a49-11e8-9d6e-095c1e8aade0.png)

**Comment by Anum444** [comment]
7>> Issue that was fixed for multiple clicks multiple pop ups appears. Now it is appearing in watch pop when I click on favorites icon. **(RFR)**
1>> Purchase History    **RFR**
I have to click on cross button for so many times and then it clicks.

**Comment by Anum444** [comment]
2>> @ZahidRavian Mobile **RFR**
Paging for My Ads and My Favorites pages.

**Comment by Anum444** [comment]
2>> My Ads is okay.   **FIXED**
My Favorites is redirecting to this page.

**Comment by ZarshaB** [comment]
7>> There are double arrows.
![image](https://user-images.githubusercontent.com/35685146/39418637-e61bd15e-4c74-11e8-9407-986bca01c85a.png)

**Comment by ZarshaB** [comment]
8>> Radio buttons for Mobile responsive is not appearing okay. They are okay for App.

**Comment by ZarshaB** [comment]
9>> Please make all pop up messages aligned below the cross sign. As it is for My Favorites page.
![image](https://user-images.githubusercontent.com/35685146/39418716-6fd29ab8-4c75-11e8-8d74-5d6abd84b946.png)

Make this message and other messages alignment same as My favorites pop up message. 
![image](https://user-images.githubusercontent.com/35685146/39418726-7dd1977c-4c75-11e8-9178-5967f66cb253.png)

**Comment by ZarshaB** [comment]
10>> Multiple clicks for Place your Ad uploads same ad for multiple times. This issue was fixed but again I'm seeing this.
![image](https://user-images.githubusercontent.com/35685146/39419073-6720c71c-4c77-11e8-81d6-bc430dce8c8f.png)

**Comment by Anum444** [comment]
**please share screen shots of all pop ups**

**Comment by Anum444** [comment]
9>> Please make all pop up messages aligned below the cross sign. As it is for My Favorites page.  **RFR**

**Comment by Anum444** [comment]
10>> Multiple clicks for Place your Ad uploads same ad for multiple times. This issue was fixed but again I'm seeing this.   **RFR**

**Comment by ZarshaB** [comment]
@zohaibqadir 
11>> When I click on here of this message of Buy Car button then it redirects to Home page having back arrow. This arrow should not be here.
![image](https://user-images.githubusercontent.com/35685146/39425561-79e6718a-4c95-11e8-8593-99c25506b9f2.png)

**Comment by Anum444** [comment]
8>> Radio buttons for Mobile responsive is not appearing okay. They are okay for App.   **FIXED**

**Comment by Anum444** [comment]
4>> Radio buttons in Shayan's mobile are not appearing correct.  **RFR**

**Comment by ZarshaB** [comment]
9>> Please make all pop up messages aligned below the cross sign. As it is for My Favorites page.

![image](https://user-images.githubusercontent.com/35685146/39424192-d430e7c6-4c8e-11e8-8cc7-16cdacfe7214.png)

**Comment by Anum444** [comment]
9>> Please make all pop up messages aligned below the cross sign. As it is for My Favorites page.  **RFR**

**Comment by ZarshaB** [comment]
15>> In nexus this cross icon for images is appearing like this.
![image](https://user-images.githubusercontent.com/35685146/39431023-ee57c42a-4ca8-11e8-83d5-2fd0ce740930.png)
![image](https://user-images.githubusercontent.com/35685146/39431041-f6619682-4ca8-11e8-8d30-7cab5dae5344.png)

**Comment by ZarshaB** [comment]
@zohaibqadir 
16>> If I cross this message then it keeps me logged in. This message is being displayed after user has logged out and it is not asking for user's approval to logged out or not. So on clicking on cross icon it should still logged out the user.
![image](https://user-images.githubusercontent.com/35685146/39432487-0edb6fd6-4cad-11e8-97f8-ba4f76cb9c5c.png)

**Comment by Anum444** [comment]
15>> In Nexus this cross icon for images is appearing like this.
image   **RFR**

**Comment by Anum444** [comment]
15>> In Nexus this cross icon for images is appearing like this.
image   **Fixed**
