### ISSUE TITLE
Radio buttons alignment with text

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#230]

**Comment by ZarshaB** [comment]
Radio buttons are not aligned with text on Place your Ad, Filters and My Profile pages but it is aligned at Register page.
![image](https://user-images.githubusercontent.com/35685146/39480485-d21c6fd4-4d81-11e8-8c3b-3ad67eb811e2.png)
![image](https://user-images.githubusercontent.com/35685146/39480508-e6002720-4d81-11e8-9369-5c878bbfae81.png)

**Comment by Anum444** [comment]
Radio buttons are not aligned with text on Place your Ad, Filters and My Profile pages but it is aligned at Register page.   **RFR**
