### ISSUE TITLE
My Profile | Change Password

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#232]

**Comment by ZarshaB** [comment]
It is not working properly as if I enter correct password then it still displays me error that old password is not correct. I tried this multiple times then I logged out and then it worked. And then when I tried with wrong password it gave me success message. And then again it displayed me error message for my correct password.
![image](https://user-images.githubusercontent.com/35685146/39516656-04a3e8e8-4e17-11e8-8f7b-9035f42ec66f.png)

**Comment by ZahidRavian** [comment]
(Fixed) It is not working properly as if I enter correct password then it still displays me error that old password is not correct. I tried this multiple times then I logged out and then it worked. And then when I tried with wrong password it gave me success message. And then again it displayed me error message for my correct password.
![image](https://user-images.githubusercontent.com/35685146/39516656-04a3e8e8-4e17-11e8-8f7b-9035f42ec66f.png)
