### ISSUE TITLE
Safari Issues 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#234]

**Comment by ZarshaB** [comment]
1>> Images borders. 
![image](https://user-images.githubusercontent.com/35685146/39529553-68a6407e-4e40-11e8-82c6-71dcf44771c6.png)

**Comment by Anum444** [comment]
1>> Images borders.  **RFR**

**Comment by Anum444** [comment]
**FIXED**
1>> Images borders.
