### ISSUE TITLE
Remaining Responsive

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#235]

**Comment by ZarshaB** [comment]
1>> iPhone
Radio buttons are not appearing okay.

**Comment by ZarshaB** [comment]
2>> iPhone
How it works page is having double buttons.

**Comment by ZarshaB** [comment]
3>> In Landscape mode radio buttons are not completely filled.
![image](https://user-images.githubusercontent.com/35685146/39529731-d19e3a50-4e40-11e8-8fa2-6a3f228b24f0.png)

**Comment by ZarshaB** [comment]
4>> In How it works menu is not clickable.
![image](https://user-images.githubusercontent.com/35685146/39529775-e725b24a-4e40-11e8-8d5d-056da8f1603b.png)

**Comment by ZarshaB** [comment]
5>> If I upload any word/pdf document then it appears as broken image.
![image](https://user-images.githubusercontent.com/35685146/39530147-ca4997e4-4e41-11e8-8d72-969f72f8967d.png)

**Comment by Anum444** [comment]
3>> In Landscape mode radio buttons are not completely filled.   **RFR**

**Comment by Anum444** [comment]
**RFR**

2>> iPhone
How it works page is having double buttons.

**Comment by Anum444** [comment]
**Fixed**

3>> In Landscape mode radio buttons are not completely filled.

**Comment by Anum444** [comment]
4>> In How it works menu is not clickable.   **RFR**

**Comment by ZarshaB** [comment]
iPhone 
video of How it works is not playing automatically.

**Comment by ZarshaB** [comment]
iPhone 
My Account >> Delete Account >> Buttons are overlapping Again :/.

**Comment by Anum444** [comment]
1>> iPhone
Radio buttons are not appearing okay.                    **RFR**

**Comment by ZarshaB** [comment]
4>> iPhone
Search bar is having white portion in landscape mode.
It changes it's shape in both portrait and landscape.

**Comment by ZarshaB** [comment]
5>> iPhone
Landscape mode | View Cars
Filters and Number of show field are not aligned.

**Comment by ZarshaB** [comment]
6>> Search bar changes it's shape in landscape mode. It was fixed but again seeing it.
![image](https://user-images.githubusercontent.com/35685146/39624082-6f09727a-4fb1-11e8-82e9-b751191a87ec.png)

**Comment by ZarshaB** [comment]
7>> Delete Ad
Radio buttons are not aligned with text.
![image](https://user-images.githubusercontent.com/35685146/39624112-84ed06a6-4fb1-11e8-922d-08040985f551.png)
![image](https://user-images.githubusercontent.com/35685146/39624125-9155110e-4fb1-11e8-9b09-9387011b65cf.png)

**Comment by Anum444** [comment]
**Fixed**

iPhone
My Account >> Delete Account >> Buttons are overlapping Again :/.

**Comment by ZarshaB** [comment]
5>> How it works | Android
Menu is not clickable on this page for both portrait and landscape mode.
Video is not playing automatically. As before both issues were fixed. But I'm seeing it again.
![image](https://user-images.githubusercontent.com/35685146/39635031-c182b15a-4fd5-11e8-974d-849ca843c609.png)

**Comment by Anum444** [comment]
**Fixed**

5>> How it works | Android
Menu is not clickable on this page for both portrait and landscape mode.
Video is not playing automatically. As before both issues were fixed. But I'm seeing it again.

**Comment by Anum444** [comment]
**Fixed**

4>> iPhone
Search bar is having white portion in landscape mode.

**Comment by Anum444** [comment]
**Fixed**

1>> iPhone
Radio buttons are not appearing okay.
