### ISSUE TITLE
Site

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#236]

**Comment by ZarshaB** [comment]
When I click on this highlighted dots then it starts loading and a kind of pop up appears. It should not be clickable or should perform other function.
![image](https://user-images.githubusercontent.com/35685146/39570744-c46e453a-4ee2-11e8-9bb9-6b2a8efd7cee.png)

**Comment by ZarshaB** [comment]
2>> Radio buttons are above the text on Register page.
![image](https://user-images.githubusercontent.com/35685146/39570830-058072f0-4ee3-11e8-843e-57afa888f0d3.png)

**Comment by Anum444** [comment]
2>> Radio buttons are above the text on Register page.  **RFR**

**Comment by Anum444** [comment]
2>> Radio buttons are above the text on Register page.  **Fixed**

**Comment by ZarshaB** [comment]
1>> When I click on this highlighted dots then it starts loading and a kind of pop up appears. It should not be clickable or should perform other function.
![image](https://user-images.githubusercontent.com/35685146/39570744-c46e453a-4ee2-11e8-9bb9-6b2a8efd7cee.png)

**Comment by ZarshaB** [comment]
2>> Radio buttons are above the text on Register page.
![image](https://user-images.githubusercontent.com/35685146/39570830-058072f0-4ee3-11e8-843e-57afa888f0d3.png)

**Comment by ZarshaB** [comment]
**Not fixed**
1>> When I click on this highlighted dots then it starts loading and a kind of pop up appears. It should not be clickable or should perform other function.
![image](https://user-images.githubusercontent.com/35685146/39570744-c46e453a-4ee2-11e8-9bb9-6b2a8efd7cee.png)
