### ISSUE TITLE
Mobile Feedback 20th May 2018

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#247]

**Comment by ZarshaB** [comment]
1>>When the page is opened, will we get the notification on top for downloading the app?

 **All the websites that I've ever come across have this thing. Either they prompt to download app or if app is already downloaded, they prompt to open in it. Please add it and let me know if you need content for it.**

**Comment by ZarshaB** [comment]
2>> General
Website is Still very very slow. Pages are literally taking minutes to load.

**Comment by ZarshaB** [comment]
3>> Home page
Please decrease the size of top most banner (orange with weladela) by 20-30% and the banner should be increase by same ratio i.e. 20-30%. Net space should remain the same

**Not good enough. Please discuss over skype.**

**Comment by ZarshaB** [comment]
4>> Testimonials
Please decrease the size of testimonial pictures by 50%. The have taken way too much space on the screen.

**Please resolve. Just look at it. Testimonials are so important that they are bigger than the car ads, banners and other things on the website. Please make it look normal like all other websites normally have,**

**Comment by ZarshaB** [comment]
5>> Please decrease the size of footer by 30-40% and increase the size of "Download our app" by 30%.

**Please reduce the footer further by 30-40% on mobile version only without effecting the other versions and the font.**

**Comment by ZarshaB** [comment]
6>> When I clicked Learn More on How it Works on Homepage, the video did not play. I had to play it myself. Additionally, the sound is by default on mute. Please make it unmute

**1) My browser (Safari) has auto play option and is automatically playing videos from other sites without mute.
2) Look at the attached image and the presentation of the website. 
3) There is no option to play or pause or time bar in the bottom. For this I have to View Full Screen.**

**Comment by ZarshaB** [comment]
7>> Login with Facebook button

**Button improved but functionality is gone down. It requires two clicks to move ahead. When I press the button once, it changes color. Second time pressed, it performs the function and routes to facebook login page.**

**Comment by ZarshaB** [comment]
8>> Landscape mode
In tilt view, the top two rows (Orange header and second banner) is taking up half the screen. Shouldn't it be responsive and adjust automatically?

**Comment by ZarshaB** [comment]
9>> The featured car lists for the cars lets you scroll the background and not functioning properly when scrolling.

**Comment by ZarshaB** [comment]
10>> Home page
The feature car list moves only once and then stops and the speed is also very slow. I believe you havent changed the timeer to same speed as of the website. When the auto movement ends and has to continue from the 1st featured ad, it makes a big time jerk. Same behavior is observed when it is manually scrolled through left/right arrows.

**Comment by ZarshaB** [comment]
11>> Results
1) The draw result in mobile version should be same as on website. It should have the similar timeline in center with sort option line having month wise sorting option on the top. In mobile version, there is no option to sort results date wise or month wise.
Please refer to attached picture. 

2) There is a grey box around the filter button. Please remove it. 

3) Also, The blank photo slots should be similar in size to the other photo slots.

**Comment by ZarshaB** [comment]
12>> There is a jerk issue for Our Featured Cars section in Safari.

**Comment by ZarshaB** [comment]
This is fixed but when I click on FB button then button disappears.

@sammiullah 

7>> Login with Facebook button

**Button improved but functionality is gone down. It requires two clicks to move ahead. When I press the button once, it changes color. Second time pressed, it performs the function and routes to facebook login page.**

**Comment by ZarshaB** [comment]
This button is not working for iPhone. Also no video is there on How it works page. 
![image](https://user-images.githubusercontent.com/35685146/40353948-23c8b46e-5dcc-11e8-9045-3dd693e7398c.png)

@haideraziz004   @sammiullah 

6>> When I clicked Learn More on How it Works on Homepage, the video did not play. I had to play it myself. Additionally, the sound is by default on mute. Please make it unmute **(Fixed)**

**1) My browser (Safari) has auto play option and is automatically playing videos from other sites without mute.
2) Look at the attached image and the presentation of the website. **(Fixed)**
3) There is no option to play or pause or time bar in the bottom. For this I have to View Full Screen.**

![image](https://user-images.githubusercontent.com/35685146/40297001-b0991e0e-5cf7-11e8-939d-a2ab7e43dcda.png)

**Comment by ZarshaB** [comment]
**Requires response from Client for these points.**
 
@ZahidRavian 
11>> Results
1) The draw result in mobile version should be same as on website. It should have the similar timeline in center with sort option line having month wise sorting option on the top. In mobile version, there is no option to sort results date wise or month wise.
Please refer to attached picture. 

2) There is a grey box around the filter button. Please remove it. 

![image](https://user-images.githubusercontent.com/35685146/40297035-d2f41bfc-5cf7-11e8-9169-007817a1835c.png)

**Comment by ZarshaB** [comment]
12>> There is a jerk issue for Our Featured Cars section in Safari.

**Comment by ZarshaB** [comment]
2>> General
Website is Still very very slow. Pages are literally taking minutes to load.

**Comment by shayanr262** [comment]
"Reopened"
@Anum Cross icon is not at correct place for mobile.
