### ISSUE TITLE
Account Credentials

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#249]

**Comment by ZarshaB** [comment]
1>> For refunds, please create a new email id refunds@weladela.com

**Comment by ZarshaB** [comment]
2>> Please create a new email id rewards@weladela.com and in section 11 of point redeem policy, please replace the already mentioned email address with it.
![image](https://user-images.githubusercontent.com/35685146/40300802-bd368640-5d03-11e8-9592-b7a59db2e9c0.png)

**Comment by ZarshaB** [comment]
3>> In front of each email ID, please add the type of emails it will be getting.

**Comment by ZarshaB** [comment]
4>> •	On Contact Us page, please create and add some generic email ID instead of using rewards@weladela.com. It can be hello@weladela.com

**Comment by ZarshaB** [comment]
5>> The inquiry form submission should route to hello@weladela.com. This way all the contacts made from Contact Us page (Inquiry Form submission and direct email) will be made to only one account i.e. hello@weladela.com.

**Comment by ZarshaB** [comment]
6>> Buy Now request should route to customersupport@weladela.com.

**Comment by ZarshaB** [comment]
7>> Please also mention account on which account deletion and ad deletion requests shall be automatically routed. I think that these two deletion request should also be routed to customersupport@weladela.com.

**Comment by ZahidRavian** [comment]
3>> In front of each email ID, please add the type of emails it will be getting. 

usama@weladeal.com (This email ID is for usama)
admin@weladeal.com (This email ID is for the access of admin portal)
noreply.weladela@weladela.com (All emails will be sent to customers from this email ID )
refunds@weladela.com (Customers can contact any query regarding refunds on this email ID)
rewards@weladela.com  (Customers can contact any query regarding reward points on this email ID)
customersupport@weladela.com (The email will be sent to this email ID when customer will click on Buy Now button)
