### ISSUE TITLE
Web Related IOS Log 16th july 2018

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#274]

**Comment by ZarshaB** [comment]
3>> FAQs
FAQs font of questions and answers os totally different. The answer font is as per old specimen. These FAQs will be reviewed once the font is fixed.

**Comment by ZarshaB** [comment]
4>> My Favorites
1) Some othe cars that I added in My favorties weren't being diplayed in My Favorites even though they had an orange heart on it.

2) When I go to My Favorties and click the information 'I" button, the quick view opens fine but the share button isnt working there.

**Comment by ZarshaB** [comment]
5>> My Ads
 Still there. Infact this time instead of posting my ad, it displayed the message that please login to continue and the ad wasn’t posted. When I went to More menu, it reflected em as signed in

**Comment by ZarshaB** [comment]
6>> Cart
I selected a ticket and opted to continue shopping. The car wasn't added to my cart.

**Comment by ZarshaB** [comment]
7>> Place your Ad
When I place my Ad and adding the details of the car, there is any issue with the list of options. For example, when I want to enter the model, it opens the list for all years, but I cannot select the year by simply clicking on that year (which is a common functionality in iOS). Instead, I have to bring it on that year and then choose "Done". Please rectify this on Place your Ad and everywhere else where we have such options.

**Comment by ZarshaB** [comment]
8>> View Cars
Please refer to attached images, the ads are not aligned properly. Some are shorter than the others.

**Comment by ZarshaB** [comment]
9>> Checkout
Please refer to attached image, When I tried to check out, the checkout button wasn’t displayed. I had to scroll up to see last two buttons at the bottom but couldn’t click them as they wouldn’t stay there.

**Comment by ZarshaB** [comment]
10>> Server Issue
Getting messages from Godday very often. Please resolve. Shouldn’t be happening considering there is only one user at that time. Plus instead of displaying the error message from godaddy, we have a image with message. Please get it from Awaiza.

**Comment by ZarshaB** [comment]
11>> Please refer to attached image. Please rectify spellings everywhere(also there on website) and add a hyperlink like elsewhere.

**Comment by ZarshaB** [comment]
12>> Points Redeem Policy
Please refer to attached image for desktop view; please make the highlighted sentence 6.1 and 6.2 in one line. Same error on iOS

**Comment by ZarshaB** [comment]
11>> Change Password
Still there. Please see the attached image and later got this message from Godaddy. Please note that in such cases, there is separte image that needs to be displayed. Awaiza has it (a guy with tie and messgae for the error)
![image](https://user-images.githubusercontent.com/35685146/42437114-740c6938-8375-11e8-822b-e06160f07c14.png)
![image](https://user-images.githubusercontent.com/35685146/42437145-8ac37fe0-8375-11e8-8430-8f4cbeda9d93.png)

**This issue is not related to me.**

**Comment by ZarshaB** [comment]
**Zahid**
4>> My Favorites

2) When I go to My Favorties and click the information 'I" button, the quick view opens fine but the share button isnt working there.

**Comment by ZarshaB** [comment]
10>> Server Issue
Getting messages from Godday very often. Please resolve. Shouldn’t be happening considering there is only one user at that time. Plus instead of displaying the error message from godaddy, we have a image with message. Please get it from Awaiza.
![image](https://user-images.githubusercontent.com/35685146/42437034-3ce42108-8375-11e8-8cd6-7b6473f6ab3a.png)

**Comment by ZarshaB** [comment]
**I didn't face any issue while posting ad.**
@ZahidRavian 
5>> My Ads
 Still there. Infact this time instead of posting my ad, it displayed the message that please login to continue and the ad wasn’t posted. When I went to More menu, it reflected em as signed in

**Comment by ZarshaB** [comment]
**As per discussion with Usama he asked to look into it and if something could be done.**
7>> Place your Ad
When I place my Ad and adding the details of the car, there is any issue with the list of options. For example, when I want to enter the model, it opens the list for all years, but I cannot select the year by simply clicking on that year (which is a common functionality in iOS). Instead, I have to bring it on that year and then choose "Done". Please rectify this on Place your Ad and everywhere else where we have such options.

**Comment by ZarshaB** [comment]
@ZarshaB 
**Not getting much time for me.**
1>> View Cars
Still there. Takes too much of time for loading.

**Comment by ZarshaB** [comment]
@ZarshaB 
**As per discussion with Usama he asked to look into it and if something could be done.**
3>> FAQs
FAQs font of questions and answers os totally different. The answer font is as per old specimen. These FAQs will be reviewed once the font is fixed.

**Comment by ZarshaB** [comment]
**High Priority**
2>> Cart
I selected a ticket and opted to continue shopping. The car wasn't added to my cart.

**Comment by ZarshaB** [comment]
3>> List view
Whenever I opt list view for cars, why is it reflecting the description of the car there?? Its taking way too much space for one ad. Please remove that portion and size of each ad should be reduced accordingly.

**Comment by ZarshaB** [comment]
4>> Share Button
Please refer to attach image. Whenever I click on share and try to share it through email or whatsapp, the orange border has white line on the left.

**Comment by ZarshaB** [comment]
@zohaibqadir 
5>> Push Notification
Push Notification permission pops up at orange screen. It should come when you the menu screen with banner pages is displayed

**Comment by ZarshaB** [comment]
6>> Ticket Sold
Please refer to attached image. Tickets sold 565%????? That means that we have sold over 3500 tickets for this car. Please put a check on all platforms to stop selling tickets once it reaches 600.

**Comment by asifjans** [comment]
4) USE THREADING ON PAGES WHERE  PROCESSING IS TAKING TIME MORE THAN FEW MINUTS.

LIKE  TICKET SAVED/EAMIL

**Comment by asifjans** [comment]
**(2) Fixed.**
**(3) Fixed.**

**Comment by asifjans** [comment]
**(4) Fixed**
