### ISSUE TITLE
Genral Issues

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#278]
1) Please use Enum all project where we are using hardcode values as

  var orderId = _uow.Orders.AddOrder(new Order
            {
                AccountId = account.AccountId,
                CreatedDate = DateTime.Now,
                **OrderStatus = 2,**
                TotalPrice = price,
                Discount = discountAmount,
                PaidAmount = paidAmount
            });

**Comment by asifjans** [comment]
2) Change cards icon as actual images provied by Designer

**Comment by asifjans** [comment]
3) Purchase history table heading issue
![image](https://user-images.githubusercontent.com/10880558/43315246-cad54f90-91ae-11e8-8f86-da3f20814d83.png)
4) In Internet Explorer testimonial section is hidden.
![image](https://user-images.githubusercontent.com/10880558/43315287-ec333080-91ae-11e8-8fd3-80932bc57ccd.png)

**Comment by asifjans** [comment]
(3) Purchase history table heading issue **(Fixed)**

**Comment by asifjans** [comment]
(2) Change cards icon as actual images provied by Designer **(Fixed)**

**Comment by asifjans** [comment]
(5) Use Threading on Place add scrreen.
other wise it will take time to compres and save images flow

**Comment by asifjans** [comment]
(6) Flush db and fix admin issues.

**Comment by asifjans** [comment]
(7) if add is remove i am getting below email

![image](https://user-images.githubusercontent.com/10880558/43463806-f01cd272-94f2-11e8-869d-f0f53b49b6fc.png)


Please make sure image sh'd be not missing in featured  ads email
and add approved email etc.

**Comment by asifjans** [comment]
(8) In edge browser testimonial section is hidden
![image](https://user-images.githubusercontent.com/10880558/43508469-6f007dd2-9589-11e8-8c86-05422253403f.png)

**Comment by asifjans** [comment]
(9) Result page image is not displayed.

**Comment by ZarshaB** [comment]
12>> Images are not appearing if I make ads featured. 
![image](https://user-images.githubusercontent.com/35685146/43519169-c8449ec8-95a7-11e8-8176-5c0ca03198f9.png)

**Comment by ZarshaB** [comment]
13>> Reward Points
Alignment of table in mobile is disturbed.
![image](https://user-images.githubusercontent.com/35685146/43519887-80192418-95aa-11e8-987c-ef543da02cb1.png)

**Comment by ZarshaB** [comment]
14>> Image is not appearing on cart page.
![image](https://user-images.githubusercontent.com/35685146/43519944-b0135530-95aa-11e8-9d26-08c26fd07fab.png)

**Comment by ZarshaB** [comment]
15>> Results
Images appear when I see by selecting All option. But if I select month then images do not appear.
![image](https://user-images.githubusercontent.com/35685146/43520171-6d66be4c-95ab-11e8-9db9-8fda98326e38.png)

**Comment by ZarshaB** [comment]
16>> Admin portal | Ad Deatil
Images are not appearing.
![image](https://user-images.githubusercontent.com/35685146/43520416-3ea4ac76-95ac-11e8-81cb-5f0f7fd9a1c7.png)

**Comment by ZarshaB** [comment]
17>> Purchase History
Transfer icon is not displaying image.
![image](https://user-images.githubusercontent.com/35685146/43530930-1f6d1796-95c8-11e8-9cf4-a9ea2fd6d232.png)

**Comment by asifjans** [comment]
**(7) Fixed
(9) Fixed
(10) Fixed
(11) Fixed
(12) Fixed
(13) Fixed
(14) Fixed
(15) Fixed
(16) Fixed
(17) Fixed**

**Comment by ZarshaB** [comment]
**Fixed**
7,9,10,11,12,14,15,17

**Not Fixed**
13>> 
16>> Not all images are available from Admin when we see the detail of that image.

**Comment by ZarshaB** [comment]
18>> Dialogue is appearing at Reward Points page.
![image](https://user-images.githubusercontent.com/35685146/43586288-ab8ca62a-9680-11e8-823b-173743f5b145.png)

**Comment by ZarshaB** [comment]
19>>Admin
When I add Reward points page keeps on loading.
![image](https://user-images.githubusercontent.com/35685146/43588635-5e35ede0-9686-11e8-8553-5f5a2ce8eea7.png)

**Comment by ZarshaB** [comment]
20>> Reward Points
I have redeem reward points during purchasing my ad. It has been deleted from my reward points but table of Redeem points is not appearing.
![image](https://user-images.githubusercontent.com/35685146/43588715-893404c8-9686-11e8-9fd2-6f1cdd048751.png)

**Comment by ZarshaB** [comment]
20>> Admin
Description is overlapping in Ad detail page.
![image](https://user-images.githubusercontent.com/35685146/43637844-e1838370-972f-11e8-91a0-f10d017d59b5.png)

**Comment by ZarshaB** [comment]
22>> Cancelled Ad.
Image is not appearing for it. And also it's price is touching the border.
![image](https://user-images.githubusercontent.com/35685146/43639190-d90213a6-9734-11e8-9d64-8e67e9dc9e1f.png)

**Comment by ZarshaB** [comment]
23>> Reward Points
Reward points are not updating in my account on purchasing of tickets.
![image](https://user-images.githubusercontent.com/35685146/43644822-7c6df15e-9749-11e8-8cda-195222c52c45.png)

**Comment by ZarshaB** [comment]
21>> Ticket price is appearing "0" whereas it is appearing correct on cart page.
![image](https://user-images.githubusercontent.com/35685146/43710783-0b380464-998a-11e8-82c8-f4849092a090.png)

![image](https://user-images.githubusercontent.com/35685146/43710757-f7b96630-9989-11e8-8eaa-ff4c829d1195.png)

**Comment by ZarshaB** [comment]
22>> It is displaying negative reward points in my account.
Steps:
a) My reward points balance was zero.
b) I bought ticket of whom price is showing zero but on order summary it displays AED 25.
c) After that I refund that ticket.

![image](https://user-images.githubusercontent.com/35685146/43719384-0039ea38-99a7-11e8-9e58-0bb6cac90e1e.png)

**Comment by ZarshaB** [comment]
21>> Third image of this ad is going out of layout.
![image](https://user-images.githubusercontent.com/35685146/43770595-4d530af2-9a56-11e8-8938-872d34c190dc.png)
