### ISSUE TITLE
Web Related 30th July 2018 Bug Log IOS 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#279]

**Comment by ZarshaB** [comment]
1>> 
1) Refer to attached image. Why we have given so much gap between ticket price and Buy Ticket button? Increase the size of ticket price by 1 font and move the Buy Button a little upwards. 
2) When the clock has stopped, then why is it not reflecting days? Due to this one missing blcok of counter, it looks abnormal. All four blocks of the counter should be there.
3) Refer to 2nd attahced image. The 1st sceen shot shows that "L" pf Lamborghini is capital in the list but when we go in the ad detail, it automtaically becomes smal "l". 

Above mentioned three issues are there in all versions (iOS, Android and desktop)

![image](https://user-images.githubusercontent.com/35685146/43385133-62ed8fe4-93f9-11e8-9b76-9a26c11d0ead.png)
![image](https://user-images.githubusercontent.com/35685146/43385155-6e482e8a-93f9-11e8-8f89-f861f32ccdaf.png)
![image](https://user-images.githubusercontent.com/35685146/43385181-7d15e344-93f9-11e8-9e3e-8cffb24bdb85.png)

**Comment by ZarshaB** [comment]
2) Loading Arrows
When the arrows are loading and moving front and back, in their backward motion, they leave a light colored trail. This is new. Please let them the way they are in all versions

**Comment by ZarshaB** [comment]
3>> Image Optimization
Nothing found as was discussed. Same images with variable sizes and as result its taking lots of time to load.

**Comment by ZarshaB** [comment]
4>>In some ads, the counter is below the image, in some its half way and iin others it over the image. Issue in all versions
![image](https://user-images.githubusercontent.com/35685146/43385338-f6b73964-93f9-11e8-8377-0e3f5ebca7f5.png)
![image](https://user-images.githubusercontent.com/35685146/43385348-00516418-93fa-11e8-9eb1-54e844c4ac83.png)

**Comment by ZarshaB** [comment]
5>> View Cars
View Cars Page/Home page takes forever to load. After showing loading arrows, it goes blank for good 3-4 seconds giving impression of malfunction.
Still there. Takes too much of time for loading.

6>>  Everything is taking forever to load. Please look into it.

**Comment by asifjans** [comment]
2>> Image Optimization
Nothing found as was discussed. Same images with variable sizes and as result its taking lots of time to load. **(Fixed)**

**Comment by asifjans** [comment]
3>>In some ads, the counter is below the image, in some its half way and iin others it over the image. Issue in all versions. **(Fixed)**

**Comment by ZarshaB** [comment]
2>> In mobiles complete version images are not displayed.
![image](https://user-images.githubusercontent.com/35685146/43407537-7389b244-9438-11e8-8898-44944bf2121e.png)

**Comment by asifjans** [comment]
2>> Image Optimization
In mobiles complete version images are not displayed. **(Fixed)**

**Comment by ZarshaB** [comment]
2>> Fixed.

**Comment by ZarshaB** [comment]
1>> 
     (1)Only Ticket Price font left otherwise gap is reduced.
     (2)Fixed on Demo
     (3)Fixed on Demo
