### ISSUE TITLE
Time format in All Grids

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#28]
Time format in All Grids

**Comment by asifjans** [comment]
a) Time  format still missing for
 Manage Accounts   Browse Accounts  Edit Account > Services grids

1. - Termination 
2. - Call Agents
3. - Call back.
4. - Confrence Grid
5. - Sims  > Availble sims grid

b)  Manage Accounts   Browse Accounts  Edit Account > Services 
- CRUD of Call forword services date and time is not displayed on edit mode.

**Comment by asifjans** [comment]
c)  Rate Management  Browse Rate Schedules  Edit Rate Schedule
Time format issue
Rate Schedule Item Grid.

**Comment by asifjans** [comment]
e) Cost Management  Browse Cost Schedules  Edit Cost Schedule
Cost Schedule items

**Comment by asifjans** [comment]
f)  User Management  Browse Users
 in users grid

**Comment by haideraziz004** [comment]
a)
1 - fixed
2 - fixed
3 - fixed
4 - fixed

**Comment by haideraziz004** [comment]
a)
5 - fixed
6 - fixed

b) fixed

**Comment by haideraziz004** [comment]
@asifjans  it seems user gird is showing right format of date time(point f). can you please check it?

**Comment by haideraziz004** [comment]
c) fixed
d) fixed
e) fixed
f) fixed
g) fixed
