### ISSUE TITLE
Admin Issues

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#281]

**Comment by ZarshaB** [comment]
1>> Tables are going out of layout.
![image](https://user-images.githubusercontent.com/35685146/43463986-5c870a40-94f3-11e8-82ab-20c963e168a3.png)

**Comment by ZarshaB** [comment]
2>> If I delete pending ads then it keeps on loading and I have to refresh page and then it gets deleted.

**Comment by asifjans** [comment]
1>> Tables are going out of layout. **(Fixed)**
2>> If I delete pending ads then it keeps on loading and I have to refresh page and then it gets deleted.**(Fixed)**
