### ISSUE TITLE
Price in decimal

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#292]

**Comment by ZarshaB** [comment]
1>> Please change 500 to 250.
![image](https://user-images.githubusercontent.com/35685146/46539431-e3c62800-c8cf-11e8-96e7-4254561d9848.png)

**Comment by ZarshaB** [comment]
2>> As this requirement has changed so this message should not be displayed.
Steps:
I removed the entered reward points.
And clicked on Apply Reward Points button.
It displayed me this error message.
![image](https://user-images.githubusercontent.com/35685146/46539959-6c919380-c8d1-11e8-8ceb-9be9a1e4d798.png)

**Comment by ZarshaB** [comment]
3>> Please remove this price from integer and make it decimal.
![image](https://user-images.githubusercontent.com/35685146/46540363-88e20000-c8d2-11e8-8988-abecb803adc6.png)

**Comment by ZarshaB** [comment]
4>> Also After transfer ticket reward points should be: Remaining price multiply by 50.
![image](https://user-images.githubusercontent.com/35685146/46541865-87b2d200-c8d6-11e8-8ea8-3308e5980f01.png)

**Comment by ZarshaB** [comment]
3>> Still there

**Comment by asifjans** [comment]
@Anum444  Please check (3)

**Comment by Anum444** [comment]
3>> Please remove this price from integer and make it decimal.  **(FIXED)**

**Comment by asifjans** [comment]
@ZarshaB  please test and confirm.

**Comment by ZarshaB** [comment]
It is removed from above table of this page but it is here on this list.
![image](https://user-images.githubusercontent.com/35685146/47425450-be785b80-d7a3-11e8-9d90-d13a8b9b54b5.png)

**Comment by Anum444** [comment]
It is removed from above table of this page but it is here on this list. 
(**RFR**)
