### ISSUE TITLE
Issues 15-10-18

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#296]

**Comment by ZarshaB** [comment]
1>> The banner image that recently added is showing white space in responsive.
![image](https://user-images.githubusercontent.com/35685146/46938159-76a75500-d07c-11e8-8463-9bc9a29193a5.png)

**Comment by ZarshaB** [comment]
2>> Order id of transfer ticket in email is appearing different than order id of same ticket in Purchase History of user's account.
![image](https://user-images.githubusercontent.com/35685146/46938220-9d658b80-d07c-11e8-9715-da666cbe9180.png)
![image](https://user-images.githubusercontent.com/35685146/46938232-a6eef380-d07c-11e8-806c-007906554a8b.png)

**Comment by Anum444** [comment]
2>> Order id of transfer ticket in email is appearing different than order id of same ticket in Purchase History of user's account.   **Fixed**
