### ISSUE TITLE
Promotion code Feature Issues

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#299]

**Comment by ZarshaB** [comment]
1>> If Promotion code is inactive it is still being used.

**Comment by ZarshaB** [comment]
2>> Search of Promotion Code is not working.

![image](https://user-images.githubusercontent.com/35685146/47225279-1fd0b100-d3d7-11e8-9d2d-1fd19b829d5b.png)

**Comment by ZarshaB** [comment]
3>> Export of Promotion code is exporting wrong file.

**Comment by ZarshaB** [comment]
4>> It either discount for promotion code or reward points not both. It works for the one I used latest.
![image](https://user-images.githubusercontent.com/35685146/47225378-60c8c580-d3d7-11e8-8358-a0d25a3f1970.png)

**Comment by ZarshaB** [comment]
5>> Please also check is round off working fine.

**Comment by asifjans** [comment]
@ZarshaB  all issues fixed,  please take a look and confirm...

**Comment by ZarshaB** [comment]
**Re-opened:**
3>> It is exporting file with correct file name and fields. But now when I export file then it does not include the starting zeros of discount code. For example if code is 002 then it only displays in exported file as 2.
![image](https://user-images.githubusercontent.com/35685146/47282613-584fd500-d5f9-11e8-8be1-482d2d39ddf5.png)
5>> Still there.

**Comment by ZarshaB** [comment]
**Reopened:**
4>> If I use promotion code first without redeeming any reward points then it displays zero in discount whereas it will display success message of discount.
![image](https://user-images.githubusercontent.com/35685146/47282708-b381c780-d5f9-11e8-93e7-6eeced2d00e1.png)

If I redeem reward points let's say 250 for which discount would be 5. Then it works fine for this part.
![image](https://user-images.githubusercontent.com/35685146/47282783-ecba3780-d5f9-11e8-81fb-fe36b2585cfc.png)

And after redeeming reward points if I use promotion code then the discount provided is not accurate. For example: After redeeming 250 reward points, I got discount of AED 5. Now if I use promotion code ABC which is giving 50% discount. So 50% discount of 45 would be 22.5 which is 23 after rounding off. But as here rounding off is not working correctly so we take 22 as 50% discount of 45 AED. Now after adding 22 into 5 we got 27 as discount value. But here we are getting 25 in discount and it's VAT 5% changes value to 1 which is 2 for 45. 
![image](https://user-images.githubusercontent.com/35685146/47282943-85e94e00-d5fa-11e8-99d4-5028c8e49215.png)

**Comment by Anum444** [comment]
3>> Export of Promotion code page is exporting wrong file.  **(FIXED)**

**Comment by ZarshaB** [comment]
3>> Fixed

**Comment by asifjans** [comment]
@ZarshaB  Please check 4&5 [Fixed]
