### ISSUE TITLE
24-10-2018 Changes Feedback 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#300]

**Comment by ZarshaB** [comment]
1>> Font of “Apply Promotion Code” should be same as others

**Comment by ZarshaB** [comment]
2>> Button should also be the same with proper spacing from the data entry box

**Comment by ZarshaB** [comment]
3>> Too much distance given in below highlighted area. It is Ok in live version. So when you upload the changes, please make sure that this distance should be standard.

**Comment by ZarshaB** [comment]
4>> Please refer to below mentioned image. When does this message appear? And we need to change it.
![image](https://user-images.githubusercontent.com/35685146/47416587-7ea77900-d78f-11e8-9933-0e3b70e4f780.png)

**Comment by ZarshaB** [comment]
5>> When I transferred one ticket, its status was shown as draw concluded. Please refer to below image. Please make sure that when uploaded to live, it should be as per our agreed description.
![image](https://user-images.githubusercontent.com/35685146/47416636-8ff08580-d78f-11e8-87a7-aa27311ec427.png)

**Comment by ZarshaB** [comment]
6>> Please refer to below image. There shouldn’t be any message after applying the discount. And the discount code should remain written in the box.
![image](https://user-images.githubusercontent.com/35685146/47416676-a5fe4600-d78f-11e8-9e91-029de0401729.png)

**Comment by ZarshaB** [comment]
7>> In Ticket management, it is showing full price in “Price Paid” whereas I paid discounted price. This issue is not there in live. So please make sure that when uploaded to live, this issue should not be there.
![image](https://user-images.githubusercontent.com/35685146/47416705-b6aebc00-d78f-11e8-9ffc-01db4639f20e.png)

**Comment by ZarshaB** [comment]
9>>I chose a ticket of AED 750. Applied 5000 reward points of worth 100. Total payable became 650. The I applied 10% DISCOUNT and total payable became 575. So I paid this amount. But in admin portal, the total sale before purchase was 19665 and after purchase was 20315. So instead of adding 575 in total sale, it added 650. So it is ignoring the promotion code discount and still adding it to total. Same issue with current month sale. Instead it should have a separate boxes on dashboard for Current Month Discount and Total Discount. It should have a report generation with all details similar to Point Redeem Report with two additional columns i.e. Promotion Code and Percentage Discount

**Comment by ZarshaB** [comment]
10>> There should be another column on Dashboard for VAT. In reports, it should have report generation for VAT paid with all details of customer like First and Last name, Customer ID, Contact Number, Email ID, Purchase date, Total Amount Paid(after promo code and reward points), VAT charged, Ad Reference, Car Make, Model and Ticket Reference number.

**Comment by ZarshaB** [comment]
11>> Use word “Promo Code” instead of Promotion Code every where.

**Comment by ZarshaB** [comment]
**Re-opened**
7>> It is okay for mentioned Admin panel. But at purchase history and ticket it is showing discount price which should be original price.
![image](https://user-images.githubusercontent.com/35685146/47498591-2055c580-d877-11e8-965a-9aef26bd9dad.png)
![image](https://user-images.githubusercontent.com/35685146/47498600-28ae0080-d877-11e8-9554-82de1189db53.png)

**Comment by ZarshaB** [comment]
**Reopened**
9>> It is not adding correct value of discount price as discount price that appears at Admin with Ticket is not correct. Also there is no promotion code report similar to redeem point report. 
![image](https://user-images.githubusercontent.com/35685146/47504483-c5779a80-d885-11e8-9c5c-50aa1eae14cf.png)

**Comment by Anum444** [comment]
> 10>> There should be another column on Dashboard for VAT. In reports, it should have report generation for VAT paid with all details of customer like First and Last name, Customer ID, Contact Number, Email ID, Purchase date, Total Amount Paid(after promo code and reward points), VAT charged, Ad Reference, Car Make, Model and Ticket Reference number.

**Comment by ZarshaB** [comment]
10>> **Need Clarification for two points otherwise it is working okay.**

**Comment by Anum444** [comment]
11>> Use word “Promo Code” instead of Promotion Code every where. **(Fixed)**
10>> There should be another column on Dashboard for VAT. In reports, it should have report generation for VAT paid with all details of customer like First and Last name, Customer ID, Contact Number, Email ID, Purchase date, Total Amount Paid(after promo code and reward points), VAT charged, Ad Reference, Car Make, Model and Ticket Reference number. **(Fixed)**

**Comment by Anum444** [comment]
Re-opened
7>>Price paid is not correct. And purchase history and ticket it is showing discount price which should be original price. (RFR)

Reopened
9>> It is not adding correct value of discount price as discount price that appears at Admin with Ticket is not correct. Also there is no promotion code report similar to redeem point report. **RFR**

**Comment by ZarshaB** [comment]
Instead Promotion code should have a separate boxes on dashboard for Current Month Discount and Total Discount. It should have a report generation with all details similar to Point Redeem Report with two additional columns i.e. Promotion Code and Percentage Discount
