### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#302]
1) Employe shd be able to his/her attandance list
2) Admin sh'd be able to add/edit/delete attandence of any employe
3) Admin sh'd be able to search attandce by Date and Employe id 
4) Employe sh'be able to appy for Leave, Employe can see his/her leaves
5) Admin sh'd be able to view/Approve employee leave

**Comment by shafin2** [comment]
1) Editor Box 
2) Assign to another 
3) Employee also create task and just delete his own tasks
