### ISSUE TITLE
HomePage Required Things

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#304]

**Comment by ZarshaB** [comment]
Please find attached the images and other things required by you for homepage design. Please let me know if there is anything missing from it. And this file may contain layout for other pages but as of now, please use only for homepage. 
[UI of WelaDela.zip](https://github.com/asifjans/Inovedia/files/2533271/UI.of.WelaDela.zip)

**Comment by asifjans** [comment]
@ZarshaB  @Anum444  Please suggest theme for it.

**Comment by ZarshaB** [comment]
Okay Sir.

**Comment by ZarshaB** [comment]
http://templines.rocks/html/legaster/home-1.html
https://arsesina.com/shopina/index.html
https://preview.themeforest.net/item/thalia-hotel-and-resort-booking-bootstrap-template/full_screen_preview/22937162

**Comment by Anum444** [comment]
https://demo.themefuse.com/?theme=autotrader&device=desktop
