### ISSUE TITLE
Pop up font color is different

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#310]

**Comment by ZarshaB** [comment]
The pop up that appears after ticket purchase has different font color then pop up that appears after Placing ad.

![image](https://user-images.githubusercontent.com/35685146/48261042-80d02f80-e43f-11e8-8ffc-2aed5debd566.png)
![image](https://user-images.githubusercontent.com/35685146/48261048-875ea700-e43f-11e8-82fc-ae6e2b6693b8.png)

**Comment by asifjans** [comment]
@ZarshaB  which one is prefect?

**Comment by ZarshaB** [comment]
There are different font colors of different pop ups. 
![image](https://user-images.githubusercontent.com/35685146/48261214-22f01780-e440-11e8-94d1-0ec16f1a4859.png)
![image](https://user-images.githubusercontent.com/35685146/48261223-2c797f80-e440-11e8-8a1b-715955f61b8c.png)
![image](https://user-images.githubusercontent.com/35685146/48261236-3602e780-e440-11e8-8c94-cbf384498f1c.png)
![image](https://user-images.githubusercontent.com/35685146/48261250-41eea980-e440-11e8-80eb-a175e0005c20.png)
![image](https://user-images.githubusercontent.com/35685146/48261261-4c10a800-e440-11e8-80f1-9da9a06bd84c.png)

**Comment by asifjans** [comment]
which one is ideal, so that we will follow that.....

**Comment by ZarshaB** [comment]
I think this is okay.
![image](https://user-images.githubusercontent.com/35685146/48261383-bc1f2e00-e440-11e8-81dd-eb9aac2b5c46.png)
