### ISSUE TITLE
Usama's Feedback for Keychain 11-12-2018

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#311]

**Comment by ZarshaB** [comment]
1>> The counter in iOS is not working.

**Comment by ZarshaB** [comment]
2>> In View cars page and home page, the keychain and counter needs to be a little smaller and moved right and upwards. The circle edges of the bottom should touch the picture line and not overlap it.

**Comment by ZarshaB** [comment]
3>> The keychain image is way too big in mobile versions. It should be optimized.

**Comment by ZarshaB** [comment]
4>> In Purchase History, the key chain image should be in a separate column under the heading “Product Details”. And the Ad title should be in line with other columns.

**Comment by ZarshaB** [comment]
5>> In purchase history in mobile browser, there is no keychain image.

**Comment by ZarshaB** [comment]
6>> In cart, one condition needs to be added in T&Cs mentioned there. It should be at the last and should read  All pick-up schedule requests must be addressed to pickup@weladela.com.

**Comment by ZarshaB** [comment]
7>> Keychain image is still blur in mobile versions.

**Comment by ZarshaB** [comment]
8>> In HIW first orange box on Homepage, the text should be in line with other two boxes and should be in two lines.

**Comment by ZarshaB** [comment]
9>> In Buyer FAQs Question: I made online purchase but the Raffle Draw did not take place.
Answer: There can be three major reasons for it. (1) Seller has changed his mind about selling the car (2) He has already sold the car (3) The desired number of items were not sold. In all cases, we will transfer your ticket to a draw for any other car. A new ticket will be issued and will be sent to your email. If the older ticket is of more value than the new ticket, then you will get free additional tickets having value equivalent to the amount you have already paid. In case if there is any balance left, it shall be transferred to your weladela.com account in form of reward points.

**Comment by ZarshaB** [comment]
10>> The order confirmation email is missing this text. Please refer to previously sent document to check the placement of text. 
You can collect your purchased product from our Head Office in Dubai within one calendar month. You must schedule your pick-up at least one week before collection. All pick-up schedule requests must be addressed to pickup@weladela.com

**Comment by ZarshaB** [comment]
2>> **Re-opened**
The space of keychain circle is different for Home page and View cars page. The space of View cars page is okay.
![image](https://user-images.githubusercontent.com/35685146/48356435-14139a00-e6b8-11e8-8564-6293ba070866.png)
![image](https://user-images.githubusercontent.com/35685146/48356449-1d9d0200-e6b8-11e8-8077-5970df005bab.png)

**Comment by ZarshaB** [comment]
8>> **Re-opened**
Not fixed.
![image](https://user-images.githubusercontent.com/35685146/48357295-0e1eb880-e6ba-11e8-963a-5e2acf604e45.png)

**Comment by ZarshaB** [comment]
10>> **Re-opened**
Not fixed.

**Comment by ZarshaB** [comment]
10>> Re-opened
It is missing a text.
![image](https://user-images.githubusercontent.com/35685146/48410779-7674a500-e761-11e8-84d9-0e40198604f7.png)

**Comment by ZarshaB** [comment]
2>> **Re-opened**
The space of keychain circle is different for Home page and View cars page. The space of View cars page is okay.
![image](https://user-images.githubusercontent.com/35685146/48356435-14139a00-e6b8-11e8-8564-6293ba070866.png)
![image](https://user-images.githubusercontent.com/35685146/48356449-1d9d0200-e6b8-11e8-8077-5970df005bab.png)

**Comment by Anum444** [comment]
**Fixed**
2>> Re-opened
The space of keychain circle is different for Home page and View cars page. The space of View cars page is okay. And also same for mobile version. In mobile landscape mode counter is not on keychain ribbon.

**Comment by ZarshaB** [comment]
2>> Re-opened:
Counter placing issue.
![image](https://user-images.githubusercontent.com/35685146/48472601-71bef800-e818-11e8-9dea-95fd6178bb54.png)
![image](https://user-images.githubusercontent.com/35685146/48472615-7aafc980-e818-11e8-985f-a357d34cece3.png)

**Comment by Anum444** [comment]
**RFR**
2>> Re-opened:
Counter placing issue.
And in Mobile view counter and key placement is not correct.
