### ISSUE TITLE
Generate Ticket And Account Creation Functional

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#315]

**Comment by ZarshaB** [comment]
1>> He wants that account creation should be normal and that account should remain permanently there.
Customer could use it in future. 
He will get promotional emails and all other emails as normal.

**Comment by ZarshaB** [comment]
2>> There should be two options:
Account create 
Ticket generate.
If Admin only create account then only account is created. 
And if he wants to purchase ticket further then there should be option for purchasing ticket.

**Comment by asifjans** [comment]
7) in mobile view buttons are overallping
![image](https://user-images.githubusercontent.com/10880558/49214106-b5ecf380-f3e7-11e8-9e28-606d385aead8.png)
8) add links "View Tickets" and "View Accounts"
9) sort list of add by SNO

**Comment by asifjans** [comment]
10) if user enter email or phone, and any account already exist with phone or email address in alert show message,"account with this email | phone already exist in the system! do you want to  proceed with it?

if  no alert will be ignore, otherwise

we will auto fill text boxes with that account details and in add button will be converted to update
and in session we will add accountid

**Comment by ZarshaB** [comment]
11>> Please correct it's spelling. It's "Heard From".
![image](https://user-images.githubusercontent.com/35685146/49278497-ce701300-f4a6-11e8-8234-ecb2538616db.png)

**Comment by ZarshaB** [comment]
12>> It's arrows are at wrong position.
![image](https://user-images.githubusercontent.com/35685146/49278542-f65f7680-f4a6-11e8-8e50-435784ae1f6d.png)

**Comment by ZarshaB** [comment]
13>> It is creating my account without correct mobile number.
![image](https://user-images.githubusercontent.com/35685146/49278624-2870d880-f4a7-11e8-8430-fd14cffee18c.png)

**Comment by ZarshaB** [comment]
14>> User is not able to create account with it's email address.

**Comment by ZarshaB** [comment]
**Reopened**
4>> It does not have Date of Birth field.
And also password field. Like which password it will use while login from his account?

**Comment by ZarshaB** [comment]
Reopened
10>> It is not displaying message that is mentioned by sir. And also it's buttons are changed. And "No" button has outline around it.
![image](https://user-images.githubusercontent.com/35685146/49279722-0d539800-f4aa-11e8-853c-ada0b310a275.png)

**Comment by ZarshaB** [comment]
16>> Buttons are overlapping and also text should be center aligned.
![image](https://user-images.githubusercontent.com/35685146/49280589-645a6c80-f4ac-11e8-8c00-aab4e22ef977.png)

**Comment by ZarshaB** [comment]
17>> When I used HappyDeal promo code then it displayed me both these boxed.
![image](https://user-images.githubusercontent.com/35685146/49280755-c7e49a00-f4ac-11e8-96d1-c82e6ecd8036.png)

**Comment by ZarshaB** [comment]
18>> After payment gateway it displayed me this message.
![image](https://user-images.githubusercontent.com/35685146/49280907-17c36100-f4ad-11e8-97a8-cdae805da580.png)

**Comment by ZarshaB** [comment]
19>> This Get Ticket option brings me back on this page.
![image](https://user-images.githubusercontent.com/35685146/49280999-50633a80-f4ad-11e8-9e19-76151c68e878.png)

**Comment by ZarshaB** [comment]
**Reopened**
10>>Please Make this message like this:
"Account with this Email/Mobile Number already exists in the system. Do you want to proceed with it?"
![image](https://user-images.githubusercontent.com/35685146/49454374-d8777600-f806-11e8-98d1-12e4ab5872a4.png)

**Comment by ZarshaB** [comment]
20>> On clicking on "Remove" button of Promotion code it displays me this message.
![image](https://user-images.githubusercontent.com/35685146/49454743-9bf84a00-f807-11e8-9b63-243c551df4ef.png)

**Comment by ZarshaB** [comment]
**Reopened**
12>> Still there.

**Comment by Anum444** [comment]
**RFR**
8) add links "View Tickets" and "View Accounts"

**Comment by ZarshaB** [comment]
21>> Please make it in two lines. Ooops will be in first line and in the center and other messages would be at second line.
![image](https://user-images.githubusercontent.com/35685146/49519036-e50cd480-f8c1-11e8-9bb5-a16a8989db6f.png)

**Comment by ZarshaB** [comment]
22>> It should not display me this message if empty form is submitted. It should display this message if whole form is submitted without filling email or mobile number any of these fields.
![image](https://user-images.githubusercontent.com/35685146/49519108-0f5e9200-f8c2-11e8-9031-c7762c55dbd0.png)

**Comment by ZarshaB** [comment]
23>> It should be aligned with field.
![image](https://user-images.githubusercontent.com/35685146/49519165-3026e780-f8c2-11e8-9c6c-8b1270d2b93b.png)

**Comment by ZarshaB** [comment]
24>> If I give it mobile number then does not already exist then it is still displaying me this  message.
![image](https://user-images.githubusercontent.com/35685146/49519423-bfcc9600-f8c2-11e8-8344-da8fa2cc1f8a.png)

**Comment by ZarshaB** [comment]
27>> When it displays the message of email/mobile number already exists do you want to replace it. Then after updating it saves mobile number in 6 digits.
![image](https://user-images.githubusercontent.com/35685146/49520482-2e125800-f8c5-11e8-9f7f-05794f14ceff.png)

**Comment by ZarshaB** [comment]
28>> There should be space between both buttons. And also "No" button should be same as other pop ups of this page.
![image](https://user-images.githubusercontent.com/35685146/49521272-e8568f00-f8c6-11e8-960b-81ece2885622.png)

**Comment by ZarshaB** [comment]
29>> After I have applied promo code. It disappears from the Promo code field.
![image](https://user-images.githubusercontent.com/35685146/49577035-6028c600-f968-11e8-9b9c-2793974e7769.png)

**Comment by ZarshaB** [comment]
30>> Please put full stop at the end of this sentence.
![image](https://user-images.githubusercontent.com/35685146/49639374-a5163080-fa2c-11e8-9bad-292d3ce8525d.png)

**Comment by ZarshaB** [comment]
31>> In User's Account it is displaying payment method as Rewards.
![image](https://user-images.githubusercontent.com/35685146/49644516-70a97100-fa3a-11e8-83b2-534d24acc721.png)

**Comment by ZarshaB** [comment]
32>> When I update from here, it does not update in original account.
![image](https://user-images.githubusercontent.com/35685146/49645722-caac3580-fa3e-11e8-88c8-5bd269a590d6.png)

**Comment by ZarshaB** [comment]
33>> I checked out without filling billing address field and it took me to payment gateway.

**Comment by ZarshaB** [comment]
**Re-opened**
21>> Okay now they are in two lines. But I think Ooops and Hollaa should be in center.

**Comment by ZarshaB** [comment]
34>> After account creation and purchasing ticket. It is taking me to login screen after payment gateway.

**Comment by Anum444** [comment]
**FIXED**
4>> Create Account
It will have all normal and mandatory fields like First Name, Last Name, City, Nationality, Mobile Number, Date of Birth, Hear About Us etc.

**Comment by Anum444** [comment]
**FIXED**
33>> I checked out without filling billing address field and it took me to payment gateway.

**Comment by ZarshaB** [comment]
33>> Okay now it highlights the field but it does it in blue color. It should display similar error message as it does on cart page.
![image](https://user-images.githubusercontent.com/35685146/49796244-ff313180-fd5d-11e8-9df6-10203029c0a3.png)
![image](https://user-images.githubusercontent.com/35685146/49796286-153ef200-fd5e-11e8-81eb-86b6628d856d.png)

**Comment by ZarshaB** [comment]
34>> It keeps on logging me out after purchasing of ticket.

**Comment by Anum444** [comment]
**FIXED**
33>> Okay now it highlights the field but it does it in blue color. It should display similar error message as it does on cart page.
34>> It keeps on logging me out after purchasing of ticket.
