### ISSUE TITLE
Fixed but needs debugging to check this could not appear again. 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#317]

**Comment by ZarshaB** [comment]
1>> Please see if keychain image could be reduced a little more in mobile versions.

**Comment by ZarshaB** [comment]
2>> Keychain image is still blur in mobile versions.

**Comment by ZarshaB** [comment]
3>> **Discount Report**
1) For my purchase of AED 995, I got 100 discount from 5000 points. In downloaded report, it is showing 5000 under points discount column and AED 100 promotion discount. It should be only AED 100 under points discount.
2) For my purchase of AED 270, I got 50% discount on promo code. But nothing is reflected under promotion code column in downloaded report.

**Comment by ZarshaB** [comment]
4>> **View cars sorting**
Doesn't work. I changed status of car from serial 1 to serial 34 and serial 8 but it moved only to third position. It sould work in such a wy that View Cars landing page sorted from Ticket Price High to Low by default. But when admin changes the serial of any specific car, it should bypass this check and should go to the end.

**Comment by ZarshaB** [comment]
5>> When I select COD, the charges are not being reflected in total. The delivery charges are not added in total. It is only reflected in the delivery charges column.

**Comment by ZarshaB** [comment]
6>> **COD Form**
In text input columns in COD form, please leave First Name and Last Name column empty. In Shipping address input column, please add "Enter Apt/Villa No, Building Name, Street No. and Area"
2) The heading COD Information should be changed to Shipping Information

**Comment by ZarshaB** [comment]
7>> Please give space after full stop and then add this line i.e. …..Sharjah and Ajman. Free shipping for orders over AED 100.
![image](https://user-images.githubusercontent.com/35685146/48606130-934aeb80-e9a0-11e8-85bc-fd3ac8715818.png)

**Comment by ZarshaB** [comment]
8>> **COD Report:**
 In downloaded report and in admin portal, the total paid is being reflected without including delivery charges. It should be total of both columns but only in this report. The total sales report should be without COD.

**Comment by ZarshaB** [comment]
9>> **COD Emails**
1) There will be two different mails for COD. One is when customer places order and second is when he makes payment and admin generates ticket. Both are different from Card payment emails and are attached in word document for your reference. 
2) How will admin generate ticket to send to customer through courier company? Currently ticket is only generated when admin presses generate ticket button and this way customer also gets the ticket in email without payment. Concept is when rider goes to collect payment, he should have a copy of ticket with him to deliver as well. 

**Mail for COD Order Placement.**
![image](https://user-images.githubusercontent.com/35685146/48606232-ede44780-e9a0-11e8-80f7-fc82a0faa413.png)

**Mail for COD customer makes payment and Admin generates Ticket:**
![image](https://user-images.githubusercontent.com/35685146/48606286-19673200-e9a1-11e8-9142-0c6b27438ee5.png)

**Comment by ZarshaB** [comment]
10>> This issue is both in demo and live. Please check my last two purchases. In first I applied 5000 reward point discount worth AED 100 on two tickets of AED 750 and AED 245. Total was AED 995 and after discount I paid AED 895. However, in admin, the amount paid is shown as AED 650 and AED 145 which means that it has deducted 200 in total. And in total and monthly sale same amount after discount of 200 is being shown. In reward points, same reward points are being shown i.e. 650 and 145 reward points.

**Comment by ZarshaB** [comment]
11>> This issue is both in demo and live. Please check my last purchase. I applied 50% discount on two tickets of AED 25 and AED 245. Total was AED 270  and after discount I paid AED 135. However, in admin, the amount paid is shown as 0 for AED 25 ticket and AED 135 for ticket worth AED 245. In reward points, same reward points are being shown i.e. 0 and 130 reward points. Although in total accounting, the net figure is correct but should be having separate discount like 12.5 and 122.5 for above case

**Comment by ZarshaB** [comment]
12>> Whenever I export any file like Account Management, Ad Management , Ticket Management, Reward Management etc, it is not covering all fields that are there in admin panel. For example, when I downloaded account management report, it did not have columns for Total Tickets and Total purchases. These columns are reflected in admin portal but not exported. Please make sure that all fields that are visible in admin portal should also be downloaded.

**Comment by ZarshaB** [comment]
13>> Please also add this point as well in changes:-

Change "Hear From Us" to as follows in alphabetical order:-

1) Facebook
2) Instagram
3) Youtube
4) Snapchat
5) Google Ads
6) ENOC 
7) Radio
8) Other Video Ads
9) KIOSK in Malls
10) SMS

**Comment by ZarshaB** [comment]
6>> **Reopened**
Not fixed these points:
In text input columns in COD form, please leave First Name and Last Name column empty. In Shipping address input column, please add "Enter Apt/Villa No, Building Name, Street No. and Area"

**Comment by ZarshaB** [comment]
9>> **Re-opened**
Please add this text in email.
![image](https://user-images.githubusercontent.com/35685146/48629313-16893300-e9db-11e8-9337-f19992689a3b.png)

And Remove these highlighted lines.
![image](https://user-images.githubusercontent.com/35685146/48629349-315ba780-e9db-11e8-80f0-2146957bc223.png)
![image](https://user-images.githubusercontent.com/35685146/48629360-3a4c7900-e9db-11e8-9b5e-8080c8fff8da.png)

**Comment by asifjans** [comment]
5) Fixed

**Comment by asifjans** [comment]
6)

**Comment by asifjans** [comment]
5) Fixed :)

**Comment by Anum444** [comment]
10 Fixed...

**Comment by Anum444** [comment]
9 Fixed

**Comment by Anum444** [comment]
8 fixed

**Comment by ZarshaB** [comment]
10>> It is taking 60 AED more in total Amount Paid in Account Management. Everything else is okay for it.

**Comment by ZarshaB** [comment]
9>> Bottom lines of email has to be removed.

**Comment by ZarshaB** [comment]
13>> When ticket purchased through COD, the payment method mentioned in customer profile and admin should be COD instead of e-payment.

**Comment by asifjans** [comment]
4>> **View cars sorting**
Doesn't work. I changed status of car from serial 1 to serial 34 and serial 8 but it moved only to third position. It sould work in such a wy that View Cars landing page sorted from Ticket Price High to Low by default. But when admin changes the serial of any specific car, it should bypass this check and should go to the end.

**[Fixed, I have  tested it with diffrent flows its working fine. please check it and confirm]**

**Comment by asifjans** [comment]
8>> COD Report:
In downloaded report and in admin portal, the total paid is being reflected without including delivery charges. It should be total of both columns but only in this report. The total sales report should be without COD.
**[Fixed]**

**Comment by ZarshaB** [comment]
8>> **Reopened:**
It is not including COD Fee in reports and also COD fee column is not there in reports. 
![image](https://user-images.githubusercontent.com/35685146/48696473-d8bb2300-ec03-11e8-9619-7c7a941bc470.png)
![image](https://user-images.githubusercontent.com/35685146/48696550-04d6a400-ec04-11e8-81dc-74a9dc82972e.png)

**Comment by asifjans** [comment]
12) Fixed
8) Fixed

**Comment by ZarshaB** [comment]
12>> **Re-opened:**
**Account Management:**
last activity>> Time is displayed in reports whereas it is not in Account Management page.

**Winner** 
 Draw Date >> Rename

**Shipping Order:**
Total Amount >> Add column , Total Paid >> Rename
Total Purchase >> Remove

**Comment by asifjans** [comment]
**following issues fixed**
12>> Re-opened:
Account Management:
last activity>> Time is displayed in reports whereas it is not in Account Management page.

Winner
Draw Date >> Rename

Shipping Order:
Total Amount >> Add column , Total Paid >> Rename
