### ISSUE TITLE
COD Issues 27-11-2018

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#319]

**Comment by ZarshaB** [comment]
1>> Please correct the spelling of "generate".
![image](https://user-images.githubusercontent.com/35685146/49066909-55718100-f244-11e8-84d5-76febe70c3f0.png)

**Comment by ZarshaB** [comment]
2>> Total Amount of both COD and Reports is different.
![image](https://user-images.githubusercontent.com/35685146/49066979-85b91f80-f244-11e8-9c31-629265a3e9f8.png)
![image](https://user-images.githubusercontent.com/35685146/49066994-91a4e180-f244-11e8-9039-27bef072801b.png)

**Comment by ZarshaB** [comment]
3>> Payment Method should be COD for tickets bought via COD.
![image](https://user-images.githubusercontent.com/35685146/49067260-67075880-f245-11e8-8c28-7c3670c85a3f.png)

**Comment by asifjans** [comment]
1,2&3 **[Fixed]**
