### ISSUE TITLE
UI - Home

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#32]

**Comment by ZarshaB** [comment]
WelaDela logo does not have effect. Home should not be in menu. Extra spacing is there in logo.

![image](https://user-images.githubusercontent.com/35685146/35217233-3f154b5e-ff8c-11e7-8a42-d71769301368.png)
![image](https://user-images.githubusercontent.com/35685146/35217237-479eee38-ff8c-11e7-9b3e-ccaa5758d77f.png)

**Comment by ZarshaB** [comment]
Footer should have facebook, instagram and youtube links. And credit card brands should include Visa, MasterCard, AMEX , Central Bank , UNB Account andADCB Account.
![image](https://user-images.githubusercontent.com/35685146/35264280-efed574e-003d-11e8-9d0f-9fe1618d38d4.png)

**Comment by shayanr262** [comment]
On WelaDela logo background reflection is missing.
![logo](https://user-images.githubusercontent.com/35724117/35269261-54b8e936-004d-11e8-80f1-8a1eeb629504.PNG)

**Comment by ZarshaB** [comment]
2) In Footer everything should be in centre and in one line.
And also Footer color "green" is also change.
![image](https://user-images.githubusercontent.com/35685146/35284151-de056bb4-007b-11e8-8e9e-b638f0e52ff3.png)

**Comment by ZarshaB** [comment]
3) Fixed.

**Comment by asifjans** [comment]
4. @Anum444  Please also check Zindex issue , if user is logged in.

**Comment by ZarshaB** [comment]
5) Cart icon should be one provided in template.
![image](https://user-images.githubusercontent.com/35685146/35328265-9a1dc5ac-011d-11e8-9f5b-7eb176b1f812.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35328287-a9136d50-011d-11e8-8a72-aeedee5fd8f6.png)

**Comment by ZarshaB** [comment]
6) Cart should turn green on Hover instead of red.

**Comment by ZarshaB** [comment]
7) All buttons should change color on Hover. Hover color for all buttons should be same as decided.

**Comment by ZarshaB** [comment]
8) Please change the size of menu bit large and bold as it is in template.
![image](https://user-images.githubusercontent.com/35685146/35328373-ecb0402e-011d-11e8-9370-21fb8c8821d8.png)
Template:
![image](https://user-images.githubusercontent.com/35685146/35328395-fed50f82-011d-11e8-9216-e694851e24bb.png)

**Comment by ZarshaB** [comment]
9) Please remove dots and take now to the next line.
![image](https://user-images.githubusercontent.com/35685146/35328458-3d5cb674-011e-11e8-9b2d-cb317557b5f0.png)
Template:
![image](https://user-images.githubusercontent.com/35685146/35328475-4bce0c58-011e-11e8-9bcc-512e7224fbb5.png)

**Comment by ZarshaB** [comment]
10) Separator is not same as provided in template.
![image](https://user-images.githubusercontent.com/35685146/35328788-5b480f52-011f-11e8-88ae-139f7f243520.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35328796-62f1cb44-011f-11e8-8ab0-35637c1b3da3.png)

**Comment by ZarshaB** [comment]
11) Buttons should be filled for active and other one should be white with colored text and border as shown in template.
![image](https://user-images.githubusercontent.com/35685146/35328856-8f6c9c30-011f-11e8-877b-81696e5f4082.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35328870-97b72b6c-011f-11e8-8528-a94ce454298f.png)

**Comment by ZarshaB** [comment]
12) Sequence is not correct as provided by template:
![image](https://user-images.githubusercontent.com/35685146/35328960-e9bc39de-011f-11e8-99ce-6aacdfa19d32.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35328975-f487048e-011f-11e8-9d90-0677e5129c85.png)

**Comment by ZarshaB** [comment]
13) Buttons text should be bold.

**Comment by ZarshaB** [comment]
14) Testimonials is a slider. And content is not the one provided. And image should not be clickable.
![image](https://user-images.githubusercontent.com/35685146/35329091-628a6962-0120-11e8-883f-4d70e00d6685.png)
![image](https://user-images.githubusercontent.com/35685146/35329135-89af7294-0120-11e8-94fb-cecc3acc509c.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35329111-76f3acce-0120-11e8-9f14-88f49cfd70a4.png)

**Comment by ZarshaB** [comment]
15) Download our app portion is missing.
![image](https://user-images.githubusercontent.com/35685146/35330291-ce720d84-0124-11e8-8ffe-59b5a31b4ac3.png)

**Comment by ZarshaB** [comment]
16) The arrow color is changed.
![image](https://user-images.githubusercontent.com/35685146/35330303-e084f338-0124-11e8-8b32-c8a7b39ffddc.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35330309-e80a15de-0124-11e8-987b-0ce6b2029a6d.png)

**Comment by ZarshaB** [comment]
17) Please make the Headings bold.
![image](https://user-images.githubusercontent.com/35685146/35330346-0eba5dc4-0125-11e8-96cd-ad21839c4378.png)
Template:
![image](https://user-images.githubusercontent.com/35685146/35330356-16258994-0125-11e8-86cb-61a01278a1db.png)

**Comment by ZarshaB** [comment]
18) Text color(Black) is changed. Text is not bold. Button text is not bold. 
![image](https://user-images.githubusercontent.com/35685146/35330507-897457ae-0125-11e8-9196-2401d36ed2d7.png)

**Comment by ZarshaB** [comment]
19) Please change label of icons as "Add to Favourites" and "Watch".
![image](https://user-images.githubusercontent.com/35685146/35330631-02b75c7e-0126-11e8-9d62-978b26182b54.png)

**Comment by ZarshaB** [comment]
20) Change the loader that appears on clicking on "Watch".

**Comment by ZarshaB** [comment]
21) No action is taken on clicking on heart icon.

**Comment by ZarshaB** [comment]
22) Please refer to pop up issues to "View Cars" page.

**Comment by ZarshaB** [comment]
23) Please make "Place your ad" button and all "Learn More" buttons of Home page aligned.
![image](https://user-images.githubusercontent.com/35685146/35335515-a476ad60-0137-11e8-8f89-07f4bd399b6f.png)

**Comment by ZarshaB** [comment]
24) Please make all boxes aligned of all three headings .
![image](https://user-images.githubusercontent.com/35685146/35335576-c8222730-0137-11e8-98ea-5e96d5e769ac.png)

**Comment by ZarshaB** [comment]
25) Please make all buttons of this shape.
![image](https://user-images.githubusercontent.com/35685146/35335732-2e3be1c8-0138-11e8-8369-ec42516ec1da.png)

**Comment by ZarshaB** [comment]
26) Please change "Place your ad" button to this:
![image](https://user-images.githubusercontent.com/35685146/35335790-4ee6c6ea-0138-11e8-8228-258651891d2d.png)

That is unfilled and on hover should change color to Orange.

**Comment by ZarshaB** [comment]
27) Please make fav icon without background and transparent.
![image](https://user-images.githubusercontent.com/35685146/35335844-7307f026-0138-11e8-8ec7-96643fe08517.png)

**Comment by ZarshaB** [comment]
29) Left alignment should follow "Place your ad" button.
![image](https://user-images.githubusercontent.com/35685146/35335934-c39ee508-0138-11e8-8a77-9dc5727f3aa8.png)

**Comment by ZarshaB** [comment]
30) Please remove this from footer and instead of these write "Powered by Inovedia". Where make "Inovedia hyperlinked to "Inovedia" site. And "Powered by Inovedia" should be of same font as "Follow Us"
![image](https://user-images.githubusercontent.com/35685146/35336089-16bc42f8-0139-11e8-9c1f-de3f2e8e7358.png)

**Comment by ZarshaB** [comment]
31) Make side arrows for "Our Featured Cars" section.
![image](https://user-images.githubusercontent.com/35685146/35338624-3756fbdc-0140-11e8-806f-8c8d16ceaf63.png)

**Comment by ZarshaB** [comment]
32) Button text is not centre aligned.
![image](https://user-images.githubusercontent.com/35685146/35338696-66c46a8a-0140-11e8-9378-8489c7f70bab.png)

**Comment by ZarshaB** [comment]
33) Text of button should be small.
![image](https://user-images.githubusercontent.com/35685146/35338723-7c242974-0140-11e8-8d26-40b2b8af4b02.png)

**Comment by ZarshaB** [comment]
34) Images are stretched.
![image](https://user-images.githubusercontent.com/35685146/35338756-92cf0c20-0140-11e8-9efa-964611cfe38f.png)

**Comment by ZarshaB** [comment]
35) This should not be visible.
![image](https://user-images.githubusercontent.com/35685146/35338805-aeb9aff8-0140-11e8-9b15-2961382c1b98.png)

**Comment by ZarshaB** [comment]
36) Please change icons labels and should redirect to correct pages.
![image](https://user-images.githubusercontent.com/35685146/35338870-d4697e54-0140-11e8-98d9-f3abf9682895.png)

**Comment by ZarshaB** [comment]
37) Please make this whole static. 
![image](https://user-images.githubusercontent.com/35685146/35340178-40dea782-0144-11e8-9580-28749337806d.png)

**Comment by ZarshaB** [comment]
38) It should be aligned.
![image](https://user-images.githubusercontent.com/35685146/35340276-7cf8a830-0144-11e8-9821-6125b4bfe9ab.png)

**Comment by ZarshaB** [comment]
39) Home page loads as first "Our Featured Cars" appears and then whole page loads. It should not be like this.

**Comment by ZarshaB** [comment]
40) On clicking on "Learn More" it should redirect to "View Cars" page.
![image](https://user-images.githubusercontent.com/35685146/35377356-a5e6d078-01d0-11e8-8b20-d97747ceccfe.png)

**Comment by ZarshaB** [comment]
41) Image is not same as the image in the template.
![image](https://user-images.githubusercontent.com/35685146/35377507-46490734-01d1-11e8-9324-f2dab6849981.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35377520-51f646d2-01d1-11e8-9219-cbd4fbef53b0.png)

**Comment by ZarshaB** [comment]
42) The first image that appears is not the one required which is "That thing in your back view mirror". 
Whereas here the first image that appears is " A transparent process..".

**Comment by ZarshaB** [comment]
43) Please make it "Instagram" .
![image](https://user-images.githubusercontent.com/35685146/35380425-04900d74-01db-11e8-8d9d-2b200bf3d71d.png)

**Comment by ZarshaB** [comment]
44) Please write full stop here.
![image](https://user-images.githubusercontent.com/35685146/35380965-97727644-01dc-11e8-8a9a-9faafa0c3eaa.png)

**Comment by ZarshaB** [comment]
45) Please make it's content the one in template.
![image](https://user-images.githubusercontent.com/35685146/35381201-4beded88-01dd-11e8-944a-13b83ff42aee.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35381211-57576eb0-01dd-11e8-8246-e0869a3d88e5.png)

**Comment by ZarshaB** [comment]
40) Please make it to new line.
![image](https://user-images.githubusercontent.com/35685146/35395617-ad323d54-020c-11e8-94a4-2d973298bbfd.png)

**Comment by ZarshaB** [comment]
This should also be capital.
![image](https://user-images.githubusercontent.com/35685146/35396767-6af86244-020f-11e8-9324-2683415b28c8.png)

**Comment by ZarshaB** [comment]
42) Please make it "Powered".
![image](https://user-images.githubusercontent.com/35685146/35396842-9feb8f94-020f-11e8-8f6a-c223a6927d89.png)

**Comment by ZarshaB** [comment]
43) Please make "Inovedia" logo small and make "w" of "Weladela.com" small.
![image](https://user-images.githubusercontent.com/35685146/35429807-6d8a4fda-0297-11e8-8152-95c8404ed3df.png)

**Comment by ZarshaB** [comment]
44) Please make both Seller and Buyer buttons' text bold.
![image](https://user-images.githubusercontent.com/35685146/35431992-78766d76-02a0-11e8-922f-76877c913a8d.png)

**Comment by ZarshaB** [comment]
45) Please make "Learn More" button and text small.
![image](https://user-images.githubusercontent.com/35685146/35432016-89e1be08-02a0-11e8-9017-5297c34b18d1.png)

**Comment by ZarshaB** [comment]
46) On Login, header's alignment changes. And also "How it works" and "View Cars" options clickable area changes.
![image](https://user-images.githubusercontent.com/35685146/35436465-5f2de852-02b0-11e8-8d86-2e36b811dc80.png)

**Comment by ZarshaB** [comment]
47) Fav icon is stretched. Please make it normal.
![image](https://user-images.githubusercontent.com/35685146/35440857-12848d86-02c3-11e8-9b51-6d9b1c2a7cfd.png)

**Comment by ZahidRavian** [comment]
These issues are fixed
1,2,3,5,6,7,8,9,10,12,13,14,15,16,17,18,19,20,21,23,24,25,26,28,29,30,32,33,34,35,36,37,38,39,40,41,42,43,44,45

**Comment by ZarshaB** [comment]
14) There should not be side arrows for "Testimonials". And also slider icon is not correct.
![image](https://user-images.githubusercontent.com/35685146/35505323-9a5ba794-0507-11e8-8b86-20b937c7ea62.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35505339-a4fac34c-0507-11e8-8b13-b09a68e0e1ef.png)

**Comment by ZarshaB** [comment]
15) Download our App portion's size is very large. Please reduce it's size.
![image](https://user-images.githubusercontent.com/35685146/35505898-59fa6800-0509-11e8-8f71-5b96a99002c9.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35505907-65938020-0509-11e8-8230-9e1d1fee376c.png)

**Comment by ZarshaB** [comment]
32) Seller text of button should be a little left aligned.
![image](https://user-images.githubusercontent.com/35685146/35505974-a00bd2ac-0509-11e8-9dde-5d43df5a6b22.png)

**Comment by ZarshaB** [comment]
39) Not fixed.

**Comment by ZarshaB** [comment]
48) Please make "w" capital for "Watch".
![image](https://user-images.githubusercontent.com/35685146/35506206-5995ce62-050a-11e8-8876-394954e1f5e3.png)

**Comment by ZarshaB** [comment]
49) Please align login/Register and Cart button on home page to a little right.

**Comment by ZarshaB** [comment]
49) Please make all buttons' text to be in centre from all four sides i.e. up, down, left and right.

**Comment by ZarshaB** [comment]
50) Slider's image is not complete. This space should not appear.
![image](https://user-images.githubusercontent.com/35685146/35507426-8ce6178c-050e-11e8-94b8-b49303ec0943.png)

**Comment by ZarshaB** [comment]
51) Green color of both button on hover and cart are not same.
![image](https://user-images.githubusercontent.com/35685146/35507493-c3be3a46-050e-11e8-8d0e-37d7fb008c64.png)
![image](https://user-images.githubusercontent.com/35685146/35507504-cf9deda2-050e-11e8-94e5-816de054ad93.png)

**Comment by ZarshaB** [comment]
52) These icons are appearing blurry. And also the present state of icons should appear on hover.
By default it the whole icon and outline should be white with blurry green background.
![image](https://user-images.githubusercontent.com/35685146/35507626-3450b694-050f-11e8-9efe-b32818d9b7f9.png)

**Comment by ZarshaB** [comment]
53) No screen should be scrollable.
![image](https://user-images.githubusercontent.com/35685146/35507712-81a17dca-050f-11e8-9c86-301248070dab.png)

**Comment by ZarshaB** [comment]
55) Make it center aligned.
![image](https://user-images.githubusercontent.com/35685146/35508860-c4f06b28-0513-11e8-8666-8d5062390664.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35508866-cf632bcc-0513-11e8-9403-b2dc296b872d.png)

**Comment by ZarshaB** [comment]
56) This whole section including images and text are blurry.
![image](https://user-images.githubusercontent.com/35685146/35508885-e289ea88-0513-11e8-8b42-e8c331b82809.png)

**Comment by ZarshaB** [comment]
57) Active button should be bold and filled. Other button should remain semi bold and unfilled.
![image](https://user-images.githubusercontent.com/35685146/35508957-30f7738e-0514-11e8-8109-ca7b9d88c17d.png)

**Comment by ZarshaB** [comment]
58) All images under "Our Featured Cars" section should completely fill the box.
![image](https://user-images.githubusercontent.com/35685146/35509036-78135eb8-0514-11e8-9c26-3c78400a576c.png)

**Comment by ZarshaB** [comment]
59) No search box.
![image](https://user-images.githubusercontent.com/35685146/35509535-477e8906-0516-11e8-9d22-6f98a045f44e.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35509541-54d90c8e-0516-11e8-8e6d-b18de3b97879.png)

**Comment by ZarshaB** [comment]
60) It should not be a link or clickable.
![image](https://user-images.githubusercontent.com/35685146/35513323-78b708b4-0524-11e8-824d-c1f793721d75.png)

**Comment by ZarshaB** [comment]
61) Testimonials slider should move itself.
![image](https://user-images.githubusercontent.com/35685146/35561417-1351dc34-05d2-11e8-950f-360fdc064f5b.png)

**Comment by ZarshaB** [comment]
62) Days are missing in timer as it is on View cars page.
![image](https://user-images.githubusercontent.com/35685146/35562237-963ebe12-05d4-11e8-85c1-afc074ed1dd0.png)

**Comment by ZarshaB** [comment]
63) Timer showing time to zero.
![image](https://user-images.githubusercontent.com/35685146/35562266-ab894eae-05d4-11e8-8ada-6a1a089912cf.png)

**Comment by ZarshaB** [comment]
64) Please set the alignment of Footer.
![image](https://user-images.githubusercontent.com/35685146/35562304-c5f133f6-05d4-11e8-8a6c-24571e2c4bc7.png)

**Comment by ZarshaB** [comment]
39) Taking user to "Our Featured Cars" section but if screen is zoom out then it does not take to that section.

**Comment by ZarshaB** [comment]
40) Header jerks.

**Comment by ZarshaB** [comment]
41) Same ad is appearing for whole section of "Our Featured Cars".
![image](https://user-images.githubusercontent.com/35685146/35616481-2a975da4-0697-11e8-9fee-6081dab6c241.png)

**Comment by ZarshaB** [comment]
42) Please ad other content for this. 
![image](https://user-images.githubusercontent.com/35685146/35616548-5d4aacba-0697-11e8-829d-056aea7aea2a.png)

**Comment by ZarshaB** [comment]
43) Please make the movement of text of slider very subtle. Instead of making it jump and bounce around, lets keep it simple.

**Comment by ZarshaB** [comment]
44) Please minimize the timer block size by at least 20%.

**Comment by ZarshaB** [comment]
45) The quick view button is getting hidden if the picture background is is dark.

**Comment by ZarshaB** [comment]
46) The slider is missing outline from one side and it's drop down does not appear complete.
![image](https://user-images.githubusercontent.com/35685146/35669211-2710e71c-0756-11e8-8d60-799a76e688ad.png)

**Comment by ZarshaB** [comment]
47) Black Color outline is different than template.
![image](https://user-images.githubusercontent.com/35685146/35669426-e5ef5592-0756-11e8-9bd3-959c016de0aa.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35669435-f047ba0c-0756-11e8-81d0-c665297eea6b.png)

**Comment by ZarshaB** [comment]
48) Only two ads are displaying. Side arrows are not working. 
![image](https://user-images.githubusercontent.com/35685146/35669569-5041170a-0757-11e8-9682-b9c6be91064c.png)

**Comment by ZarshaB** [comment]
49) Search filter is not working. As if I select AED 50 from drop down. Then it also shows me ad with AED 20.

**Comment by ZarshaB** [comment]
Not Fixed = 22,52,55,57,61,64,39,40,42,43,44,45,46,47,48,49
Functional = 57,61,39,40,43,46,48,49

**Comment by ZarshaB** [comment]
49) On taking cursor to it it shows whole name, so if name is large then it should not show complete name.
![image](https://user-images.githubusercontent.com/35685146/35674032-2d1d0726-0765-11e8-832d-62dd3f7c9e04.png)

**Comment by asifjans** [comment]
42 (fixed)
