### ISSUE TITLE
COD Purchase

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#321]
if user buy a ticket using COD, reward points are not in customer balance.

**Comment by ZarshaB** [comment]
It is displaying points in table but not on button.
![image](https://user-images.githubusercontent.com/35685146/49282420-f795a100-f4b0-11e8-8e32-97fb01acd2af.png)

**Comment by ZarshaB** [comment]
And when I go to purchase any ticket then although it has 25 reward points( gained by COD) but on cart it is displaying zero reward points.
![image](https://user-images.githubusercontent.com/35685146/49283483-af2bb280-f4b3-11e8-9087-863372d0f9f3.png)
![image](https://user-images.githubusercontent.com/35685146/49283515-bfdc2880-f4b3-11e8-8deb-fc8b0bfd71d1.png)
