### ISSUE TITLE
New Banner Image

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#322]

**Comment by ZarshaB** [comment]
I'm attaching new banner image. Can you please replace the old banner that has my image in it with this new banner.

**Comment by ZarshaB** [comment]
![thumbnail_slider 1](https://user-images.githubusercontent.com/35685146/49276817-63700d80-f4a1-11e8-8534-b4a8e74e696f.png)

**Comment by Anum444** [comment]
**FIXED**
I'm attaching new banner image. Can you please replace the old banner that has my image in it with this new banner
