### ISSUE TITLE
Promo Code Deletion Error.

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#323]

**Comment by ZarshaB** [comment]
When I delete promo code then it redirects to error page.
![image](https://user-images.githubusercontent.com/35685146/49280679-9c61af80-f4ac-11e8-8431-c121d2496ab9.png)

![image](https://user-images.githubusercontent.com/35685146/49280662-923fb100-f4ac-11e8-81d4-7769bb110fb6.png)

**Comment by Anum444** [comment]
**RFR**
When I delete promo code then it redirects to error page.
