### ISSUE TITLE
Generate Ticket UI

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#327]

**Comment by ZarshaB** [comment]
1>> Please make Ooops/Holaaa in Center.
![image](https://user-images.githubusercontent.com/35685146/49722128-c7ef5180-fc85-11e8-970f-76933e0740d4.png)

**Comment by ZarshaB** [comment]
**Suggestion**
2>> It should not display me this message if empty form is submitted. It should display this message if whole form is submitted without filling email or mobile number any of these fields.
![image](https://user-images.githubusercontent.com/35685146/49519108-0f5e9200-f8c2-11e8-9031-c7762c55dbd0.png)

**Comment by Anum444** [comment]
**FIXED**
2>> It should not display me this message if empty form is submitted. It should display this message if whole form is submitted without filling email or mobile number any of these fields.

**Comment by Anum444** [comment]
**FIXED**
1>> Please make Ooops/Holaaa in Center.
