### ISSUE TITLE
Genrate ticket flow

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#329]
@ZarshaB 
@Anum444 

complete test genrate ticket with all possible flow. as its done upload latest code on demoadmin

Today try close all issues those are written in GitHub. so that from tomorrow we can start work on 

New Home page

**Comment by ZarshaB** [comment]
okay sir

**Comment by Anum444** [comment]
Okay Sir...

**Comment by asifjans** [comment]
@ZarshaB Please close and remove which issues are fixed.

**Comment by ZarshaB** [comment]
I have closed and removed fixed issues.
