### ISSUE TITLE
Rewards Managment

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#331]
1) in grid of reward also show Mobile number of customer
2)  also add option of search by Mobile number
3) also add this Mobile number in exported excel file.

**Comment by asifjans** [comment]
4) demoadmin.weladela.com/ManualGenerateTicket

Change position of  Mobile number and Email,  sequence will be
Mobile Number,Email, First Name, Last Name and so on...

**Comment by asifjans** [comment]
@Anum444 
4) demoadmin.weladela.com/ManualGenerateTicket

a) Change position of  Mobile number and Email,  sequence will be
Mobile Number,Email, First Name, Last Name and so on...

b) in mobile number append country code as we have done on Register page.

**Comment by sammiullah** [comment]
**RFR**

1.in grid of reward also show Mobile number of customer
2.also add option of search by Mobile number
3.also add this Mobile number in exported excel file.

**Comment by Anum444** [comment]
**RFR**
4) demoadmin.weladela.com/ManualGenerateTicket

a) Change position of Mobile number and Email, sequence will be
Mobile Number,Email, First Name, Last Name and so on...

b) in mobile number append country code as we have done on Register page.
