### ISSUE TITLE
Generate Ticket 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#334]

**Comment by ZarshaB** [comment]
1>> The account I created with Mobile number and didn't give email address. When I purchase ticket from this account and transfer it then it keeps on loading that page and on Ticket management it displays ticket has been transferred,

**Comment by ZarshaB** [comment]
2>> Same is the case with Refund Ticket.

**Comment by ZarshaB** [comment]
3>> And also when I make this account ticket winner. 
![image](https://user-images.githubusercontent.com/35685146/49928154-5a3f6180-fee1-11e8-88c7-85d3df821326.png)

**Comment by Anum444** [comment]
**FIXED**

1>> The account I created with Mobile number and didn't give email address. When I purchase ticket from this account and transfer it then it keeps on loading that page and on Ticket management it displays ticket has been transferred,
2>> Same is the case with Refund Ticket.
3>> And also when I make this account ticket winner.
