### ISSUE TITLE
Contact Us New Design 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#345]

**Comment by ZarshaB** [comment]
https://projects.invisionapp.com/share/UVPP6CP2EWB#/screens

**Comment by ZarshaB** [comment]
1>> Contact Us should be highlighted instead of Home from menu bar.
![image](https://user-images.githubusercontent.com/35685146/52327614-8ae9d600-2a0e-11e9-90c9-7c78d06fc5bc.png)

**Comment by ZarshaB** [comment]
2>> There are no icons and also time is not mentioned.
![image](https://user-images.githubusercontent.com/35685146/52327654-ae148580-2a0e-11e9-859b-b83284e84195.png)


**Reference:**
![image](https://user-images.githubusercontent.com/35685146/52327668-ba98de00-2a0e-11e9-8447-0b505437b95a.png)

**Comment by ZarshaB** [comment]
3>> There should be space between word and question mark.
![image](https://user-images.githubusercontent.com/35685146/52327696-cf757180-2a0e-11e9-8b7a-26775e20f272.png)

**Comment by ZarshaB** [comment]
4>> "please select city" font size should be same as other place holder font size.
![image](https://user-images.githubusercontent.com/35685146/52327833-47dc3280-2a0f-11e9-9aea-12dbcf5cd128.png)

**Comment by ZarshaB** [comment]
5>> Selected City font color is not same as other field's values.
![image](https://user-images.githubusercontent.com/35685146/52327913-9be71700-2a0f-11e9-9860-64141fe5072b.png)

**Comment by ZarshaB** [comment]
6>> After submitting form it redirects me to old site page.
![image](https://user-images.githubusercontent.com/35685146/52327966-d2249680-2a0f-11e9-973c-e1c118aa3fad.png)

**Comment by Anum444** [comment]
**RFR**

2>> There are no icons and also time is not mentioned.
3>> There should be space between word and question mark.
4>> "please select city" font size should be same as other place holder font size.
5>> Selected City font color is not same as other field's values.

**Comment by Anum444** [comment]
**RFR**
9>> View Cars should be underlined.

**Comment by ZarshaB** [comment]
2>> Now it is having icons but can you please make center icon in center.
![image](https://user-images.githubusercontent.com/35685146/53019952-bdb4b500-3477-11e9-90ae-55e88408305e.png)
