### ISSUE TITLE
UI - Order Sumary/ Cart

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#35]

**Comment by ZarshaB** [comment]
1) All names should be bold and center aligned.
![image](https://user-images.githubusercontent.com/35685146/35339482-8f7583cc-0142-11e8-9ed2-6f2c27039498.png)

**Comment by ZarshaB** [comment]
2) Redeem points should only be available if user has points in his account otherwise it should be deactivate.
![image](https://user-images.githubusercontent.com/35685146/35339597-cd37c85a-0142-11e8-87f3-7a5acfe36e52.png)

**Comment by ZarshaB** [comment]
3) Button is not working.
![image](https://user-images.githubusercontent.com/35685146/35339684-0b30125c-0143-11e8-9d98-1c3fdfca1395.png)

**Comment by ZarshaB** [comment]
4) Button's color should not change to blue.
![image](https://user-images.githubusercontent.com/35685146/35339735-2999d854-0143-11e8-9f90-e8a0e8ae3f33.png)

**Comment by ZarshaB** [comment]
5) Image also should not be hyperlinked.
![image](https://user-images.githubusercontent.com/35685146/35339778-449ff3cc-0143-11e8-87ec-da3a6dcf5314.png)

**Comment by ZarshaB** [comment]
6) It should not Proceed to checkout unless billing address is not provided.

**Comment by ZarshaB** [comment]
7) On clciking on "Continue to Shopping" it should redirect to "View Cars" page.

**Comment by ZarshaB** [comment]
8) It should ask for login/Register without proceeding to checkout.

**Comment by ZarshaB** [comment]
9) Please insert plus and minus sign here.
![image](https://user-images.githubusercontent.com/35685146/35430418-f9910288-0299-11e8-9ba3-8bb870ec82cb.png)

**Comment by ZarshaB** [comment]
10) Please remove this.
![image](https://user-images.githubusercontent.com/35685146/35430439-0ddc8870-029a-11e8-90b3-ea371cc5e8d7.png)
Please make "Apply Reward points" button here:
![image](https://user-images.githubusercontent.com/35685146/35430501-57aeeb64-029a-11e8-8e89-b25216cd474d.png)
This button should be activate when user's reward points reaches to 1000.

**Comment by ZarshaB** [comment]
11) This should be displayed at bottom of page with checkbox.
By clicking on Proceed to checkout, I agree to the following: - 

•	In case of winning the draw, I’ll have the car transferred in my name within 7 days of the draw.
•	Weladela does not guarantee anything about the car and it will be subject to passing of fitness test by Government of UAE.
•	In case of any unsuccessful draw due to any unforeseen reason, Weladela.com reserves the right to transfer this ticket to another draw for the car with similar market value.

I hereby also acknowledge that I have read, understood and agreed to all other terms and conditions(hyperlink) and will adhere to them unconditionally.

**Comment by ZahidRavian** [comment]
These issues are fixed.
1, 4, 5, 9, 10, 11

**Comment by ZarshaB** [comment]
5) These are not hyperlinked now. But it should also not be clickable.

**Comment by ZarshaB** [comment]
10) Not fixed.

**Comment by ZarshaB** [comment]
11) Please make these changes in text.
![image](https://user-images.githubusercontent.com/35685146/35503171-2fee8742-0501-11e8-9461-d6014310f793.png)

**Comment by ZarshaB** [comment]
12) Only first item's plus , minus are working but if second item is added then it's plus , minus dies not work.
![image](https://user-images.githubusercontent.com/35685146/35509706-ffa0f64a-0516-11e8-8470-4266603768bb.png)

**Comment by ZarshaB** [comment]
13) If I add item in cart and then go to Login/Register page, then cart becomes empty. Also if I add item after login and then after logout when I again login then again cart becomes empty.
Items should be there in cart until I delete them.

**Comment by ZarshaB** [comment]
14) On clicking on "Remove", it's color changes to red.
![image](https://user-images.githubusercontent.com/35685146/35514210-436da412-0527-11e8-8662-60d67627cfbc.png)

**Comment by ZarshaB** [comment]
![image](https://user-images.githubusercontent.com/35685146/35514432-f4206c40-0527-11e8-995a-6c32472a5ca8.png)

**Comment by asifjans** [comment]
3, 5, 6, 7, 8, 12, 13 (Fixed)

**Comment by ZahidRavian** [comment]
These issues are fixed. Please check and remove them from github
3, 5, 6, 7, 8,  10, 11, 12, 13

**Comment by ZarshaB** [comment]
15) Please make it's validation same as we are using for all other pages. 
![image](https://user-images.githubusercontent.com/35685146/35576292-6e75c0a2-0600-11e8-8879-350fbec96362.png)

**Comment by ZarshaB** [comment]
16) Button should be disabled if user does not have reward points.

![image](https://user-images.githubusercontent.com/35685146/35576440-ca57cbfe-0600-11e8-8019-f0d635ef48f2.png)

**Comment by ZarshaB** [comment]
18) Please make it City.
![image](https://user-images.githubusercontent.com/35685146/35618706-900659aa-069d-11e8-9a5b-0bc70c55f388.png)

**Comment by ZarshaB** [comment]
19) Heading is not correct.
![image](https://user-images.githubusercontent.com/35685146/35621668-05917b10-06a7-11e8-9f4e-f7f696407783.png)

**Comment by ZarshaB** [comment]
20) Remove button turns to red on clicking on it.
![image](https://user-images.githubusercontent.com/35685146/35677280-caefcffa-0770-11e8-8552-ea50bac2a4e4.png)

**Comment by ZarshaB** [comment]
Functional Issue = 16
Not Fixed = 15,16,18,19,20

**Comment by asifjans** [comment]
15, 18, 20 (Fixed)
