### ISSUE TITLE
Results Page - New Design 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#350]

**Comment by ZarshaB** [comment]
1>> For Results page it is displaying old design page.
![image](https://user-images.githubusercontent.com/35685146/52331882-12d5dd00-2a1b-11e9-8bfa-80a44706dd8f.png)

**Comment by Anum444** [comment]
**RFR**
1>> For Results page it is displaying old design page.

**Comment by ZarshaB** [comment]
2>> Please make No Results found page similar to View Cars page.
![image](https://user-images.githubusercontent.com/35685146/53088956-0a0dfc80-352d-11e9-8973-13ac5b2467af.png)

**Comment by Anum444** [comment]
2>> Please make No Results found page similar to View Cars page.

**Comment by ZarshaB** [comment]
1>> It is cut from above and also dates are overlapping with line.
![image](https://user-images.githubusercontent.com/35685146/53094773-e8b50c80-353c-11e9-9133-31c69efbee76.png)

**Comment by Anum444** [comment]
1>> It is cut from above and also dates are overlapping with line.

**Comment by Anum444** [comment]
**RFR**
1>> It is cut from above and also dates are overlapping with line.
