### ISSUE TITLE
Login Page - New Design

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#351]

**Comment by ZarshaB** [comment]
1>> All headings of this page should have same font size. As we are following 16px font size so it should be 16px.
![image](https://user-images.githubusercontent.com/35685146/52332040-6f38fc80-2a1b-11e9-981e-9eb54e44d50d.png)

**Comment by ZarshaB** [comment]
2>> Facebook button is not at right place and also it should be changed.
![image](https://user-images.githubusercontent.com/35685146/52332957-d192fc80-2a1d-11e9-9bba-64de22d362d5.png)

**Comment by ZarshaB** [comment]
3>> After logout it redirects to this page.
![image](https://user-images.githubusercontent.com/35685146/52352786-15eac080-2a4f-11e9-8dae-1d86e8377d5c.png)

**Comment by ZarshaB** [comment]
3>> Can you please align all these error messages at center with text and spacing?
![image](https://user-images.githubusercontent.com/35685146/52721893-6d97a780-2fcc-11e9-8e30-b4ba5bd1f668.png)

**Comment by sammiullah** [comment]
1>> New Customer and Returning Customer  heading should be little small in size.
![image](https://user-images.githubusercontent.com/35685146/52332040-6f38fc80-2a1b-11e9-981e-9eb54e44d50d.png)


We haven't changed the font of any heading, kindly don't assume thing, Please make sure Usama have any negative feed back about these then log the issues.

**Comment by sammiullah** [comment]
**Dependent on FB button image**

2>> Facebook button is not at right place and also it should be changed.
![image](https://user-images.githubusercontent.com/35685146/52332957-d192fc80-2a1d-11e9-9bba-64de22d362d5.png)

**Comment by ZarshaB** [comment]
1>> I was comparing it with other pages and in contrast to them it seems quite big. 
![image](https://user-images.githubusercontent.com/35685146/52784198-1bab5c00-3076-11e9-8c77-541efeaf8dbf.png)
![image](https://user-images.githubusercontent.com/35685146/52784214-2c5bd200-3076-11e9-8e2f-4d7d4ca2a583.png)

**Comment by ZarshaB** [comment]
3>> Messages are in center but not all messages are in center.
![image](https://user-images.githubusercontent.com/35685146/52784319-88265b00-3076-11e9-8d70-36eb99fae967.png)
![image](https://user-images.githubusercontent.com/35685146/52784333-96747700-3076-11e9-8a4b-21dc71e66e4a.png)

**Comment by sammiullah** [comment]
**RFR**

**Comment by Anum444** [comment]
**RFR**
2>> Facebook button is not at right place and also it should be changed.
