### ISSUE TITLE
Welcome Icon and Menu- New Design

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#353]

**Comment by ZarshaB** [comment]
1>> Please reduce this icon in size.
![image](https://user-images.githubusercontent.com/35685146/52346955-9fe05c80-2a42-11e9-84b8-5828c0e33fdd.png)

**Comment by ZarshaB** [comment]
2>> Please make these menus smaller in size and also not bold.
![image](https://user-images.githubusercontent.com/35685146/52347001-b7b7e080-2a42-11e9-8238-374ba32d9d45.png)

**Comment by ZarshaB** [comment]
3>> Please remove this blue highlight around icon.
![image](https://user-images.githubusercontent.com/35685146/52349674-dd47e880-2a48-11e9-9969-cbf1401b8ee2.png)

**Comment by ZarshaB** [comment]
4>> When I take cursor on any of this icon it underlines that name. Whereas in old site we used to highlight name.
![image](https://user-images.githubusercontent.com/35685146/52351169-f8682780-2a4b-11e9-82ae-66c1e2a335ae.png)

**Comment by ZarshaB** [comment]
5>> It should be in one line.
![image](https://user-images.githubusercontent.com/35685146/52351221-1cc40400-2a4c-11e9-9b68-f8c9ed649f4e.png)

**Comment by ZarshaB** [comment]
6>> When I take cursor on any of this menu then it highlights the name with blue. Whereas in old site it highlights name in orange.
![image](https://user-images.githubusercontent.com/35685146/52351322-572da100-2a4c-11e9-8338-4176173907df.png)

**Comment by sammiullah** [comment]
**RFR**
