### ISSUE TITLE
My Profile - New Design

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#354]

**Comment by ZarshaB** [comment]
1>> For previous site we have Profile picture icon in circle and orange color highlighted. 
Also "Choose File" button is not in center.
![image](https://user-images.githubusercontent.com/35685146/52347090-ef268d00-2a42-11e9-8b09-c33cf7904dc4.png)

**Comment by ZarshaB** [comment]
3>> It is not displaying correct DOB and also not editable.
![image](https://user-images.githubusercontent.com/35685146/52349370-3f541e00-2a48-11e9-9e78-c0cca605f3a1.png)

**Comment by ZarshaB** [comment]
4>> There should be asterisk for required fields.
![image](https://user-images.githubusercontent.com/35685146/52349465-6b6f9f00-2a48-11e9-9e5d-400462a76e1a.png)

**Comment by ZarshaB** [comment]
5>> Code of mobile number should be in box.
![image](https://user-images.githubusercontent.com/35685146/52349502-880bd700-2a48-11e9-89b4-df0b97847470.png)

**Comment by ZarshaB** [comment]
6>> Send Amazing deals line and checkbox is missing.
![image](https://user-images.githubusercontent.com/35685146/52349547-9eb22e00-2a48-11e9-86fc-31cb17ad53b9.png)

**Comment by ZarshaB** [comment]
7>> When I click on change password it redirects me to this page.
![image](https://user-images.githubusercontent.com/35685146/52349613-c1444700-2a48-11e9-860b-3a60ecd8632a.png)

**Comment by ZarshaB** [comment]
8>> When I take cursor to Change Password then its color changes to blue.
![image](https://user-images.githubusercontent.com/35685146/52349820-226c1a80-2a49-11e9-8bb1-1c27430ba5a0.png)

**Comment by ZarshaB** [comment]
9>> Cancel and Delete buttons are not working.
![image](https://user-images.githubusercontent.com/35685146/52351756-30bc3580-2a4d-11e9-81de-2b18a4545ea3.png)

**Comment by sammiullah** [comment]
**@ZarshaB Check these with RFR tag**

**Comment by ZarshaB** [comment]
**Re-opened**
9>> Delete button is working now but Cancel button is not working.

**Comment by ZarshaB** [comment]
10>> Position of button is not okay.
![image](https://user-images.githubusercontent.com/35685146/52857981-ab223f00-314a-11e9-8576-9a5702570bad.png)

**Reference:**
![image](https://user-images.githubusercontent.com/35685146/52857991-b8d7c480-314a-11e9-8e82-7810e6b6eedb.png)

**Comment by ZarshaB** [comment]
6>> I need to test it for account which is showing this.

**Comment by Anum444** [comment]
**RFR**
3>> It is not displaying correct DOB and also not editable.

**Comment by ZarshaB** [comment]
7>> By default it is displaying this.
![image](https://user-images.githubusercontent.com/35685146/52955705-2be17500-33af-11e9-8c0e-c606b7246f0e.png)

**Comment by ZarshaB** [comment]
8>> Please make this message in center.
![image](https://user-images.githubusercontent.com/35685146/53025714-3e2ce300-3483-11e9-9716-bb74d518cb9d.png)

**Comment by Anum444** [comment]
RFR
8>> Please make these messages in center.

**Comment by ZarshaB** [comment]
**Reopened**
Still there.
8>> Please make these messages in center.
![image](https://user-images.githubusercontent.com/35685146/53025714-3e2ce300-3483-11e9-9716-bb74d518cb9d.png)
![image](https://user-images.githubusercontent.com/35685146/53025787-66b4dd00-3483-11e9-8515-3d0400730653.png)

**Comment by Anum444** [comment]
**RFR**
By default it is displaying this.

**Comment by Anum444** [comment]
**RFR**
7>> There should be asterisk for all required fields.
By default it is displaying this.
