### ISSUE TITLE
My Favorites - New Design 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#355]

**Comment by ZarshaB** [comment]
1>> There should be button.
![image](https://user-images.githubusercontent.com/35685146/52352397-50a02900-2a4e-11e9-88fb-7902e84fe994.png)

**Comment by sammiullah** [comment]
**RFR**

**Comment by ZarshaB** [comment]
1>> Fixed.

**Comment by ZarshaB** [comment]
All the menus should be highlighted when selected.
![image](https://user-images.githubusercontent.com/35685146/52700655-4c1dc800-2f9a-11e9-90a0-9b29ee4a78cd.png)

**Comment by sammiullah** [comment]
**RFR**
