### ISSUE TITLE
My Ads - New Design

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#356]

**Comment by ZarshaB** [comment]
1>> There should be button.
![image](https://user-images.githubusercontent.com/35685146/52352486-76c5c900-2a4e-11e9-8808-4abb2b58f1da.png)

**Comment by sammiullah** [comment]
**RFR**

**Comment by ZarshaB** [comment]
1>> It is now having button. But in this design "Place your Ad" is now renamed as "Submit an Ad".
![image](https://user-images.githubusercontent.com/35685146/52700763-88e9bf00-2f9a-11e9-843f-c63a8ca0e017.png)

**Comment by sammiullah** [comment]
**RFR**
