### ISSUE TITLE
Reward Points - New Design

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#357]

**Comment by ZarshaB** [comment]
1>> There should be button.
![image](https://user-images.githubusercontent.com/35685146/52352551-9eb52c80-2a4e-11e9-82e3-935e4ff0465d.png)

**Comment by ZarshaB** [comment]
2>> Its heading is missing.
![image](https://user-images.githubusercontent.com/35685146/52352580-ad9bdf00-2a4e-11e9-8b86-31b68baf523f.png)

**Comment by ZarshaB** [comment]
1>> Empty page will display the same message that it was displaying before only there should be button of "View Cars" below.
![image](https://user-images.githubusercontent.com/35685146/52701025-0f060580-2f9b-11e9-8122-29eef84606a3.png)

**Comment by sammiullah** [comment]
**RFR**

**Comment by ZarshaB** [comment]
1>> Still not fixed. For empty page instead of displaying message it is displaying table rows. It should display this message but at place of "View Cars" it should display button.
![image](https://user-images.githubusercontent.com/35685146/52784607-7c876400-3077-11e9-8931-be3199b61a8f.png)
