### ISSUE TITLE
Purchase History - New Design

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#358]

**Comment by ZarshaB** [comment]
1>> There should be button.
![image](https://user-images.githubusercontent.com/35685146/52352689-e3d95e80-2a4e-11e9-9206-a773043a11f0.png)

**Comment by sammiullah** [comment]
**RFR**

**Comment by ZarshaB** [comment]
1>> Empty page will display the same message that it was displaying before only there should be button of "View Cars" below.
![image](https://user-images.githubusercontent.com/35685146/52700911-d23a0e80-2f9a-11e9-8e86-04e2e0772906.png)

**Comment by sammiullah** [comment]
**RFR**

**Comment by ZarshaB** [comment]
1>> Still not fixed. For empty page instead of displaying message it is displaying table rows. It should display this message but at place of "View Cars" it should display button.
![image](https://user-images.githubusercontent.com/35685146/52784524-3500d800-3077-11e9-8b76-1581d18b8a14.png)

**Comment by sammiullah** [comment]
**RFR**
