### ISSUE TITLE
Forgot Password - New Design

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#359]

**Comment by ZarshaB** [comment]
1>> This page is missing "Forgot Your Password?" Heading.
![image](https://user-images.githubusercontent.com/35685146/52352928-5d714c80-2a4f-11e9-93a2-d08cac94efe9.png)

**Comment by ZarshaB** [comment]
2>> This message should be in middle of these two lines.
![image](https://user-images.githubusercontent.com/35685146/52353004-7da10b80-2a4f-11e9-93d5-7be06558ee42.png)

**Comment by ZarshaB** [comment]
3>> Reset password link of email is redirecting to old site reset password page.
![image](https://user-images.githubusercontent.com/35685146/52353066-a3c6ab80-2a4f-11e9-9053-975b6f3c59be.png)

**Comment by sammiullah** [comment]
**RFR** all

**Comment by ZarshaB** [comment]
**Reopened**
1>> It is now having heading but it is missing question mark.
![image](https://user-images.githubusercontent.com/35685146/52701261-a2d7d180-2f9b-11e9-8076-e36cbc0f29e6.png)

**Comment by sammiullah** [comment]
Remove if fixed!!!
