### ISSUE TITLE
UI - Login

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#36]

**Comment by asifjans** [comment]
![image](https://user-images.githubusercontent.com/10880558/35216200-a0dba184-ff88-11e7-933f-782f1775c3c7.png)

**Comment by ZarshaB** [comment]
1) There should not ":-" at the end of password mismatch error message and it should be red in color.
![image](https://user-images.githubusercontent.com/35685146/35269145-06cbd8b4-004d-11e8-8d8d-5207290ffd5b.png)

**Comment by ZarshaB** [comment]
2) It should be Sign Up/ Register on button and heading of page.
![image](https://user-images.githubusercontent.com/35685146/35269171-1cffe076-004d-11e8-9be0-c601686b59b5.png)

**Comment by ZarshaB** [comment]
3) Error message should be in red color on Forgot Password page.
![image](https://user-images.githubusercontent.com/35685146/35269248-4c057d0e-004d-11e8-801c-1a2b40c6a4f7.png)

**Comment by ZarshaB** [comment]
4) After resetting password it redirects to empty page instead of displaying "Thank you. Your password has been successfully reset. Lets continue to Sign In" message and also password does not reset.
![image](https://user-images.githubusercontent.com/35685146/35269276-5ec198f6-004d-11e8-82e5-014ec5b60973.png)

**Comment by ZarshaB** [comment]
5) It should be Sign Up/ Register on button and button's name should be "Register". 
![image](https://user-images.githubusercontent.com/35685146/35269344-865694f2-004d-11e8-8898-3652a4c356e2.png)

**Comment by ZarshaB** [comment]
6) It should be reset instead of re-set.
![image](https://user-images.githubusercontent.com/35685146/35269368-98896410-004d-11e8-8f5e-f9ddab229a4a.png)

**Comment by ZarshaB** [comment]
7) It should be "Forgot Password" and color of "Forgot Password" should be change in color. Message should also be red in color as it is an error message. 
![image](https://user-images.githubusercontent.com/35685146/35269394-a6e741e4-004d-11e8-9204-39e5f4d9446b.png)

**Comment by ZarshaB** [comment]
8) After Login it should take user to "Our Featured Cars" section on Home page.

**Comment by ZarshaB** [comment]
9) On clicking on any option of "My Account" it redirects to Home page with highlighting different menus. As options are not working.
![image](https://user-images.githubusercontent.com/35685146/35269534-1927bd4c-004e-11e8-842d-152e72d48374.png)

**Comment by ZarshaB** [comment]
10) On clicking on "Login" button without filling any field, page flickers on chrome.

**Comment by ZarshaB** [comment]
11) Facebook login is missing.
![image](https://user-images.githubusercontent.com/35685146/35269610-594d3316-004e-11e8-87b8-96554c36ad32.png)

**Comment by ZarshaB** [comment]
6) Word "reset" is  corrected but please make it's color green as it not an error message.

**Comment by ZarshaB** [comment]
7) It should be "Forgot Password" instead of "Forgotten Password" as mentioned in document and "Forgot Password" color should be orange as it is a link.
Color of text is red that is correct.

**Comment by ZarshaB** [comment]
4) It is redirecting to correct page.
But please remove space and make it in centre of page.
![image](https://user-images.githubusercontent.com/35685146/35285488-5308857e-007f-11e8-8e8e-364711ef98ad.png)

**Comment by ZarshaB** [comment]
1) Error message is not correct.
![image](https://user-images.githubusercontent.com/35685146/35285637-bdf6cf4e-007f-11e8-9a8b-3bffad6774fc.png)

It is
Ahhhh!!! A password confirmation mismatch. Please try again.

**Comment by ZarshaB** [comment]
2,3,5 are fixed.

**Comment by ZarshaB** [comment]
11) It is not fixed.

**Comment by ZarshaB** [comment]
12) There should be space between heading, text and button on "Forgot your Password" and "Login/Register" page.
![image](https://user-images.githubusercontent.com/35685146/35324916-08baae4e-0114-11e8-93dd-2c85f63716f3.png)
![image](https://user-images.githubusercontent.com/35685146/35324940-190c0568-0114-11e8-9fe2-d51b2f9d83a0.png)

**Comment by ZarshaB** [comment]
Fixed Issues are
2,3,5,10

**Comment by ZarshaB** [comment]
Issues not fixed are:
1,4,6,7,11

**Comment by ZarshaB** [comment]
4) It is redirecting to correct page if password in both Password and confirm password fields have 6 strings, but if both fields have password less than 6 strings then it redirects to empty page.
But please remove space and make it in centre of page.
![image](https://user-images.githubusercontent.com/35685146/35325201-dc342994-0114-11e8-9db1-a2364679e776.png)

**Comment by ZarshaB** [comment]
Not Fixed:
4,6,7,11

**Comment by ZarshaB** [comment]
13) Please make it bold and change it's font to website's font.
![image](https://user-images.githubusercontent.com/35685146/35376778-65417d5e-01ce-11e8-8323-80cafcf934d0.png)

**Comment by ZarshaB** [comment]
14) Please make the Highlighted lines bold and "Don't worry we're here to help as semi-bold".
![image](https://user-images.githubusercontent.com/35685146/35381479-3fc36a82-01de-11e8-9024-8dc422ee54d7.png)

**Comment by ZarshaB** [comment]
15) Verify your Account.
All bold.
![image](https://user-images.githubusercontent.com/35685146/35383202-6a7ad256-01e3-11e8-83d3-f2ab81fd16df.png)

**Comment by ZarshaB** [comment]
16) Welcome email. Make highlighted lines bold.
![image](https://user-images.githubusercontent.com/35685146/35383288-a5d31f48-01e3-11e8-9ae8-400a5ac9676b.png)

**Comment by ZarshaB** [comment]
17) It should be Add to Favourites instead of wishlist.
![image](https://user-images.githubusercontent.com/35685146/35395738-0d7fb5ec-020d-11e8-8cd4-5467bce2588d.png)

**Comment by ZarshaB** [comment]
Please make it's spacing same as for Forgot your password.
![image](https://user-images.githubusercontent.com/35685146/35433750-5a2df5e0-02a6-11e8-9271-659b4c0c0d39.png)

And make spacing between "new password" and confirm password fields same as it is between "email" and "password" fields.
![image](https://user-images.githubusercontent.com/35685146/35433787-7cb930a2-02a6-11e8-8b4f-998c2dacb96e.png)

**Comment by ZahidRavian** [comment]
These issues are fixed
12, 17

**Comment by ZarshaB** [comment]
19) Please also mention fields name as we display error on Register page, showing error message on required fields with fields name.
![image](https://user-images.githubusercontent.com/35685146/35512131-75bbd76a-0520-11e8-8b35-ef645cceda58.png)
![image](https://user-images.githubusercontent.com/35685146/35512142-7f1da89c-0520-11e8-9471-68fc7c511eb9.png)

**Comment by ZarshaB** [comment]
20) Color of button should not changed to blue.
![image](https://user-images.githubusercontent.com/35685146/35512230-c6abe37c-0520-11e8-8ccd-191a695122ca.png)

**Comment by ZarshaB** [comment]
21) After logout when I click back button, it brings be to same page and also displaying my name on page. Whereas I have logged out.

**Comment by asifjans** [comment]
@ZarshaB  Can you re-test and remove the issues those are fixed.

**Comment by ZarshaB** [comment]
8) Taking user to "Our Featured Cars" section but if screen is zoom out then it does not take to that section.

**Comment by ZarshaB** [comment]
19) Please also make same error message of field for Forgot you Password's page.
![image](https://user-images.githubusercontent.com/35685146/35555859-5bec4868-05c2-11e8-8e30-1c4195a282a5.png)

**Comment by ZarshaB** [comment]
20) Please make it "Login" on highlighted place and on button , as it is on other place.
![image](https://user-images.githubusercontent.com/35685146/35615310-91782f20-0693-11e8-9eb9-9f4e5bbea4d4.png)

**Comment by ZarshaB** [comment]
Not Fixed = 11, 6, 18 , 20, 8 , 19
New logged = 21

**Comment by ZarshaB** [comment]
22) Logout message does not disappear even if I refresh. And if I click on "Login" button then still it keep on giving same message.
![image](https://user-images.githubusercontent.com/35685146/35618196-0c9e1176-069c-11e8-91eb-10856aa3d8e8.png)

**Comment by Anum444** [comment]
Fixed
![image](https://user-images.githubusercontent.com/35521943/35635343-de92b564-06cf-11e8-93e6-75e403636a91.png)
![image](https://user-images.githubusercontent.com/35521943/35635370-f44bced6-06cf-11e8-82a1-75e47937b8e1.png)

**Comment by Anum444** [comment]
Also change hea
![image](https://user-images.githubusercontent.com/35521943/35635500-445a1676-06d0-11e8-8dda-e094b621d685.png)

**Comment by ZarshaB** [comment]
19= Not Fixed
