### ISSUE TITLE
Mobile View | New Design

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#361]

**Comment by ZarshaB** [comment]
There is an alignment issue of these headings.
![image](https://user-images.githubusercontent.com/35685146/52489012-0603e580-2be3-11e9-98cb-2d1b488f7ee5.png)

**Comment by ZarshaB** [comment]
1>> Filters in View Cars and Car Detail pages.

**Comment by Anum444** [comment]
**RFR**
1>> Filters in View Cars and Car Detail pages.

**Comment by ZarshaB** [comment]
There is a filter in Car detail page in mobile view. But I can't see filter in View Cars page. Also in current site we are using filter  button which redirects to filter page.

**Comment by Anum444** [comment]
**RFR**
There is a filter in Car detail page in mobile view. But I can't see filter in View Cars page. Also in current site we are using filter button which redirects to filter page.

**Comment by ZarshaB** [comment]
There is a filter page. But I think it would be similar to one we are using now. Separate filter page.
And also when I click on View Cars page then it displays filters while page loads and then filters disappears.

**Comment by ZarshaB** [comment]
2>> Whole texts are not available.
![image](https://user-images.githubusercontent.com/35685146/53097269-e5248400-3542-11e9-8090-c9f1bcb8a8dd.png)

**Comment by ZarshaB** [comment]
3>> This menu is not visible.
![image](https://user-images.githubusercontent.com/35685146/53097501-68de7080-3543-11e9-8112-5be2b646d16d.png)

**Comment by ZarshaB** [comment]
4>> Buttons should be small.
![image](https://user-images.githubusercontent.com/35685146/53097526-7bf14080-3543-11e9-9d02-ee53de82f484.png)

**Comment by ZarshaB** [comment]
5>> Login
Buttons are overlapping.
![image](https://user-images.githubusercontent.com/35685146/53097760-0c2f8580-3544-11e9-8d0a-abbdb6d79f47.png)

**Comment by ZarshaB** [comment]
6>> Buttons and ad level is not equal.
![image](https://user-images.githubusercontent.com/35685146/53097854-35e8ac80-3544-11e9-8680-7b2fe8475d27.png)

**Comment by ZarshaB** [comment]
7>> View Cars should also have separate filter page.
![image](https://user-images.githubusercontent.com/35685146/53097933-57e22f00-3544-11e9-9b2b-9759bfe89f96.png)

**Comment by ZarshaB** [comment]
8>> Placeholders are not complete.
![image](https://user-images.githubusercontent.com/35685146/53098060-a394d880-3544-11e9-9703-c728204fca2d.png)

**Comment by ZarshaB** [comment]
9>> Button placement of Place your Ad is not correct.
![image](https://user-images.githubusercontent.com/35685146/53098091-b60f1200-3544-11e9-9153-99812f10ec7f.png)

**Comment by ZarshaB** [comment]
10>> Menu icons alignment is not correct.
![image](https://user-images.githubusercontent.com/35685146/53098181-e951a100-3544-11e9-8072-903b90e4ce34.png)

**Comment by ZarshaB** [comment]
11>> My profile
Buttons are overlapping.
![image](https://user-images.githubusercontent.com/35685146/53098232-02f2e880-3545-11e9-8f93-47c83702cdb3.png)

**Comment by Anum444** [comment]
**RFR**
2>> Whole texts are not available.
4>> Buttons should be small.
5>> Login
Buttons are overlapping.
6>> Buttons and ad level is not equal.
8>> Placeholders are not complete.
9>> Button placement of Place your Ad is not correct.
10>> Menu icons alignment is not correct.
11>> My profile
Buttons are overlapping

**Comment by ZarshaB** [comment]
3>> Slider dots are overlapping with menus.
![image](https://user-images.githubusercontent.com/35685146/53336177-59826d00-391f-11e9-8646-c0d3813b1879.png)

**Comment by ZarshaB** [comment]
5>> iPhone:
![image](https://user-images.githubusercontent.com/35685146/53336359-e3323a80-391f-11e9-91f5-105afe509120.png)

**Android:**
![image](https://user-images.githubusercontent.com/35685146/53336383-f513dd80-391f-11e9-91c8-96a7141daead.png)

**Comment by ZarshaB** [comment]
12>> This button should be small.
![image](https://user-images.githubusercontent.com/35685146/53336501-50de6680-3920-11e9-97c0-f6f2b95696f0.png)

**Comment by ZarshaB** [comment]
Still there:
6>> Buttons and ad level is not equal.
![image](https://user-images.githubusercontent.com/35685146/53097854-35e8ac80-3544-11e9-8680-7b2fe8475d27.png)
![image](https://user-images.githubusercontent.com/35685146/53336572-7ff4d800-3920-11e9-9bc7-5fab1c6ec2e9.png)

**Comment by ZarshaB** [comment]
**Still there**
10>> Menus alignment is not correct.
![image](https://user-images.githubusercontent.com/35685146/53340371-af104700-392a-11e9-8984-55bb9f9187d3.png)

**Comment by ZarshaB** [comment]
**Re-opened**
11>> In iPhone it is okay but in Android buttons are still overlapping.
![image](https://user-images.githubusercontent.com/35685146/53340453-e2eb6c80-392a-11e9-9f3e-a0efc03f4062.png)

**Comment by ZarshaB** [comment]
**Reopen**
8>> Placeholders are not complete.
![image](https://user-images.githubusercontent.com/35685146/53098060-a394d880-3544-11e9-9703-c728204fca2d.png)

**Comment by ZarshaB** [comment]
13>> FAQs alignment.
![image](https://user-images.githubusercontent.com/35685146/53341306-04e5ee80-392d-11e9-8aef-e9f0eaac0d38.png)

**Comment by ZarshaB** [comment]
14>> Cart page
Icon overlapping with text.
![image](https://user-images.githubusercontent.com/35685146/53341506-83db2700-392d-11e9-8f52-52eabddd1593.png)

**Comment by ZarshaB** [comment]
15>> These headings are appearing in blue color in my mobile.
![image](https://user-images.githubusercontent.com/35685146/53341683-0368f600-392e-11e9-8f51-34ce5fdf1ce8.png)

**Comment by ZarshaB** [comment]
16>> Please align Remember Me like it should be either in one line or align below Remember.
![image](https://user-images.githubusercontent.com/35685146/53341752-38754880-392e-11e9-8c1a-965aff6afcfd.png)

**Comment by ZarshaB** [comment]
17>> There is extra space.
![image](https://user-images.githubusercontent.com/35685146/53341786-4a56eb80-392e-11e9-96fd-29a69eac80fb.png)

**Comment by ZarshaB** [comment]
18>> Menus are not appearing in my mobile.
![image](https://user-images.githubusercontent.com/35685146/53341909-96a22b80-392e-11e9-91e7-3a6f92a2cb94.png)

**Comment by ZarshaB** [comment]
7>> On scrolling Home page view changes its size.

**Comment by ZarshaB** [comment]
8>> On Points Redeem Policy page, buttons are mixing up with mobile.
![image](https://user-images.githubusercontent.com/35685146/54998635-74183680-4ff0-11e9-976d-9db1e11f8f45.png)

**Comment by ZarshaB** [comment]
9>> Error messages are overlapping.
![image](https://user-images.githubusercontent.com/35685146/54998672-898d6080-4ff0-11e9-8301-92d98550bf7d.png)

**Comment by ZarshaB** [comment]
10>> On Submit an Ad page, instead of integer it should be number. And it should display field name as Mileage (km).
![image](https://user-images.githubusercontent.com/35685146/54998771-c2c5d080-4ff0-11e9-8a12-b50af5a9adb1.png)
![image](https://user-images.githubusercontent.com/35685146/54998793-ca857500-4ff0-11e9-8b1e-c1f5d4686c9a.png)

**Comment by ZarshaB** [comment]
11>> Complete name is not visible.
![image](https://user-images.githubusercontent.com/35685146/54998835-df620880-4ff0-11e9-9658-802c79acab45.png)

**Comment by ZarshaB** [comment]
12>> Ad image, keychain and quantity field should be aligned.
![image](https://user-images.githubusercontent.com/35685146/54998927-19cba580-4ff1-11e9-8176-220ba710a435.png)

**Comment by ZarshaB** [comment]
13>> Car Detail page:
Complete table is not visible and on scrolling whole page scrolls and does not fit to the screen.
![image](https://user-images.githubusercontent.com/35685146/54999002-3536b080-4ff1-11e9-8f2f-1abab9eb25e9.png)

**Comment by ZarshaB** [comment]
14>> It is not displaying radio buttons. 
![image](https://user-images.githubusercontent.com/35685146/54999670-93b05e80-4ff2-11e9-81a3-82737a9c4c6a.png)

**Comment by ZarshaB** [comment]
13>> Please make it in center.
![image](https://user-images.githubusercontent.com/35685146/55008380-bba7be00-5002-11e9-968f-5a3b2a4288c0.png)

**Comment by ZarshaB** [comment]
**Reopened**
**High**
2>> Filter of car detail page is not working. 
![image](https://user-images.githubusercontent.com/35685146/55008294-a16de000-5002-11e9-8256-aa14ee174609.png)

**Comment by ZarshaB** [comment]
11>> It is displaying double error message. 
![image](https://user-images.githubusercontent.com/35685146/55081970-a4300a00-50c2-11e9-803b-a5b51d1c54d0.png)
