### ISSUE TITLE
Cart Page - New Design

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#363]
**Cart Page:**
https://invis.io/58PTTOMU3AT

[Slices of checkout & place order.zip](https://github.com/asifjans/Inovedia/files/2744963/Slices.of.checkout.place.order.zip)

**Comment by ZarshaB** [comment]
1>> It is "Product Details" instead of Product Detail.
![image](https://user-images.githubusercontent.com/35685146/52556645-0254a680-2e0f-11e9-9d88-e3f5db116b8f.png)

**Comment by ZarshaB** [comment]
2>> Button is very large in size and also it's icon is not visible it should also be white when background is orange.
![image](https://user-images.githubusercontent.com/35685146/52556739-3fb93400-2e0f-11e9-8beb-2f56abfcb68c.png)

**Comment by ZarshaB** [comment]
3>> Complete text is not visible.
![image](https://user-images.githubusercontent.com/35685146/52556786-5e1f2f80-2e0f-11e9-9db7-7bb0ac9b6681.png)

**Comment by ZarshaB** [comment]
4>> It's place holder is "Enter your Points"
![image](https://user-images.githubusercontent.com/35685146/52556843-7f801b80-2e0f-11e9-9f8a-c5853cdd058f.png)

**Comment by ZarshaB** [comment]
5>> Balance would be in orange color and also it would be at extreme right corner. Also please make "Redeem" button similar to "Apply" button.
![image](https://user-images.githubusercontent.com/35685146/52556937-ca9a2e80-2e0f-11e9-99ac-f440e93eda1c.png)

**Comment by ZarshaB** [comment]
6>> It is "Redeemed Points".
![image](https://user-images.githubusercontent.com/35685146/52557016-09c87f80-2e10-11e9-9eef-895143aa959e.png)

**Comment by ZarshaB** [comment]
7>> Color of button is with orange background.
![image](https://user-images.githubusercontent.com/35685146/52557064-34b2d380-2e10-11e9-86df-870ce34386a9.png)


**Reference:**
![image](https://user-images.githubusercontent.com/35685146/52557075-3c727800-2e10-11e9-89df-344072aeb0a3.png)

**Comment by ZarshaB** [comment]
8>> When clicked this field would be in orange color instead of blue color.
![image](https://user-images.githubusercontent.com/35685146/52557120-54e29280-2e10-11e9-9945-13deacd655fd.png)

**Comment by ZarshaB** [comment]
9>> Checkbox would also be in orange color and bullet points will also be in orange.
![image](https://user-images.githubusercontent.com/35685146/52557209-9115f300-2e10-11e9-9e35-556e372c05b3.png)

**Comment by ZarshaB** [comment]
10>> Year is in orange color.
![image](https://user-images.githubusercontent.com/35685146/52557305-cfabad80-2e10-11e9-8fa9-fcc2f0fd269d.png)

**Comment by ZarshaB** [comment]
11>> On clicking on Checkout it displays this message.
![image](https://user-images.githubusercontent.com/35685146/52557409-21543800-2e11-11e9-8aae-37c352691efd.png)

**Comment by ZarshaB** [comment]
12>> Please decrease it's font size little. 
![image](https://user-images.githubusercontent.com/35685146/52557476-59f41180-2e11-11e9-98c7-742c5a3e04b2.png)

**Comment by ZarshaB** [comment]
13>> When I take cursor on Redeem button then it does not highlight button with original orange color but it highlights with blur orange color.
![image](https://user-images.githubusercontent.com/35685146/52557632-d25ad280-2e11-11e9-80de-19ede027b621.png)

**Comment by ZarshaB** [comment]
14>> Highlight of this box should also be orange instead of blue.
![image](https://user-images.githubusercontent.com/35685146/52557715-09c97f00-2e12-11e9-9307-fad0da6fc4ac.png)

**Comment by ZarshaB** [comment]
15>> Field should be in center of button.
![image](https://user-images.githubusercontent.com/35685146/52557754-2f568880-2e12-11e9-8ff3-fd18b24f57ad.png)

**Comment by ZarshaB** [comment]
16>> At this line field should end here.
![image](https://user-images.githubusercontent.com/35685146/52557855-79d80500-2e12-11e9-8b31-c5e74cd48e9f.png)

**Comment by ZarshaB** [comment]
17>> Cross button is not working.
If I update any price then loading arrows that appear are so big in size. And redirects to old site cart page.
![image](https://user-images.githubusercontent.com/35685146/52557917-af7cee00-2e12-11e9-8a69-9e967af6b21c.png)

**Comment by ZarshaB** [comment]
18>> Please add AED before price.
![image](https://user-images.githubusercontent.com/35685146/52558498-62018080-2e14-11e9-8298-67cca4977517.png)

**Comment by ZarshaB** [comment]
19>> This space should be equal.
![image](https://user-images.githubusercontent.com/35685146/52558614-ad1b9380-2e14-11e9-950a-6f489aded2e7.png)

**Comment by ZarshaB** [comment]
20>> There should be space before I hereby.
![image](https://user-images.githubusercontent.com/35685146/52559925-9e36e000-2e18-11e9-8445-7c32db665825.png)

**Comment by Anum444** [comment]
**RFR**

**Comment by ZarshaB** [comment]
**Reopened**
2>> Button's size is okay now but it's icon is still not visible it should also be white when background is orange.

5>> Balance position is okay now. But it's color should be orange. And also "Redeem" button should not have black borders or text. It should be similar to "Apply" button
![image](https://user-images.githubusercontent.com/35685146/52702535-30b4bc00-2f9e-11e9-9ba0-a8c5ecc4bee3.png)

8>> It should have orange outline. I think it is for now having orange shadow. And also it's orange color is not similar to orange color we have used.
![image](https://user-images.githubusercontent.com/35685146/52702690-7d989280-2f9e-11e9-99e7-aefcfb3b5272.png)

9>> It's checkbox color is okay now but it should not have blue color shadow. And also bullets points color is not orange.
![image](https://user-images.githubusercontent.com/35685146/52702771-ae78c780-2f9e-11e9-8298-39fbfd90d4fb.png)

11>> Checkout button is not functional now.

14>>  It should have orange outline. I think it is for now having orange shadow. And also it's orange color is not similar to orange color we have used.
![image](https://user-images.githubusercontent.com/35685146/52702851-dbc57580-2f9e-11e9-8eb7-c09cb4e69744.png)

16>> Still there. 

17>> Cross button is working now but should not have blue outline.

**Comment by ZarshaB** [comment]
21>> When I cross any ad then it redirects to old design cart page.
![image](https://user-images.githubusercontent.com/35685146/52703247-b7b66400-2f9f-11e9-9a63-fb7643576302.png)

**Comment by ZarshaB** [comment]
22>> If I add ad with small title then it disturbs the alignment.
![image](https://user-images.githubusercontent.com/35685146/52703290-db79aa00-2f9f-11e9-808f-8eec233952ac.png)

**Comment by ZarshaB** [comment]
23>> Cash on Delivery button is missing and both buttons should be aligned accordingly.
![image](https://user-images.githubusercontent.com/35685146/52703365-03690d80-2fa0-11e9-8562-91e15fb3ae37.png)

**Comment by ZarshaB** [comment]
24>> Button should not highlight when disabled.
![image](https://user-images.githubusercontent.com/35685146/52716550-cc572400-2fc0-11e9-865f-051411855565.png)

**Comment by Anum444** [comment]
**RFR**
24>> Button should not highlight when disabled.
23>> Cash on Delivery button is missing and both buttons should be aligned accordingly.
22>> If I purchase ad with small title then it disturbs the alignment.
16>> Still there.
17>> Cross button is working now but should not have blue outline.
14>> It should have orange outline. I think it is for now having orange shadow. And also it's orange color is not similar to orange color we have used.
9>> It's checkbox color is okay now but it should not have blue color shadow. 
8>> It should have orange outline. I think it is for now having orange shadow. And also it's orange color is not similar to orange color we have used.
5>> Balance position is okay now. But it's color should be orange.
16>> At this line field should end here.
3>> Complete text is not visible.

**Comment by Anum444** [comment]
@sammiullah 
**Reopened**
2>> Button's size is okay now but it's icon is still not visible it should also be white when background is orange.
![image](https://user-images.githubusercontent.com/35685146/52716343-5eaaf800-2fc0-11e9-8f69-07a2f913fdba.png)

**Comment by ZarshaB** [comment]
**Reopened**
16 , 2 , 5 >> Still there.

**Comment by ZarshaB** [comment]
**Re-opened**
9>> Checkbox color is okay. But bullets color is not orange. It should be orange for all bullets of site.

**Comment by ZarshaB** [comment]
10>> Pay with Card button should be selected by default.
![image](https://user-images.githubusercontent.com/35685146/52946662-5541d700-3396-11e9-8ef9-edeb78a3c9ca.png)

**Comment by Anum444** [comment]
**RFR**
10>> Pay with Card button should be selected by default.
9>> Checkbox color is okay. But bullets color is not orange. It should be orange for all bullets of site.

**Comment by ZarshaB** [comment]
**Re-opened**
9>> Checkbox color is okay. But bullets color is not orange. It should be orange for all bullets of site.

**Comment by Anum444** [comment]
**RFR**
9>> Checkbox color is okay. But bullets color is not orange. It should be orange for all bullets of site.
