### ISSUE TITLE
FAQs and other Footer pages.

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#364]

**Comment by ZarshaB** [comment]
1>> From above and bottom space should be equal. Above space is okay please also make the below space similar.
![image](https://user-images.githubusercontent.com/35685146/52707766-4af49700-2faa-11e9-99a2-41d0a8347603.png)

**Comment by ZarshaB** [comment]
2>> Please remove these underlines on hover.
![image](https://user-images.githubusercontent.com/35685146/52707835-6fe90a00-2faa-11e9-8e2b-432bc80a63e4.png)

**Comment by ZarshaB** [comment]
2>> It should start from the same point as on other pages.
![image](https://user-images.githubusercontent.com/35685146/52711390-83e53980-2fb3-11e9-8df7-0d8221ddb452.png)

**Other page:**
![image](https://user-images.githubusercontent.com/35685146/52712015-3073eb00-2fb5-11e9-95cd-177ce289534f.png)

**Comment by sammiullah** [comment]
**RFR**
