### ISSUE TITLE
Redirection Issue

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#365]

**Comment by ZarshaB** [comment]
1>> When I cross any ad then it redirects to old design cart page.
![image](https://user-images.githubusercontent.com/35685146/52703247-b7b66400-2f9f-11e9-9a63-fb7643576302.png)

**Comment by ZarshaB** [comment]
2>> When I click on change password of My Profile it redirects me to this page.
![image](https://user-images.githubusercontent.com/35685146/52349613-c1444700-2a48-11e9-860b-3a60ecd8632a.png)

**Comment by ZarshaB** [comment]
3>> After logout it redirects to this page.
![image](https://user-images.githubusercontent.com/35685146/52352786-15eac080-2a4f-11e9-8dae-1d86e8377d5c.png)

**Comment by ZarshaB** [comment]
4>> After submitting form it redirects me to old site page.
![image](https://user-images.githubusercontent.com/35685146/52327966-d2249680-2a0f-11e9-973c-e1c118aa3fad.png)

**Comment by ZarshaB** [comment]
5>> Search button is now functional but it redirects to this page instead of new design detail page.
![image](https://user-images.githubusercontent.com/35685146/52699242-217e4000-2f97-11e9-86c2-e1b3e406e6df.png)

**Comment by ZarshaB** [comment]
6>> It is now functional but on clicking on button it redirects to this page instead of new design detail page.
![image](https://user-images.githubusercontent.com/35685146/52699110-d19f7900-2f96-11e9-8fe5-2f6c3aff8530.png)

**Comment by sammiullah** [comment]
**RFR** all these issues

**Comment by ZarshaB** [comment]
Other issues are fixed.

Reopened
5>> Still there.

**Comment by ZarshaB** [comment]
6>> After login it should redirect to "Our Featured Cars" section of Home page of new design. Currently it is redirecting to Home page.

**Comment by ZarshaB** [comment]
7>> If user clicks on any page which requires login then it redirects to old site to display message of please login. For example if I click on Submit an Ad button without login then it redirects me to this page.
![image](https://user-images.githubusercontent.com/35685146/52787968-4fd84a00-3081-11e9-8735-78a4b1e3a389.png)

**Comment by sammiullah** [comment]
**RFR** 7>> If user clicks on any page which requires login then it redirects to old site to display message of please login. For example if I click on Submit an Ad button without login then it redirects me to this page.
![image](https://user-images.githubusercontent.com/35685146/52787968-4fd84a00-3081-11e9-8735-78a4b1e3a389.png)

**Comment by ZarshaB** [comment]
8>> After updating password from My Profile page it redirects to old design page.
![image](https://user-images.githubusercontent.com/35685146/52857943-8c23ad00-314a-11e9-9be7-5ccb6847a10c.png)

**Comment by Anum444** [comment]
**RFR**

6>> After login it should redirect to "Our Featured Cars" section of Home page of new design. Currently it is redirecting to Home page.
8>> After updating password from My Profile page it redirects to old design page.

**Comment by ZarshaB** [comment]
**Re-opened:**
7>> For submit an ad it is fixed but for "Buy Ticket" button of Car detail page it is still redirecting to old site page.
![image](https://user-images.githubusercontent.com/35685146/52944759-fbd7a900-3391-11e9-9136-f328123c9037.png)

**Comment by ZarshaB** [comment]
**Re-opened:**
8>> After updating password from My Profile page it redirects to old design page where page keeps on loading.
![image](https://user-images.githubusercontent.com/35685146/52944947-756f9700-3392-11e9-8ccc-d081519108b7.png)

**Comment by ZarshaB** [comment]
9>> After saving My Profile page it redirects to this loading page which keep on loading.
![image](https://user-images.githubusercontent.com/35685146/52955647-05bbd500-33af-11e9-8b8c-58664378ccaa.png)

**Comment by Anum444** [comment]
**RFR**
7>> For submit an ad it is fixed but for "Buy Ticket" button of Car detail page it is still redirecting to old site page.

**Comment by ZarshaB** [comment]
**Re-opened:**
7>> For submit an ad it is fixed but for "Buy Ticket" button of Car detail page it is still redirecting to old site page.
![image](https://user-images.githubusercontent.com/35685146/52944759-fbd7a900-3391-11e9-9136-f328123c9037.png)

**Comment by Anum444** [comment]
**RFR**
7>> For submit an ad it is fixed but for "Buy Ticket" button of Car detail page it is still redirecting to old site page.

**Comment by ZarshaB** [comment]
7>> It is now redirecting to correct page of login. But it should also display similar message of "Please login/Register to continue". As it displays for Submit an ad. Also after login it redirects to old page cart page.
![image](https://user-images.githubusercontent.com/35685146/53094965-5b25ec80-353d-11e9-83bc-2a074d229d68.png)

**Comment by Anum444** [comment]
**RFR**
7>> It is now redirecting to correct page of login. But it should also display similar message of "Please login/Register to continue". As it displays for Submit an ad. Also after login it redirects to old page cart page.

**Comment by Anum444** [comment]
**RFR**
7>> It is now redirecting to correct page of login. But it should also display similar message of "Please login/Register to continue". As it displays for Submit an ad. Also after login it redirects to old page cart page.
