### ISSUE TITLE
Usama's Feedback Pop up  - 04-March-2019

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#368]

**Comment by ZarshaB** [comment]
1>> Login
When email address is submitted for Forgot password, the error message We're here to help. Password reset link has been sent to your email address butt_usama@hotmail.com should be a pop-up box(same as we are using through the site)

 Log Out Message
The Log Out Message  OK. You’ve been logged out. 
Until next time, stay awesome and come back soon!!! should be a pop-up message

**Comment by ZarshaB** [comment]
2>> All the messages that customer gets should be pop-up. The pop-up message lay out should be uniform and text type and size should be in line with rest of the site. Please show some design for a pop up message. You can take some from google search. Refer to image 5 attached. Too much spacing given on top and bottom. The new design should simple, minimal, smart and sleek. 
![image](https://user-images.githubusercontent.com/35685146/53726607-25afc600-3e90-11e9-804b-62cae6d5bc54.png)

**Comment by ZarshaB** [comment]
3>> Pop-up messages lay out needs to be changed. Please refer to General section for details

**Comment by ZarshaB** [comment]
4>> The pop-up boxes have unnecessary empty spacing on the top and bottom. Please adjust accordingly.

**Comment by Anum444** [comment]
**RFR**
4>> The pop-up boxes have unnecessary empty spacing on the top and bottom. Please adjust accordingly.
