### ISSUE TITLE
Usama's Feedback 18th March 2019

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#372]

**Comment by ZarshaB** [comment]
Home:
1>> The weladela logo on homepage has distance of appx 6cms from left whereas the image by designer has almost 4.5cm. Similarly the menu line (ending of Register Now button) has distance of appx 6 cms from right whereas it should be around 4.5cms. Please set it accordingly.

**Comment by ZarshaB** [comment]
**Home**
2>>When I click on drop down menu on my name, the drop down menu opens against “Contact Us” page. Also give a little more space in the options in the drop down menu.

**Comment by ZarshaB** [comment]
**Home:**
3>> The space between icons of How it works section on homepage (both buyer and seller) should be increased. I checked the distance between them on the image by designer and its is 0.3-0.5 cms greater than our design. So please increase it as per the design.

**Comment by ZarshaB** [comment]
**Home:**
4>> The Laptop screen on homepage is appx 9.3cms where as in design it is 11.5cms. So please increase it accordingly (both screen and the bottom silver part)

**Comment by ZarshaB** [comment]
**Home:**
5>> Some changes still to be made in HIW on home page. Two of them are mentioned below. Rest remove all exclamation marks there. I did not mention them in my previous document.
**Seller**
Ad goes LIVE 
Including a FREE car valuation from WelaDela
 
Sell fast and get more 
We market your car everywhere FREE to ensure sale in quick sale

**Comment by ZarshaB** [comment]
6>>The master card secure code and verified by visa logo should be moved lower. Almost overlapping the logos above them.
![image](https://user-images.githubusercontent.com/35685146/54514666-8f45cf00-497c-11e9-8095-9ffa95349608.png)

**Comment by ZarshaB** [comment]
7>> The Master Card, Visa and COD logos should be made a little bigger have a little more space between them and the heading “We Accept” should be centre aligned with these logos
![image](https://user-images.githubusercontent.com/35685146/54514696-a84e8000-497c-11e9-8981-e6d231ef75e7.png)

**Comment by ZarshaB** [comment]
8>> When you adjust the distance of the logo and menu bar as mentioned in the above # 1 point, the register and returning customer columns should be re-adjusted accordingly. It will give them enough space between each other. Same goes for download our app column on all pages.
![image](https://user-images.githubusercontent.com/35685146/54514796-e64ba400-497c-11e9-8fc7-ede9feb0c965.png)

![image](https://user-images.githubusercontent.com/35685146/54514761-d59b2e00-497c-11e9-8f37-fd1293d25e4d.png)

**Comment by ZarshaB** [comment]
9>> The New Customer and Returning customer boxes should be moved slightly lower. The distance should remain universal and should be the same as when the message appears when you enter wrong password.
![image](https://user-images.githubusercontent.com/35685146/54514842-f9f70a80-497c-11e9-9355-98d3974e0c7e.png)

**Comment by ZarshaB** [comment]
10>> **My Account**
When in my account, the options in grey bar (My Profile, My favorites etc) are way too small. Increase them a little with proportion to overall theme. Should not look too big nor too small.
![image](https://user-images.githubusercontent.com/35685146/54514894-1a26c980-497d-11e9-8996-c3c50797f128.png)

**Comment by ZarshaB** [comment]
11>> **Register**
Please give little more space between two lines at the bottom (lines with check box)
![image](https://user-images.githubusercontent.com/35685146/54514936-3f1b3c80-497d-11e9-8950-1a00b5116c07.png)

**Comment by ZarshaB** [comment]
12>> **View Cars**
The space between each ad (side-by side ads) is 0.3cms whereas in image by designer, it is 0.5cm. Please give that much space,

**Comment by ZarshaB** [comment]
13>> **View Cars**
The buttons showing number of pages be at least 10. From there it should have the next page option and then jump to last option. Currently we can seen only 3 pages in the option at the bottom

**Comment by ZarshaB** [comment]
14>> **View Cars**
The distance between search filter column on left and car list should be increased. Currently its appx 0.5cms whereas it should be 0.8-0.9cms

**Comment by ZarshaB** [comment]
15>> **Needs more fine tuning**
When the cart has some items in it then the cart button on top doesn’t look neat with digits 1 or 2 in them. Very blurry. Please make it look clean with perfect circle.

**Comment by ZarshaB** [comment]
16>> **View Cars- List**
The placement of ticket price is higher as compared to template provided by designer.
![image](https://user-images.githubusercontent.com/35685146/54515420-d4b6cc00-497d-11e9-9f5e-a90f7146b570.png)

**Reference:**
![image](https://user-images.githubusercontent.com/35685146/54515438-e1d3bb00-497d-11e9-946c-24f38f463e36.png)

**Comment by ZarshaB** [comment]
17>> **Car Detail**
The distance between search filter column on left and car list should be increased.  **STILL THERE. Its 0.5 cms where in designer’s image it is 1cm**

**Comment by ZarshaB** [comment]
18>> **Car Detail**
The quantity button is accepting negative as well. 
![image](https://user-images.githubusercontent.com/35685146/54515512-15aee080-497e-11e9-9b51-37f745e069ab.png)

**Comment by ZarshaB** [comment]
19>> **Cart**
Please remove the heading on top left in grey bar (View Cars/Check-out) 
![image](https://user-images.githubusercontent.com/35685146/54515549-2d866480-497e-11e9-9ab1-7fb0214e66eb.png)

**Comment by ZarshaB** [comment]
20>> **Cart**
Quantity button not working properly. Goes in negative and deducts the amount from total when goes in negative.
![image](https://user-images.githubusercontent.com/35685146/54515570-44c55200-497e-11e9-91b3-190c1d929002.png)

**Comment by ZarshaB** [comment]
21>> When you adjust the distance of the logo and menu bar as mentioned in the above # 1 point, setting and alignment of all the pages and sub-pages need to be redone with respect to the new distance.

**Comment by ZarshaB** [comment]
22>> Please change the font type, size and other things for all the emails as per the new format.

**Comment by ZarshaB** [comment]
23>> Image optimization.
https://github.com/asifjans/Inovedia/issues/370

**Comment by ZarshaB** [comment]
24>> SEO
https://github.com/asifjans/Inovedia/issues/371

**Comment by ZarshaB** [comment]
25>> Pop Up messages
https://github.com/asifjans/Inovedia/issues/368

**Comment by ZarshaB** [comment]
**Reopened**
5>> Please remove these exclamation marks. 
![image](https://user-images.githubusercontent.com/35685146/54603834-271fe780-4a67-11e9-83fd-7f2ba5916516.png)

**Comment by ZarshaB** [comment]
26>> On decreasing size it's line disappears.
![image](https://user-images.githubusercontent.com/35685146/54619017-c6ec6e00-4a85-11e9-942f-6d0545a43ab0.png)

**Comment by Anum444** [comment]
**RFR**
25>> Pop Up messages
#368

**Comment by ZarshaB** [comment]
25>> It is displaying this pop up having mis placed circle.
![image](https://user-images.githubusercontent.com/35685146/54830956-4c1c9080-4cdb-11e9-978c-8412599d3b0c.png)

**Comment by ZarshaB** [comment]
**Reopened**
It is still there. 
26>> On decreasing size it's line disappears.
![image](https://user-images.githubusercontent.com/35685146/54619017-c6ec6e00-4a85-11e9-942f-6d0545a43ab0.png)

**Comment by ZarshaB** [comment]
9>>This space is not same with and without error message.
![image](https://user-images.githubusercontent.com/35685146/54831247-d06f1380-4cdb-11e9-8376-f26944a2bf4e.png)

**Comment by ZarshaB** [comment]
27>> Please make the text of slider aligned with the logo.
![image](https://user-images.githubusercontent.com/35685146/54905131-17d6e900-4f02-11e9-9cd4-ce72294bb9fb.png)


**Reference:**
![image](https://user-images.githubusercontent.com/35685146/54905170-29b88c00-4f02-11e9-8a88-fd25668cf4ef.png)

**Comment by ZarshaB** [comment]
24>> Reopened
Page titles are different.
Home: Page Title:  Weladela – Sell Car in Raffle Draw / Win a Car in Lottery >> Please remove double dashes from Home page title.
![image](https://user-images.githubusercontent.com/35685146/54909424-fd097200-4f0b-11e9-99e9-571adcfdecbf.png)


How it works: Page Title: How it Works – How a lottery ticket of AED 25 can win you a Car in Lucky Draw - Weladela

View Cars: Page Title: Buy Used Car in Dubai with Raffle Tickets – Weladela

FAQs: Page title: Frequently Asked Question about Weladela - Raffle Car Draw in UAE – Weladela

Car Detail: Page Title: Buy {Car maker} {Car model} in {AED price ticket} from {City} Raffle Draw – Weladela
