### ISSUE TITLE
UI - Buttons / Label/ Link

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#39]
![image](https://user-images.githubusercontent.com/35521900/35270177-1e7aa852-0050-11e8-9f38-c480d471252f.png)
-Font Family
-Font Size
-Color
-Width* height
-Hover color
-Border-radius

**Comment by asifjans** [comment]
Font Family / Font Size / Font-Weight/ Color Code  width*height

1) ![image](https://user-images.githubusercontent.com/10880558/35268257-6f2a70ee-004a-11e8-844e-4cfcee509084.png)

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35270437-ef683574-0050-11e8-9370-db616294c02e.png)


-    Font Family
-    Font Size
-    Color
-    Hover Color
-    Width* height

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35270545-492da698-0051-11e8-9470-0931c06bc50d.png)

-    Font Family
-     Font Size
-     Color
-     Hover Color
-     Width* height
-     Border-radius

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35270604-84d7e924-0051-11e8-9af1-85c9900902e3.png)

-    Font Family
-    Font Size
-    Color
-    Hover Color
-    Width* height
-    Border-radius

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35270755-deb84fe2-0051-11e8-960b-28f5dedae6b4.png)



-    Font Family
-    Font Size
-    Color
-    Hover Color  ( BUY NOW)
-    Width* height
-    Border-radius

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35270838-1d119fc8-0052-11e8-9459-63c424784210.png)


-    Font Family
-    Font Size
-    Color
-    Width* height
-    Border-radius

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35270966-6d4150ce-0052-11e8-8769-ba69147187b4.png)

-  Font Family
-  Font Size
-  Color
-  Width* height
-  Border-radius

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35271354-a02a6358-0053-11e8-99a4-a58626e1e850.png)

-Font Family
-Font Size
-Color
-Width* height
-Hover color
-Border-radius

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35271404-d64ab87a-0053-11e8-8257-0a34a9c2a1dd.png)

-Font Family
-Font Size
-Color
-Width* height
-Hover color
-Border-radius

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35271716-cc68a9e2-0054-11e8-8ad9-67ff5fb4a1e3.png)

-Font Family
-Font Size
-Color
-Width* height
-Hover color
-Border-radius

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35271740-e421ed5a-0054-11e8-9842-ebf894360e57.png)

-Font Family
-Font Size
-Color
-Width* height
-Hover color
-Border-radius

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35271802-08bb99fe-0055-11e8-99a3-0baf1d147cdb.png)

-Font Family
-Font Size
-Color
-Width* height
-Hover color
-Border-radius

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35271845-2a7e0a0e-0055-11e8-8f9e-9c384865e36e.png)

-Font Family
-Font Size
-Color
-Width* height
-Hover color
-Border-radius

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35271861-3a199e92-0055-11e8-9541-f193378c22c1.png)

-Font Family
-Font Size
-Color
-Width* height
-Hover color
-Border-radius

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35271905-59042246-0055-11e8-96ed-3b850deb3f83.png)

-Font Family
-Font Size
-Color
-Width* height
-Hover color
-Border-radius

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35271982-85c51f4c-0055-11e8-8cf4-76f79b323426.png)


-Font Family
-Font Size
-Color
-Width* height
-Hover color
-Border-radius

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35272051-c40377cc-0055-11e8-8a59-705b2e0b91a9.png)

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35272077-d87d27f2-0055-11e8-9159-4624bbdc3fb1.png)

-Font Family
-Font Size
-Color
-Width* height
-Hover color
-Border-radius

**Comment by sammiullah** [comment]
![image](https://user-images.githubusercontent.com/35521900/35272111-f47f8c88-0055-11e8-9796-088350c9b25b.png)

-Font Family
-Font Size
-Color
-Width* height
-Hover color
-Border-radius

**Comment by ZarshaB** [comment]
1) Please make text of all buttons as bold and only first letter of a word capital instead of making whole word capital.

**Comment by ZarshaB** [comment]
2) Please change the color of all links to orange.
