### ISSUE TITLE
UI - Browse Rate Schedules

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#4]
Please check formatting of Browse Rate Schedules and it's child screen

**Comment by xahide** [comment]
The CRUD about RateSchedule are functional. But there is problem in the CRUD of RateScheduleItem.  It gives the following error to create RateScheduleItem.
{"status":"error","message":"PerThread execution failed (probably due to bad input parameters) for IIvrApi.RateScheduleItemAdd","data":null}
