### ISSUE TITLE
Responsive Issues iPhone Portrait

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#42]

**Comment by ZarshaB** [comment]
1) iPhone portrait
Logo and buttons are not aligned.
![image](https://user-images.githubusercontent.com/35685146/35376840-ad30b7f6-01ce-11e8-9e73-3cae45fe8482.png)

**Comment by ZarshaB** [comment]
2) iPhone portrait
Color appears red on hover.
![image](https://user-images.githubusercontent.com/35685146/35376914-edb7b55e-01ce-11e8-8b8c-5da1fdec41b7.png)

**Comment by ZarshaB** [comment]
3) Place your Ad button does not appear.
![image](https://user-images.githubusercontent.com/35685146/35377140-dda5fe72-01cf-11e8-978a-23269944c088.png)

**Comment by ZarshaB** [comment]
iPhone portrait. 
4) Complete content does not appear. 
![image](https://user-images.githubusercontent.com/35685146/35377266-4a7663e8-01d0-11e8-9f27-25267ea1acb8.png)

**Comment by ZarshaB** [comment]
iPhone portrait. 
5) All "Learn More" buttons are not aligned.
![image](https://user-images.githubusercontent.com/35685146/35377821-7b012bf4-01d2-11e8-8b67-43178b253525.png)

**Comment by ZarshaB** [comment]
iPhone portrait.
6) Whole How it works section is not appearing.
![image](https://user-images.githubusercontent.com/35685146/35377868-a06639f2-01d2-11e8-93fd-442a74f34b98.png)

**Comment by ZarshaB** [comment]
iPhone portrait.
7) Content is not visible and images are appearing as extended.

**Comment by ZarshaB** [comment]
iPhone portrait.
8) Extra space is appearing.
![image](https://user-images.githubusercontent.com/35685146/35379437-e88def0e-01d7-11e8-95fd-7e1a1b59bdd5.png)

**Comment by ZarshaB** [comment]
iPhone Portrait.
9) Buttons are not appearing correct.
![image](https://user-images.githubusercontent.com/35685146/35379869-688171a8-01d9-11e8-9477-20b7f6662076.png)

**Comment by ZarshaB** [comment]
iPhone Portrait.
10) Not appearing in one line.
![image](https://user-images.githubusercontent.com/35685146/35379956-b23b163c-01d9-11e8-9e20-35918e76baa9.png)

**Comment by ZarshaB** [comment]
iPhone Portrai.
11) Button is overlapping.
![image](https://user-images.githubusercontent.com/35685146/35380079-0ccd9e30-01da-11e8-811a-a159d791796c.png)

**Comment by ZarshaB** [comment]
iPhone Portrait.
12) Drop down is going out of layout.
![image](https://user-images.githubusercontent.com/35685146/35380164-4e329790-01da-11e8-84c2-53b17ab880d5.png)

**Comment by ZarshaB** [comment]
13) Button should be in middle.
![image](https://user-images.githubusercontent.com/35685146/35380275-9e616d36-01da-11e8-8f6f-c3b5e25e2e48.png)

**Comment by ZarshaB** [comment]
14) Layout issue.
![image](https://user-images.githubusercontent.com/35685146/35382158-369ee970-01e0-11e8-9171-f8dd96ebfde2.png)

**Comment by asifjans** [comment]
13 - in all screen button position is left align.

**Comment by asifjans** [comment]
1,2,4,5,6,7,8,9,10,11,12,14 (Fixed)
