### ISSUE TITLE
Responsive Issues iPhone Landscape

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#43]

**Comment by ZarshaB** [comment]
1) Buttons are not at same level.
![image](https://user-images.githubusercontent.com/35685146/35380534-5959b6d4-01db-11e8-8ba5-1f0bac546c6b.png)

**Comment by ZarshaB** [comment]
2) Content is going out of layout.
![image](https://user-images.githubusercontent.com/35685146/35380583-86ba6ac4-01db-11e8-812d-e6ea5ee82a58.png)

**Comment by ZarshaB** [comment]
3) Space is available on all pages except Home page.
![image](https://user-images.githubusercontent.com/35685146/35389568-00e9fc9c-01fa-11e8-8d57-f9c1b1085e07.png)

**Comment by ZarshaB** [comment]
4) Buttons are appearing in very large size.
![image](https://user-images.githubusercontent.com/35685146/35389607-2c165e1a-01fa-11e8-8988-385d5071d06b.png)

**Comment by ZarshaB** [comment]
5) It does not changes to User's name after login.
![image](https://user-images.githubusercontent.com/35685146/35389622-43c2959c-01fa-11e8-89d9-6b165b93478a.png)

**Comment by ZarshaB** [comment]
6) Learn More buttons of Home page are not in one line.
![image](https://user-images.githubusercontent.com/35685146/35389663-67c29bfe-01fa-11e8-8f38-cfca3dc3ba1a.png)

**Comment by ZarshaB** [comment]
7) Buttons are not appearing in correct layout.
![image](https://user-images.githubusercontent.com/35685146/35389703-895c9008-01fa-11e8-90bd-e05d726b4c79.png)

**Comment by ZarshaB** [comment]
8) Headings should be aligned with table.
![image](https://user-images.githubusercontent.com/35685146/35389721-9cb44e70-01fa-11e8-9d29-e1197edd5103.png)

**Comment by ZarshaB** [comment]
9) Things are overlapping and also images are not appearing.
![image](https://user-images.githubusercontent.com/35685146/35389773-c6f00756-01fa-11e8-934b-3d2b76b8ccda.png)

**Comment by ZarshaB** [comment]
10) On clicking on "Login/Register" button after login, it is redirecting to place your ad page.

**Comment by asifjans** [comment]
1,2,3,4,5,6,7,8,9,10 (Fixed)
