### ISSUE TITLE
Responsive Issues 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#45]

**Comment by ZarshaB** [comment]
1) Alignment issue.
![image](https://user-images.githubusercontent.com/35685146/35390313-c3ad78e2-01fc-11e8-8331-1df0b01530c7.png)

**Comment by ZarshaB** [comment]
2) Complete sliders are not appearing.
![image](https://user-images.githubusercontent.com/35685146/35390337-db88f54a-01fc-11e8-939c-48798074a4f0.png)

**Comment by ZarshaB** [comment]
3) Learn More buttons are not in one line.
![image](https://user-images.githubusercontent.com/35685146/35390367-fbf7c630-01fc-11e8-8072-15017fa0d395.png)

**Comment by ZarshaB** [comment]
4) Correct images are not appearing ans also buttons of "Buyer" and "Seller" are not appearing.
![image](https://user-images.githubusercontent.com/35685146/35390390-162ec7b0-01fd-11e8-84e6-45405f4ba907.png)

**Comment by ZarshaB** [comment]
5) Complete heading is not appearing.
![image](https://user-images.githubusercontent.com/35685146/35390419-30d267e8-01fd-11e8-9425-657addcec03d.png)

**Comment by ZarshaB** [comment]
6) Alignment issue of footer.
![image](https://user-images.githubusercontent.com/35685146/35390441-46a5f17a-01fd-11e8-9b4a-e4c7e6538ebc.png)

**Comment by ZarshaB** [comment]
7) Layout Issue:
![image](https://user-images.githubusercontent.com/35685146/35390468-6d4befdc-01fd-11e8-84b4-017214c3d708.png)

**Comment by ZarshaB** [comment]
8) Complete car is not visible due to timer.
![image](https://user-images.githubusercontent.com/35685146/35390616-ea02ccc6-01fd-11e8-9ab8-fdc332a3db29.png)

**Comment by ZarshaB** [comment]
9) Complete field is not visible.
![image](https://user-images.githubusercontent.com/35685146/35390715-2d8afb8a-01fe-11e8-8c01-679cb86b6624.png)

**Comment by ZarshaB** [comment]
10) Only one button is visible.
![image](https://user-images.githubusercontent.com/35685146/35390750-51a8d0fa-01fe-11e8-963f-5752336405b9.png)

**Comment by ZarshaB** [comment]
11) Other images of Car detail page are not visible.
![image](https://user-images.githubusercontent.com/35685146/35390786-68e44a56-01fe-11e8-85c5-a69261d303e9.png)

**Comment by ZarshaB** [comment]
12) Complete table is not visible.
![image](https://user-images.githubusercontent.com/35685146/35390818-81664f7a-01fe-11e8-8582-5ea08d692a41.png)

**Comment by ZarshaB** [comment]
12) Going out of layout.
![image](https://user-images.githubusercontent.com/35685146/35390856-9cd7c2e8-01fe-11e8-91cd-76c84327460c.png)

**Comment by ZarshaB** [comment]
13) Buttons are overlapping.
![image](https://user-images.githubusercontent.com/35685146/35390872-ade1d40c-01fe-11e8-898a-76987ed9a87a.png)

**Comment by ZarshaB** [comment]
14) Layout issue:
![image](https://user-images.githubusercontent.com/35685146/35390908-cd966e8e-01fe-11e8-83f3-0537bb021e63.png)

**Comment by ZarshaB** [comment]
15) Buttons are not appearing correct.
![image](https://user-images.githubusercontent.com/35685146/35390979-0d031842-01ff-11e8-9be8-188132baf07c.png)

**Comment by ZarshaB** [comment]
16) Layout issue on Forgot you Password page.
![image](https://user-images.githubusercontent.com/35685146/35391066-5b93a83c-01ff-11e8-8f91-3f1596d1b112.png)

**Comment by ZarshaB** [comment]
17) Buttons are overlapping on "Forgot your Password" page.
![image](https://user-images.githubusercontent.com/35685146/35391089-7117fdca-01ff-11e8-8a1e-787480d71fc0.png)

**Comment by ZarshaB** [comment]
18) Complete buttons are not appearing.
![image](https://user-images.githubusercontent.com/35685146/35436041-bf55f3ac-02ae-11e8-83b3-222a709b7cb7.png)

**Comment by ZarshaB** [comment]
19) Pop up button is not appearing correct and complete.
![image](https://user-images.githubusercontent.com/35685146/35436089-e3249068-02ae-11e8-9601-bdc64f063dd8.png)

**Comment by ZarshaB** [comment]
20) This should appear like the one below.
![image](https://user-images.githubusercontent.com/35685146/35441461-681cd42c-02c5-11e8-96c2-40cf9cd40da5.png)

![image](https://user-images.githubusercontent.com/35685146/35441455-5efc2d16-02c5-11e8-90d1-059672e711e8.png)

**Comment by ZarshaB** [comment]
21) Button is overlapping with text.
![image](https://user-images.githubusercontent.com/35685146/35441594-ef006378-02c5-11e8-805c-99abafcf9d29.png)

**Comment by ZarshaB** [comment]
22) Nationality drop down of Register page is going out of layout.

**Comment by ZarshaB** [comment]
23) Every time I click on "Login/Register" button, it takes me to LogIn/Register" page that is correct, but also shows error message.
![image](https://user-images.githubusercontent.com/35685146/35441694-4ef3b9b0-02c6-11e8-94d7-3a98938759e0.png)

**Comment by asifjans** [comment]
2,11, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23

**Comment by ZarshaB** [comment]
2>> If title is long then alignment changes.
![image](https://user-images.githubusercontent.com/35685146/38314727-56865318-3840-11e8-9200-6ed15272de36.png)

**Comment by ZarshaB** [comment]
3>> Radio button's are not appearing correct.
![image](https://user-images.githubusercontent.com/35685146/38314759-6e535dc4-3840-11e8-9ad2-176d9e91bcf0.png)

**Comment by ZarshaB** [comment]
4>> Alignment of images.
![image](https://user-images.githubusercontent.com/35685146/38314803-92049ad0-3840-11e8-823d-6c1e7a1d62d1.png)

**Comment by ZarshaB** [comment]
5>> Please also check the headings spacing of pages. Before you made them equal but again it seems like they are not equal.

**Comment by ZarshaB** [comment]
6>> Button's size increases as I click on it in landscape mode.
![image](https://user-images.githubusercontent.com/35685146/38317528-b1c76626-3846-11e8-831c-8eb1d607d8f4.png)

**Comment by ZarshaB** [comment]
7>> Value of cart icon disturbs in landscape mode.
![image](https://user-images.githubusercontent.com/35685146/38317588-cf0c1222-3846-11e8-9e6e-126ba4a8a27d.png)

**Comment by ZarshaB** [comment]
8>> Color of both is changed in iPhone.
![image](https://user-images.githubusercontent.com/35685146/38317890-8a3eb022-3847-11e8-9a39-a412f9cc4519.png)

**Comment by ZarshaB** [comment]
9>> Reward points page numbering is appearing like this in iPhone.
![image](https://user-images.githubusercontent.com/35685146/38317965-b79e9c4e-3847-11e8-99b3-e4d350c53b96.png)

**Comment by ZarshaB** [comment]
10>> Place your Ad page radio button and labels are not aligned.

**Comment by ZarshaB** [comment]
1>> Could the radio buttons be increased more? As they are not completely filled. Also in iPhone. 
![image](https://user-images.githubusercontent.com/35685146/38422598-cb3af8e6-39c4-11e8-86a3-132ee301e790.png)

**Comment by ZarshaB** [comment]
2>> There is so much extra space. Can you please align quantity and heart in between Time left and Ticket Sold. And also move Time left and Ticket sold a little above.
![image](https://user-images.githubusercontent.com/35685146/38422689-208b8f18-39c5-11e8-88b6-6b11e7abe080.png)

**Comment by Anum444** [comment]
move Time left and Ticket sold a little above. **(FIXED)**

**Comment by ZarshaB** [comment]
Please correct the alignment of checkbox.
![image](https://user-images.githubusercontent.com/35685146/38427925-faa61c6e-39d3-11e8-99c6-adf9149c9cd5.png)
![image](https://user-images.githubusercontent.com/35685146/38427962-16235858-39d4-11e8-8935-4264fd96753a.png)
