### ISSUE TITLE
Responsive Issues Android Landscape.

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#48]

**Comment by ZarshaB** [comment]
1) Buttons are not at same level.
![image](https://user-images.githubusercontent.com/35685146/35433988-4c0c5456-02a7-11e8-82ec-be10d5bc32f0.png)

**Comment by ZarshaB** [comment]
2) Complete content is not appearing.
![image](https://user-images.githubusercontent.com/35685146/35435418-7f304c16-02ac-11e8-8f87-9ba6831161b0.png)

**Comment by ZarshaB** [comment]
3) How it works section is not appearing correct.
![image](https://user-images.githubusercontent.com/35685146/35435576-12cc36a6-02ad-11e8-8b8e-8fd73033268d.png)

**Comment by ZarshaB** [comment]
4) Learn More buttons alignment issue.

**Comment by ZarshaB** [comment]
5) In pop up Buttons are not appearing correct.
![image](https://user-images.githubusercontent.com/35685146/35435689-7b0ad1fa-02ad-11e8-98d5-d55a4fb21f27.png)

**Comment by ZarshaB** [comment]
6) Alignment Issue:
![image](https://user-images.githubusercontent.com/35685146/35435751-b13d5e0a-02ad-11e8-8023-9841da8e6968.png)

**Comment by ZarshaB** [comment]
7) Buttons alignment issue:
![image](https://user-images.githubusercontent.com/35685146/35435840-04723f82-02ae-11e8-9962-7beeb863eb71.png)

**Comment by ZarshaB** [comment]
8) Drop down of nationality is going out of layout.
![image](https://user-images.githubusercontent.com/35685146/35435911-430248be-02ae-11e8-810d-0dc939fc2399.png)

**Comment by ZarshaB** [comment]
9) Overlapping of button with text.
![image](https://user-images.githubusercontent.com/35685146/35435940-56b60dd2-02ae-11e8-85f6-95dad54159b7.png)

**Comment by ZarshaB** [comment]
10) Extra space is there.
![image](https://user-images.githubusercontent.com/35685146/35441899-2447ed48-02c7-11e8-85f3-4c43013a576f.png)

**Comment by ZarshaB** [comment]
11) Lines are going out of layout.
![image](https://user-images.githubusercontent.com/35685146/35442448-1e7154c0-02c9-11e8-9b73-170a833c3477.png)

**Comment by ZarshaB** [comment]
12) Buttons are overlapping.
![image](https://user-images.githubusercontent.com/35685146/35442761-2ae1cb30-02ca-11e8-9b5f-0a17dfc32774.png)

**Comment by ZarshaB** [comment]
13) It should start from here:
![image](https://user-images.githubusercontent.com/35685146/35442800-567540e2-02ca-11e8-913d-8e225ba88afe.png)

**Comment by asifjans** [comment]
2, 5, 6, 7, 8, 11 (FIXED)
