### ISSUE TITLE
Responsive Issues iPad Portrait

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#51]

**Comment by ZarshaB** [comment]
1) Text is not appearing on slider.
![image](https://user-images.githubusercontent.com/35685146/35443451-ec6cc6a4-02cc-11e8-8568-42d32a4ebb5d.png)

**Comment by ZarshaB** [comment]
2) How it works section is not correct.
![image](https://user-images.githubusercontent.com/35685146/35444307-f356f3a6-02cf-11e8-80b7-13945d005760.png)

**Comment by ZarshaB** [comment]
3) Stretched images are appearing.
![image](https://user-images.githubusercontent.com/35685146/35444373-34342d6c-02d0-11e8-946d-3a05054c27c5.png)

**Comment by ZarshaB** [comment]
4) Menu is not appearing correct.
![image](https://user-images.githubusercontent.com/35685146/35444425-5749639e-02d0-11e8-885c-b16e2f3c0d9e.png)

**Comment by ZarshaB** [comment]
5) Buttons are not appearing correct.
![image](https://user-images.githubusercontent.com/35685146/35444960-f942548e-02d1-11e8-9a3a-cc638f3f9f51.png)

**Comment by ZarshaB** [comment]
6) This field is not appearing correct.
![image](https://user-images.githubusercontent.com/35685146/35445030-26cd0c64-02d2-11e8-89e6-740968f3d784.png)

**Comment by ZarshaB** [comment]
7) Nationality drop down of Register page is going out of layout.

**Comment by ZarshaB** [comment]
8) It should be in one line.
![image](https://user-images.githubusercontent.com/35685146/35445081-546b29da-02d2-11e8-98fa-5173ad72e7ff.png)
![image](https://user-images.githubusercontent.com/35685146/35445100-5f20072e-02d2-11e8-9a0b-ff0aed73e9a9.png)

**Comment by ZarshaB** [comment]
9) Extra space is there on page.
![image](https://user-images.githubusercontent.com/35685146/35445210-b0d2f4a0-02d2-11e8-8cc2-cbf565fd3bcb.png)

**Comment by asifjans** [comment]
1,2,3,4,5,6,7,8,9 (FIXED)

**Comment by ZarshaB** [comment]
1) Text is overlapping with search bar. Complete image of slider is not visible. Extra lines are appearing on menu. 

![image](https://user-images.githubusercontent.com/35685146/36062689-293bbdca-0e93-11e8-9899-47735a33bcfa.png)

**Comment by ZarshaB** [comment]
2>> Extra space is there below .
![image](https://user-images.githubusercontent.com/35685146/36475286-fe018338-171b-11e8-88fa-c5079647e84e.png)
![image](https://user-images.githubusercontent.com/35685146/36475305-0b01c444-171c-11e8-82ae-9b250a038bab.png)
![image](https://user-images.githubusercontent.com/35685146/36475385-413d6130-171c-11e8-9ccd-45602e1d472e.png)

3>> Footer's alignment.
![image](https://user-images.githubusercontent.com/35685146/36475361-30bf294c-171c-11e8-87a2-7e19e89a46bf.png)

4>> It should be at one line.
![image](https://user-images.githubusercontent.com/35685146/36475406-539694fa-171c-11e8-8f77-d50d790ddfa1.png)

5>> Overlapping of icons and also extra space is there.
![image](https://user-images.githubusercontent.com/35685146/36475420-6312fad6-171c-11e8-8250-8fddbede0fe1.png)

6>> Text of Download Our App" is overlapping with buttons.
![image](https://user-images.githubusercontent.com/35685146/36475444-7e88a946-171c-11e8-8956-f7d6422308f1.png)

**Comment by ZarshaB** [comment]
7>> Overlapping icon.
![image](https://user-images.githubusercontent.com/35685146/36895596-39a427ee-1e31-11e8-9626-757d9be5678c.png)

**Comment by ZahidRavian** [comment]
Please test the following issues and remove them from GitHub.
4>> It should be at one line.
7>> Overlapping icon.

**Comment by ZarshaB** [comment]
8>> Text is overlapping.
![image](https://user-images.githubusercontent.com/35685146/36966359-60bc80de-207e-11e8-9fc8-f5c26a9bdddb.png)

**Comment by ZahidRavian** [comment]
These issues are fixed and ready for testing.

3>> Footer's alignment. 
6>> Text of Download Our App" is overlapping with buttons.  
8>> Text is overlapping.

**Comment by ZarshaB** [comment]
3>> Placement of price filter.
![image](https://user-images.githubusercontent.com/35685146/37279664-3cb90fce-260d-11e8-9fc8-a13d450e433d.png)

**Comment by ZarshaB** [comment]
4>> Alignmnet of text is not same.
![image](https://user-images.githubusercontent.com/35685146/37279736-785770f2-260d-11e8-93ad-6cba79395bf3.png)

**Comment by ZarshaB** [comment]
5>> After login it redirects to this part, whereas it should redirect to "Our Featured Cars" heading.
![image](https://user-images.githubusercontent.com/35685146/37280088-9795276a-260e-11e8-8cc0-abd1627b2bcc.png)

**Comment by ZarshaB** [comment]
6>> Overlapping of buttons.
![image](https://user-images.githubusercontent.com/35685146/37280105-a60988ae-260e-11e8-8b83-3599eac096d4.png)

**Comment by ZarshaB** [comment]
7>> Overlapping of search bar and text.
![image](https://user-images.githubusercontent.com/35685146/37280145-becf5c60-260e-11e8-990c-ed3e0cb82327.png)

**Comment by ZarshaB** [comment]
8>> Menu icon changes.
![image](https://user-images.githubusercontent.com/35685146/37280202-f029c5c0-260e-11e8-82bd-00f6294c185c.png)

**Comment by ZarshaB** [comment]
9>> Extra space on My Favorites page.
![image](https://user-images.githubusercontent.com/35685146/37280360-57f8ddc6-260f-11e8-9aee-43b4c0e37377.png)

**Comment by ZarshaB** [comment]
10>> Complete icon is not visible.
![image](https://user-images.githubusercontent.com/35685146/37280405-7bdf558a-260f-11e8-8391-6eb6b6059eae.png)

**Comment by Anum444** [comment]
**These issues are fixed and ready for testing**

2>> Extra space is there below. (Fixed)
3>> Placement of price filter. (FIXED)
4>> Alignment of text is not same. (FIXED)
5>> After login it redirects to this part, whereas it should redirect to "Our Featured Cars" heading.(FIXED)
6>> Overlapping of buttons. (FIXED)
7>> Overlapping of search bar and text. (FIXED)
8>> Menu icon changes on all login pages. (FIXED)
9>> Extra space on My Favorites page. (Fixed)
10>> Complete icon is not visible. (FIXED)

**Comment by ZarshaB** [comment]
Fixed >> 3,4,6,8,9,10
**Not Fixed:**
2>> Now all these page are appearing like this:
![image](https://user-images.githubusercontent.com/35685146/37830811-2fc527b0-2ec5-11e8-9718-c37d2e3183f6.png)
5>> After login, it is not redirecting to correct place.

**Comment by Anum444** [comment]
5>> After login it redirects to this part, whereas it should redirect to "Our Featured Cars" heading. (Fixed)
