### ISSUE TITLE
Responsive Issues iPad Landscape

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#52]

**Comment by ZarshaB** [comment]
1) Complete content is not visible.
![image](https://user-images.githubusercontent.com/35685146/35445271-f0006f40-02d2-11e8-8ff4-734e810dbc76.png)

**Comment by ZarshaB** [comment]
2) It should be in one line.
![image](https://user-images.githubusercontent.com/35685146/35445342-27df0070-02d3-11e8-9f2a-f5d33c0084cc.png)

**Comment by ZarshaB** [comment]
3) Layout issue.
![image](https://user-images.githubusercontent.com/35685146/35445373-3ac86820-02d3-11e8-9832-aec882ac3870.png)

**Comment by ZarshaB** [comment]
4) All boxes should be in one line.
![image](https://user-images.githubusercontent.com/35685146/35445392-4fa6e212-02d3-11e8-980e-a7daa121f310.png)

**Comment by asifjans** [comment]
1,2,3,4 (FIXED)
