### ISSUE TITLE
Terms and conditions

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#53]

**Comment by ZarshaB** [comment]
1) Please change all highlighted words to weladela.com and make it hyperlinked to site. 
![image](https://user-images.githubusercontent.com/35685146/35504163-1aeae11c-0504-11e8-89f5-235833bc1a58.png)
![image](https://user-images.githubusercontent.com/35685146/35504241-5b594086-0504-11e8-8d3a-d5d17978272c.png)
![image](https://user-images.githubusercontent.com/35685146/35504306-896607ca-0504-11e8-9063-2c5d6233b0be.png)

**Comment by ZarshaB** [comment]
2) Updated terms and conditions:
All tickets sold are subject to terms and conditions of the WelaDela.com. Please read the terms and conditions carefully and contact us in case of any queries before you make a purchase. We reserve the right at any time and without prior notice to changes these Terms & Conditions and you are solely responsible for reviewing these Terms & Conditions from time to time. Although WelaDela.com shall make every effort to notify you of any such changes, however, WelaDela.com cannot be held liable for any failure to do so. Your purchase of a raffle ticket constitutes your acceptance of the Terms & Conditions. If you do not agree to these Terms & Conditions, you must immediately refrain from using the Website and its Services.


The following Terms and Conditions apply to our website. By accessing the Website or using its services, you agree that you have read, understood and agree to adhere to these Terms & Conditions. All exclusions and limitations of liability in these Terms & Conditions apply for our benefit and the benefit of all service providers and vendors. 

•	Employees, trainees or partners of WelaDela.com, as well as immediate family (spouse, parents, siblings and children) and household members of those employees, are not eligible to enter.
•	Raffle tickets will be emailed upon acceptance of payment by the bank
•	Raffle tickets are personal and revocable licenses that shall at all times remain the property of WelaDela.com. Any raffle tickets obtained in breach of the terms and conditions will be void.
•	If any part of Raffle ticket is removed, altered or defaced, that particular ticket may be invalidated. 
•	It is the responsibility of the purchaser to ensure that all information they provide are accurate (e.g. Passport Number, Emirates ID Number, Name, Nationality etc.). All customer information on raffle tickets may not be altered, modified, copied or reproduced in any way. 
•	No details will be altered once the ticket has been purchased.
•	Raffle tickets are only valid for the car mentioned on the ticket.
•	Ticket is non-transferable to any other person or institution and cannot be exchanged for cash.
•	Weladela.com does not offer any cash alternatives to the cars and cannot be held responsible for any financial dealings conducted by the winner with potential buyers.
•	In case of any unsuccessful draw due to any unforeseen reason, Weladela.com reserves the right to transfer this ticket to another draw for the car with similar market value. In that case, another ticket with new number will be sent to the buyer through email.
•	Refund shall only be made after the ticket has been included in and/or transferred to three unsuccessful draws.
•	Once the raffle draw is conducted, no refunds shall be made after that.
•	In case of winning the draw, the winner will have the car transferred in his or her name within seven (7) days of the draw. In the event that the winner fails to do so, WelaDela.com reserves the right to conduct another draw and pick a new winner after seven (7) days, if the original winner fails to respond to communication sent by WelaDela.com.
•	The winner will have to produce e-ticket along with his or her original passport and/or Emirates ID to claim the prize. No prizes will be handed over to any winner unless all requirements are provided to Weladela.com.
•	Any winner who is unable to present this ticket will lose the right to claim the prize.
•	Winners under the age of 18 (minor) must have a legal guardian who must be able to verify the winner’s identity by providing a valid ID to Weladela.com representative and evidence to support the nature of their relationship.
•	Weladela.com does not guarantee anything about the car and it will be subject to passing of fitness test by Government of UAE.
•	Any fraudulent or unauthorized use of the credit or debit card is strictly prohibited, and will result in disqualification from the draw.
•	WelaDela.com cannot be held liable for any loss, theft, damage or unauthorized use of a credit card, whether in the course of online buying process or after it.
•	When a ticket purchase is made through WelaDela.com, we may need to verify your method of payment, shipping address, before processing your order.
•	Once the draw is concluded, the seller is obligated to transfer the car in Buyer’s name within seven (7) days of the draw. In the event that the seller fails to do so, WelaDela.com reserves the right to replace that car with similar value car of any make and model which is either listed on the website or from any of its partner car dealers. 
•	The seller cannot offer for sale any car that is located outside of the UAE, does not belong to his ownership and/or do not have the rights to sell.
•	A nominal processing fee will be charged for sale of every car. This fee will be charged from the seller and will range from AED 250 to AED 1,000 depending upon the value of the car. This fee will only be charged once the sale has been made. No charges will apply in case of unsuccessful draw. 
•	In case the car fails to pass the test, it will be responsibility of seller to have the car repaired as pointed out in report.
•	In case the seller changes his mind about selling the car or manage to sell the car elsewhere, he or she is obligated to immediately notify WelDela.com about the same well before the draw date.
•	The seller is not eligible for purchasing ticket for that particular car’s raffle draw and will result in disqualification from the draw.
•	Seller agrees not to post, email, host, display, upload, modify, publish, transmit, update or share any information on the Site, or otherwise make available content that violates any law or regulation, that is copyrighted or patented, infringes any of the foregoing intellectual property rights of any party, and/or is harmful, abusive, unlawful, threatening, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another's privacy or other rights, hateful, or racially, ethnically objectionable, disparaging, and/or harasses, degrades, intimidates or is hateful towards any individual or group of individuals on the basis of religion, gender, sexual orientation, race, ethnicity, age, or disability and/or is false, deceptive, misleading, deceitful and/or misinforming.
•	WelaDela.com is dedicated to protecting the privacy and confidentiality of your personal information. WelaDela.com never rents or sells your details to any third party. Your data is stored securely on WelaDela.com’s database and will only be disclosed to our trusted partners for the purpose of operating WelaDela.com
•	By participating, winners & sellers consent that WelaDela.com may use and publish their names and photos as decided by Weladela.com to any person/s and/or institution, for promotional purposes in any media and/or in any mode or manner as deemed appropriate by Weladela.com without further payment or consideration. Refusal to provide these particulars may result to forfeiture of the prize. 
•	Other Terms and Conditions apply.

**Comment by ZarshaB** [comment]
3) Please change all "WelaDela.com" to "weladela.com" in terms and conditions.

**Comment by asifjans** [comment]
@sammiullah  Please get latest and fixed it. make sure there are two pages of terms and conditions
1) Register
2) Place Add / Place Order

**Comment by sammiullah** [comment]
fixed.

**Comment by ZarshaB** [comment]
Terms and conditions of "Place your Ad" and "Order Summary" pages are correct and verified.

"Terms and conditions" of "Register" page >> Please update them with the one provided above and also change "WelaDela.com" to "weladela.com" everywhere on this page.

**Comment by ZarshaB** [comment]
[Terms & Conditions.docx](https://github.com/asifjans/Inovedia/files/1689471/Terms.Conditions.docx)
