### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#55]

**Comment by ZarshaB** [comment]
1) What is ticket type in this?
![image](https://user-images.githubusercontent.com/35685146/35514505-386c0df0-0528-11e8-9415-6b93e41f9202.png)

**Comment by ZarshaB** [comment]
2) The text and content used in "new Customer" when Login/Register button is clicked should be as per the prescribed format. Content is not provided by client. What is the content?

**Comment by asifjans** [comment]
What will be the Title and Description for website as
![image](https://user-images.githubusercontent.com/10880558/35969316-47d50fc2-0ce8-11e8-88c5-ef1b9a786377.png)

**Comment by ZarshaB** [comment]
What would be the subject of email that is sent to Admin when "Buy Now" button is clicked.
