### ISSUE TITLE
Internal Feedback About Home page

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#58]
1. Login / Registter in green in mobile UI
2. logo top / bottom margin same, use logo with effect
3. in mobile UI show 2 cars in one row
4. -show hide  "App icon" according to the device
5. -how it section buttons overlapping issue.
6. we can show one box in one line
7. -in desktop/web show both icons of apps

**Comment by Anum444** [comment]
1) Fixed

**Comment by ZarshaB** [comment]
Fixed:
1, 2, 3
