### ISSUE TITLE
Email Templates

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#59]
@sammiullah  Please  show forgot and Reset password  email to Zursha and make sure emale template is 100% Approved, then you need to work on on other templates.

**Comment by ZarshaB** [comment]
1)Live Ad Email
 Please correct spelling mistake for "listing". Increase width of button. And decrease size of "Cheers" and "Team WelaDela".
![image](https://user-images.githubusercontent.com/35685146/35614740-e3397442-0691-11e8-9a02-e9f7d71f0ac3.png)

**Comment by ZarshaB** [comment]
2) Registration Template:
Please put full stop at highlighted place. And reduce size of cheers and team WelaDela.
![image](https://user-images.githubusercontent.com/35685146/35615227-57b53c1a-0693-11e8-8091-a0ec45e8d733.png)

**Comment by ZarshaB** [comment]
3) Welcome Template:
Please make "Happy Shopping" bold. Email should not disappear when cursor is taken to it. 
There should be space between link and Cheers. Reduce the size of "Cheers" and "Team WelaDela". 
Remove "Featured Ads" heading. "View Ad" should be little small in size.

![image](https://user-images.githubusercontent.com/35685146/35615900-581364be-0695-11e8-9598-374152b63f5d.png)

**Comment by ZarshaB** [comment]
4) Reset Password Template:
Template is not appearing correct as it is for other emails. Button is not correct in shape. Remove space between "Forgot your password.." and "Don't worry..." lines.
Reduce size of Cheers and Team WelaDela.

![image](https://user-images.githubusercontent.com/35685146/35616145-354cd11c-0696-11e8-9f05-534faea5f97e.png)

**Comment by ZarshaB** [comment]
5) Email template for "Buy Now".
Please remove "car" written.
Move "Car Make" above.
Make space between "Link" and "Customer Name".
There should be space between "City" and "Cheers'.
Reduce size of "Cheers" and "Team WelaDela".

![image](https://user-images.githubusercontent.com/35685146/35617092-09a422f6-0699-11e8-953d-2b9ab5490204.png)


Change Subject of Email. And Email should be sent to Admin.
![image](https://user-images.githubusercontent.com/35685146/35617133-2e529844-0699-11e8-8307-7d04bfdc8856.png)

**Comment by ZarshaB** [comment]
1) Live Email Template:
Cheers and WelaDela spacing is not correct. And weladela.com link should be as it is on other templates.
![image](https://user-images.githubusercontent.com/35685146/35673113-63c24a32-0762-11e8-8d74-001da040f77f.png)

**Comment by ZarshaB** [comment]
5) Could you please make the values semi bold? All else looks okay.
![image](https://user-images.githubusercontent.com/35685146/35676979-b1a1f8c6-076f-11e8-85cb-defdbc9ffef8.png)

**Comment by sammiullah** [comment]
All templates are fixed.

**Comment by ZarshaB** [comment]
Fixed = Verify your Account Template 
Not Fixed:
**Welcome Template** = Images are not appearing
![image](https://user-images.githubusercontent.com/35685146/35727949-c4e7ad7e-082b-11e8-88ad-b3aacd2b3fbf.png)

**Forgot Your Password** = Template is not appearing correctly
![image](https://user-images.githubusercontent.com/35685146/35728000-f356b042-082b-11e8-8927-55c411a6df43.png)

**Live Ad** = Please make weladela.com link same as other links of templates i.e. black text underlined and bold

Buy Now Template is okay but Subject is not correct

**Comment by sammiullah** [comment]
ALL links mentioned in the Email Templates are Fixed
The issue with the forgotPassword Template has been resolved.

**Comment by asifjans** [comment]
Same Please complete following tempaltes and other temlate if we have missed any. you can check on  wd (WIN-D9A9TBM4DHH) - Shortcut

1. Ticket Email template
2. Ticket Template

**Comment by asifjans** [comment]
@ZahidRavian  Please add template

**Comment by ZahidRavian** [comment]
It is fixed now.
