### ISSUE TITLE
Sprint II -My Account - My Profile

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#66]
•	My Profile

**Comment by sammiullah** [comment]
created --- > My Profile Page
created ----> Reset Password

**Comment by ZarshaB** [comment]
**My Profile:**
Gender, DOB, Hear About Us Fields are missing.

Spacing between Password and Nationality is very less.
![image](https://user-images.githubusercontent.com/35685146/35963840-dd6770f4-0cd7-11e8-8e25-246586669b8b.png)

Each field is not having an edit button.
It does not have a Save and Cancel button at the bottom.
It does not have option for uploading a picture.

**Comment by ZarshaB** [comment]
**Purchase History**

Message is not correct.
![image](https://user-images.githubusercontent.com/35685146/36061699-b450df30-0e7f-11e8-99cb-c49cd6f36da1.png)

It should be:
Ooops!!!
This place looks like The Empty Quarter. Lets fill it up and do some shopping cardio.
Go get ‘em Tiger!!!

**Comment by ZarshaB** [comment]
**My Profile:**
"Hear About Us" field is appearing empty whereas it should have value of Register form.
Also when I save Hear about Us field and click on Save button then still it becomes empty.
![image](https://user-images.githubusercontent.com/35685146/36061730-413b16cc-0e80-11e8-8561-fe47e0570e4c.png)

**Comment by ZarshaB** [comment]
**My Ads:**
It should also be a button to maintain consistency.
![image](https://user-images.githubusercontent.com/35685146/36061759-a806330a-0e80-11e8-8c0d-056064e30542.png)

**Comment by ZarshaB** [comment]
**FAQs**
These questions in General section are repeating. Please remove these three.
![image](https://user-images.githubusercontent.com/35685146/36061828-2c81893a-0e82-11e8-93ba-0663bf151f95.png)

**Comment by ZarshaB** [comment]
**Point Redeem Policy**

1) Please replace WelaDela.com to "weladela.com" everywhere on this page.
2) Point number is 2.5 which is missing and also make 2.6 bold.
![image](https://user-images.githubusercontent.com/35685146/36062177-8be1b43a-0e88-11e8-9a8d-a3371d478a45.png)

**Comment by asifjans** [comment]
those are fixed, Please remove.

**Comment by ZarshaB** [comment]
FAQs:
1) Two repeating questions are removed and one is left. Please also remove this one.
![image](https://user-images.githubusercontent.com/35685146/36088252-28ed4c9c-0ff8-11e8-94df-4976d93318cd.png)

**Comment by ZarshaB** [comment]
**My Profile:**
1) "Hear About Us" field is now not appearing empty whereas it also not showing value from Register form.
Also when I save Hear about Us field and click on Save button then still it changes to others.
![image](https://user-images.githubusercontent.com/35685146/36090770-6dbe9a64-1003-11e8-8c37-a291787fa4b5.png)


2) It does not have option for uploading a picture.

**Comment by ZarshaB** [comment]
**Point Redeem Policy:**
1,2,3 are fixed.
"WelaDela" was correct I only asked for changing WelaDela.com to "weladela.com".
Please change "weladela" to "WelaDela" on all places.

**Comment by sammiullah** [comment]
Point Redeem Policy:  resolved
My Profile: "Hear About Us" resolved
FAQs: resolved

**Comment by ZahidRavian** [comment]
@sammiullah 
Please make below screens according to design.
My Favorites
Redeem Points
Purchase History

![my-purchase](https://user-images.githubusercontent.com/17255154/36112040-1a07870e-104a-11e8-94fd-1cf04f95599f.png)
![no-purchase-history](https://user-images.githubusercontent.com/17255154/36112042-1a3bb592-104a-11e8-9d91-9f3af91de651.png)
![no-reward](https://user-images.githubusercontent.com/17255154/36112043-1a6abf40-104a-11e8-9191-b5e03857b77a.png)
![redeem-points](https://user-images.githubusercontent.com/17255154/36112044-1a9d9686-104a-11e8-8790-c445012b8d66.png)

**Comment by ZarshaB** [comment]
**FAQs**
I asked for removing repeating question not to remove question entirely. :face_with_head_bandage: 

Please add:
What is the price of a ticket?
The price of ticket depends on the value of the car. It ranges from AED 25 to AED 1,000.

![image](https://user-images.githubusercontent.com/35685146/36155565-82796abc-10f6-11e8-898f-6c567adb1c2e.png)

**Comment by ZarshaB** [comment]
**My Profile:**
Hear About Us issue is fixed.
2) It does not have option for uploading a picture.

**Comment by ZarshaB** [comment]
**Point Redeem Policy:**
Issue is Fixed.
