### ISSUE TITLE
View Cars 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#68]

**Comment by ZarshaB** [comment]
1) Please make it bold and in centre.
![image](https://user-images.githubusercontent.com/35685146/35620161-1bcc641c-06a2-11e8-89a0-c6624adf2b0c.png)

**Comment by ZarshaB** [comment]
2) Please remove this line below AED and also reduce space.
![image](https://user-images.githubusercontent.com/35685146/35620181-2c97f004-06a2-11e8-9340-61baeff67e35.png)

**Comment by Anum444** [comment]
1 & 2 **Fixed**
