### ISSUE TITLE
Home 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#69]

**Comment by ZarshaB** [comment]
1) Seller and Buyer text of button should be a little left aligned and in centre.
![image](https://user-images.githubusercontent.com/35685146/35620250-69af6dc8-06a2-11e8-8f1e-171766eda004.png)

**Comment by ZarshaB** [comment]
2) Please ad other content for this.
![image](https://user-images.githubusercontent.com/35685146/35620279-81bb9022-06a2-11e8-90c9-3c90ab58db78.png)

**Comment by Anum444** [comment]
1 & 2 **Fixed**
