### ISSUE TITLE
Sprint II - Contact Us 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#76]

**Comment by ZarshaB** [comment]
**Contact Us:**
Images are stretched.
Spacing is not correct.
Button is very small.
It should be Email Id.
It should be bold.
![image](https://user-images.githubusercontent.com/35685146/35964480-ac9afd54-0cd9-11e8-80d7-0f00753fce64.png)
![image](https://user-images.githubusercontent.com/35685146/35964490-b36f2f1a-0cd9-11e8-9688-720074fbb295.png)

**Template:**
![image](https://user-images.githubusercontent.com/35685146/35964508-c06a2a44-0cd9-11e8-935c-7c6448ea8c54.png)

**Comment by Anum444** [comment]
Please take a look &  give feedback.

**Comment by ZarshaB** [comment]
1) Please correct the spelling and make it "secrets".
![image](https://user-images.githubusercontent.com/35685146/36062031-162112d8-0e86-11e8-9a5a-f1ec8df57e3c.png)

**Comment by Anum444** [comment]
1 **Fixed**

**Comment by ZarshaB** [comment]
1,2 are Fixed.

3) Please make the font size same as it in template.
