### ISSUE TITLE
Sprint II - About Us

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#77]

**Comment by ZarshaB** [comment]
About Us
Terms and Conditions
Tips on Buying Tickets
FAQs
Point Redeem Policy

**Comment by ZarshaB** [comment]
1) It should have some hover effect or effect like menu bar have when cursor is taken to any option,
![image](https://user-images.githubusercontent.com/35685146/36061780-271eb4be-0e81-11e8-8641-665e93ec8a83.png)

**Comment by Anum444** [comment]
It should have some hover effect or effect like menu bar have when cursor is taken to any option, **(Fixed)**

**Comment by ZarshaB** [comment]
Okay Fixed.
