### ISSUE TITLE
Sprint II - My Account - Purchase History

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#79]

**Comment by asifjans** [comment]
Ready for testing

**Comment by ZarshaB** [comment]
**Purchase History**

Message is not correct.
![image](https://user-images.githubusercontent.com/35685146/36061699-b450df30-0e7f-11e8-99cb-c49cd6f36da1.png)

It should be:
Ooops!!!
This place looks like The Empty Quarter. Lets fill it up and do some shopping cardio.
Go get ‘em Tiger!!!

**Comment by ZarshaB** [comment]
2) It should be bold.
![image](https://user-images.githubusercontent.com/35685146/36062317-fdec92e0-0e8b-11e8-80f8-1e58e25ad12b.png)

**Comment by Anum444** [comment]
1 & 2 **Fixed**

**Comment by ZarshaB** [comment]
1) Fixed.
