### ISSUE TITLE
API - Manage Accounts - Browse Accounts - Edit Account 

### ISSUE THREAD

**Issue by ZahidRavian** [asifjans/Inovedia#8]
1) In Service Tab - Callback
When I clicked on copy, "Alias" field remain empty.

2) In Service Tab - Call Forward Selective
Days are not Adding and Updating.

3) In Service Tab - Voice Mail and PBX - Actions (DTMF)
"Invalid Entry" is not Adding and Updating

**Comment by nawabanjum** [comment]
Implemented plz test it .

**Comment by ZahidRavian** [comment]
Issue number 3 is not resolved

3) In Service Tab - Voice Mail and PBX - Actions (DTMF)
"Invalid Entry" is not Adding and Updating

**Comment by nawabanjum** [comment]
API - Manage Accounts - Browse Accounts - Edit Account
In Service Tab - Voice Mail and PBX - Actions (DTMF)
"Invalid Entry which value wil be show
