### ISSUE TITLE
Sprint II - My Account - Reward Points

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#80]

**Comment by ZarshaB** [comment]
1) Color of box should be orange.
![image](https://user-images.githubusercontent.com/35685146/35980797-73976e96-0d0d-11e8-9c5b-77261bee27ed.png)

**Comment by Anum444** [comment]
Please take a look & give your feedback.

**Comment by ZarshaB** [comment]
1) This page is missing second table of "Redeem History".

**Comment by ZarshaB** [comment]
2) Please make it bold.
![image](https://user-images.githubusercontent.com/35685146/36062309-d64cf7a2-0e8b-11e8-8e29-5a28132466a4.png)

**Comment by Anum444** [comment]
No# : 2 **Fixed**

**Comment by ZarshaB** [comment]
Okay Yes 1 and 2 are fixed.
Please also make these bold.
![image](https://user-images.githubusercontent.com/35685146/36091056-449b29a8-1004-11e8-9286-ce1aa1367031.png)

**Comment by ZarshaB** [comment]
It updates my reward points after I logged in whereas it should display at the same time.

**Comment by ZahidRavian** [comment]
Above issues are fixed now.

**Comment by ZarshaB** [comment]
Showing double line.
![image](https://user-images.githubusercontent.com/35685146/36138976-8bca27c0-10bd-11e8-862c-c651fa20d93f.png)

**Comment by ZarshaB** [comment]
2 is fixed.
1 is not fixed.

**Comment by ZarshaB** [comment]
4) Fields are centre aligned. And heading size is very large.
![image](https://user-images.githubusercontent.com/35685146/36153948-b47c176c-10f1-11e8-8837-015414080921.png)
![image](https://user-images.githubusercontent.com/35685146/36153961-bfa520a2-10f1-11e8-90c8-6bbef3fb0a89.png)
