### ISSUE TITLE
Sprint II - How it works.

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#85]
1) It should not have download option.
![image](https://user-images.githubusercontent.com/35685146/36061607-18b8910e-0e7e-11e8-8583-aaf68a3d4027.png)

**Comment by ZarshaB** [comment]
2) How it works of Footer is not working.
![image](https://user-images.githubusercontent.com/35685146/36061620-2f45d4c2-0e7e-11e8-9724-d8397763d1ee.png)

**Comment by Anum444** [comment]
1 , 2  **Fixed**

**Comment by ZarshaB** [comment]
Fixed.
