### ISSUE TITLE
Sir Tanzeel's Feedback

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#86]

**Comment by ZarshaB** [comment]
1) Please remove this line from logo. It should be same as it is from downwards.
![image](https://user-images.githubusercontent.com/35685146/36099437-7d136366-1024-11e8-9ac0-1e3bc4fb8f27.png)

**Comment by ZarshaB** [comment]
2) Search field should be in centre. It should have same font, boldness and hover effect as it is for "Login/Register" button.
![image](https://user-images.githubusercontent.com/35685146/36099528-cacd21e6-1024-11e8-9444-96d25d862cba.png)

**Comment by ZarshaB** [comment]
3) Loader of  Pop up of Featured Cars should be same as View Cars page as for Home page it is extended.

**Comment by ZarshaB** [comment]
4) Pop up description should have same borders around description as it has for Detail.
![image](https://user-images.githubusercontent.com/35685146/36099674-4e1761ba-1025-11e8-8475-2085a2327744.png)
![image](https://user-images.githubusercontent.com/35685146/36099691-5a034142-1025-11e8-9424-d85697b2b775.png)

**Comment by ZarshaB** [comment]
5) Please reduce spacing.
![image](https://user-images.githubusercontent.com/35685146/36099717-6fee503c-1025-11e8-8b8e-2c8dda62db65.png)

**Comment by ZarshaB** [comment]
6) Images are appearing stretched.
![image](https://user-images.githubusercontent.com/35685146/36099752-8c38666a-1025-11e8-949f-d4d762a33354.png)

**Comment by ZarshaB** [comment]
7) Arrows are appearing blur.
![image](https://user-images.githubusercontent.com/35685146/36099788-b8d48956-1025-11e8-8343-7d5d2667034c.png)

**Comment by ZarshaB** [comment]
8) Images are stretched.
![image](https://user-images.githubusercontent.com/35685146/36099922-2bb6ee1e-1026-11e8-9a1d-55ea4ec5d896.png)

**Comment by ZarshaB** [comment]
9) Timer should be fixed at bottom and images should not be stretched.
![image](https://user-images.githubusercontent.com/35685146/36100065-c56fc666-1026-11e8-9d34-110d81012773.png)

**Comment by ZarshaB** [comment]
10) Heading would be in one line and it would have dots at the end. And color of heading would be same as "Search Filter".
![image](https://user-images.githubusercontent.com/35685146/36100147-17e44cf0-1027-11e8-8b7e-d232c5b23efe.png)

**Comment by ZarshaB** [comment]
11) Video will cover the whole page.
![image](https://user-images.githubusercontent.com/35685146/36100194-3c6287fe-1027-11e8-8524-688adc6e4f2b.png)

**Comment by ZarshaB** [comment]
12) Gender will appear in one line.
![image](https://user-images.githubusercontent.com/35685146/36100242-6c6e609e-1027-11e8-8ea2-dd9b26a5294a.png)

**Comment by ZarshaB** [comment]
13) Alignment of both boxes is not same.
![image](https://user-images.githubusercontent.com/35685146/36100291-8fec36fe-1027-11e8-80f3-305f25967cb0.png)

**Comment by ZarshaB** [comment]
14) Please change the alignment of captcha to right and of check boxes to left.
![image](https://user-images.githubusercontent.com/35685146/36100338-bb5ddbd0-1027-11e8-822c-282844a433f4.png)

**Comment by ZarshaB** [comment]
15) Icons are appearing stretched.
![image](https://user-images.githubusercontent.com/35685146/36100458-24c5d0e6-1028-11e8-9e65-0181277be411.png)

**Comment by ZarshaB** [comment]
16) Please remove time from DOB.
![image](https://user-images.githubusercontent.com/35685146/36100481-3959aeec-1028-11e8-99b4-66cf52c86aec.png)

**Comment by ZarshaB** [comment]
17) Plus/minus icons are not appearing. And also font size is not same as template.
![image](https://user-images.githubusercontent.com/35685146/36100573-81c729e8-1028-11e8-9cf0-a7a33c3c9602.png)

**Comment by ZarshaB** [comment]
18) On selecting "Seller" , "General" icon moves downwards.

**Comment by ZarshaB** [comment]
19) Please remove this heading.
![image](https://user-images.githubusercontent.com/35685146/36100616-aba4f524-1028-11e8-8069-7097a7dd3259.png)

**Comment by ZarshaB** [comment]
20) Please make it's alignment same as "Point Redeem Policy" i.e. starting below "How it works".
![image](https://user-images.githubusercontent.com/35685146/36100671-d820ee6e-1028-11e8-8334-a2b6c9f0c278.png)

**Comment by ZarshaB** [comment]
21) Email template is appearing stretched on mobile. And also on clicking on link the page that appears has so much extra space on mobile.

**Comment by ZarshaB** [comment]
22) Also please change the name and images of Testimonials.

**Comment by asifjans** [comment]
4, 5, 8 (Fixed)

**Comment by ZarshaB** [comment]
8>> It is fixed but please make space between Follow Us and Icons as it is between Powered by and icon.
![image](https://user-images.githubusercontent.com/35685146/36141446-8ef77a70-10c6-11e8-91fd-bd2503ac9d87.png)

**Comment by ZarshaB** [comment]
4 = Fixed
5 = Not Fixed

**Comment by ZarshaB** [comment]
9>> All pages' headings space should be same. Also "Our Featured Cars" and "How it works" heading should have same space.
![image](https://user-images.githubusercontent.com/35685146/36154126-4a97d8e4-10f2-11e8-9148-5f25e1f2bafe.png)
![image](https://user-images.githubusercontent.com/35685146/36154138-51d60612-10f2-11e8-9cf7-daf3b0b400c3.png)
