### ISSUE TITLE
UI - Admin Portal

### ISSUE THREAD

**Issue by ZahidRavian** [asifjans/Inovedia#88]
Url: http://admin.weladela.com/
Username: admin@weladela.com
Password: 123456

**Comment by shayanr262** [comment]
Unable to update the price of ad.
![Uploading ask_price.PNG…]()

**Comment by shayanr262** [comment]
First_Name column showing data of dates.
![first_name](https://user-images.githubusercontent.com/35724117/36261428-1f56ed74-1286-11e8-872b-8359580f38f1.PNG)

**Comment by shayanr262** [comment]
Reward section is missing:
• Admin should have option of reversing the reward points from customer in case he claims the refund.
• Admin should have option for deleting all the reward points for the winners. 
• Admin should have option to delete anybody’s reward points or give them bonus reward points into account.
• It should be able to generate the report of purchases made against report with user details, car details for which ticket is purchased, additional cash paid for ticket etc.

**Comment by shayanr262** [comment]
Transfer ticket functionality is not working. It gives message of "No record found" regardless record is exists

**Comment by shayanr262** [comment]
Source name is missing.
![source](https://user-images.githubusercontent.com/35724117/36298003-998f273c-1317-11e8-9288-ce4173dae5ce.PNG)

**Comment by shayanr262** [comment]
On clicking View details button it gives error message of "An error occurred while processing your request."
![view_det](https://user-images.githubusercontent.com/35724117/36298429-ed0f5be6-1319-11e8-90a9-15b313881995.PNG)

**Comment by shayanr262** [comment]
New ad:
For transfer, a new ticket number should be generated.

**Comment by shayanr262** [comment]
Raffle draw should only available when ad is expired

**Comment by shayanr262** [comment]
Ads filters not working
![ads_filters](https://user-images.githubusercontent.com/35724117/36303228-3dc39896-132d-11e8-8b50-d12eed6b17b0.PNG)

**Comment by shayanr262** [comment]
On clicking ticket refund report section it gives following error. 
An error occurred while processing your request."

**Comment by shayanr262** [comment]
Asking price should be editable only when ad is in pending state.
![ask_price](https://user-images.githubusercontent.com/35724117/36303935-aef30d6a-132f-11e8-94f7-d26bb76f1e2e.PNG)

**Comment by shayanr262** [comment]
ticket transfer report search filters not wokring
![tkt_trans](https://user-images.githubusercontent.com/35724117/36304075-2daeeb6a-1330-11e8-971c-905689fbb9e1.PNG)

**Comment by zohaibqadir** [comment]
1 First_Name column showing data of dates.
FIXED
3. On clicking ticket refund report section it gives following error.
An error occurred while processing your request."
FIXED
4. ticket transfer report search filters not wokring
FIXED
5. Source name is missing.
will handle on website

**Comment by zohaibqadir** [comment]
2. Raffle draw should only available when ad is expired
Fixed

**Comment by shayanr262** [comment]
On search filters it should not be mandatory to give both date_from and date_to field information. User can search by giving information on either date_from and date_to field .
