### ISSUE TITLE
UI - Manage Accounts - Browse Accounts - Edit Account

### ISSUE THREAD

**Issue by ZahidRavian** [asifjans/Inovedia#9]
1) On Account Create and Update, remove the popup message. "Account successfully created" and "Account successfully updated" 

2) In Service Tab - Mobile Sims
Grid height is max as compare to other Service grids.

3) In Service Tab - Voice Mail and PBX
Grid height is max as compare to other Service grids.

4) In Service Tab - Call Forward Selective
On Add/Edit Popup, when the check box "Specify Active Days" will be unchecked, all days will be checked and disabled. and when it is checked all days will be enabled.

**Comment by nawabanjum** [comment]
Done

**Comment by ZahidRavian** [comment]
Please check this issue

4) In Service Tab - Call Forward Selective
On Add/Edit Popup, when the check box "Specify Active Days" will be unchecked, all days will be checked and disabled. and when it is checked all days will be enabled.

**Comment by nawabanjum** [comment]
done
